Repository bcgov/sbc-auth, pull requests merged in 2020-09, with the labels that each got.

#974 4660 - align session storage constant w/ entities
  auth-web/src/util/constants.ts
Labels: bug

#987 Dev to Test
  auth-web/src/store/modules/user.ts
  auth-web/src/util/constants.ts
Labels: skip-changelog

#986 Statement fixes
  auth-web/src/components/auth/Statements.vue
  auth-web/src/components/auth/StatementsSettings.vue
Labels: skip-changelog

#988 Staff dashboard - filter by account name#4510
  auth-web/src/components/auth/staff/StaffActiveAccountsTable.vue
Labels: enhancement

#989 Test Deployment
  auth-web/src/components/auth/Statements.vue
  auth-web/src/components/auth/StatementsSettings.vue
  auth-web/src/components/auth/staff/StaffActiveAccountsTable.vue
Labels: skip-changelog

#990 Statements message
  auth-web/src/components/auth/StatementsSettings.vue
  auth-web/src/models/statement.ts
  auth-web/src/services/payment.services.ts
  auth-web/src/store/modules/org.ts
Labels: enhancement

#992 Statement member restriction
  auth-api/migrations/versions/032248a1b370_create_statement_permissions.py
  auth-api/src/auth_api/schemas/membership.py
  auth-api/src/auth_api/schemas/user.py
  auth-web/src/components/auth/StatementsSettings.vue
  auth-web/src/models/user.ts
  auth-web/src/util/common-util.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/AccountSettings.vue
Labels: enhancement

#995 director search account should only be accessible to Admins
  auth-api/requirements.txt
  auth-api/src/auth_api/models/org.py
  auth-api/src/auth_api/resources/org.py
  auth-api/src/auth_api/services/org.py
Labels: enhancement

#994 [entity4510] Minor UI Fixes for Account Name Filter
  auth-web/src/components/auth/staff/StaffActiveAccountsTable.vue
Labels: skip-changelog

#997 dev to test merge
  auth-api/requirements.txt
  auth-api/src/auth_api/models/org.py
  auth-api/src/auth_api/resources/org.py
  auth-api/src/auth_api/services/org.py
  auth-web/src/components/auth/staff/StaffActiveAccountsTable.vue
Labels: skip-changelog

#998 Added tests , fixed the syntax
  auth-api/src/auth_api/services/org.py
  auth-api/tests/unit/api/test_org.py
  auth-api/tests/utilities/factory_scenarios.py
Labels: bug

#1001 changes for reset otp api
  auth-api/migrations/versions/eff007a689cb_add_reset_otp_permission.py
  auth-api/src/auth_api/resources/user.py
  auth-api/src/auth_api/services/user.py
  auth-api/tests/unit/api/test_user.py
  auth-api/tests/unit/services/test_user.py
  auth-api/tests/utilities/factory_scenarios.py
  auth-api/tests/utilities/factory_utils.py
Labels: enhancement

#1002 alembic heads fixed
  auth-api/migrations/versions/d1b167ef61da_merge_heads.py
  auth-api/migrations/versions/eff007a689cb_add_reset_otp_permission.py
Labels: skip-changelog

#1004 removing the disable otp api call for lower kc version
  auth-api/src/auth_api/services/keycloak.py
Labels: enhancement

#1003 Admin/Coordinator resets one-time password authenticator #3239
  auth-web/jest.config.js
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/src/App.vue
  auth-web/src/components/auth/InvitationsDataTable.vue
  auth-web/src/components/auth/MemberDataTable.vue
  auth-web/src/components/auth/PendingMemberDataTable.vue
  auth-web/src/components/auth/Statements.vue
  auth-web/src/components/auth/TransactionsDataTable.vue
  auth-web/src/components/auth/UserManagement.vue
  auth-web/src/components/auth/mixins/TeamManagementMixin.vue
  auth-web/src/locales/en.json
  auth-web/src/models/Organization.ts
  auth-web/src/services/user.services.ts
  auth-web/src/store/modules/user.ts
  auth-web/src/util/common-util.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/AccountSettings.vue
  auth-web/src/vue-test-utils-helpers.d.ts
  auth-web/tests/unit/components/MemberDataTable.spec.ts
  auth-web/tests/unit/util/MockRouter.ts
Labels: feature

#1010 Adding audit columns to version tables
  auth-api/migrations/versions/f91bcb97f2c2_adding_audit_columns_to_version_table.py
  auth-api/src/auth_api/models/base_model.py
Labels: bug

#1011 Broken link in Terms and condition#4236
  auth-api/migrations/versions/0bf25945e757_update_broken_link_tos.py
Labels: bug

#1013 fixing migration heads
  auth-api/migrations/versions/66ae9d618842_merge_heads.py
Labels: skip-changelog

#1007 Switch CD process to composite action.
  .github/workflows/auth-api-cd.yml
  .github/workflows/auth-web-cd.yml
  .github/workflows/notify-api&queue-cd.yml
  .github/workflows/status-api-cd.yml
  scripts/1pass.sh
  scripts/install_tools.sh
Labels: devops

#1014 Update cd action version to latest.
  .github/workflows/auth-api-cd.yml
  .github/workflows/auth-web-cd.yml
  .github/workflows/notify-api&queue-cd.yml
  .github/workflows/status-api-cd.yml
Labels: skip-changelog

#1015 Test Deployment
  .github/workflows/auth-api-cd.yml
  .github/workflows/auth-web-cd.yml
  .github/workflows/notify-api&queue-cd.yml
  .github/workflows/status-api-cd.yml
  auth-api/migrations/versions/0bf25945e757_update_broken_link_tos.py
  auth-api/migrations/versions/66ae9d618842_merge_heads.py
  auth-api/migrations/versions/f91bcb97f2c2_adding_audit_columns_to_version_table.py
  auth-api/src/auth_api/models/base_model.py
  scripts/1pass.sh
  scripts/install_tools.sh
Labels: skip-changelog

#1016 Search by username in manage team#4339
  auth-web/src/components/auth/MemberDataTable.vue
  auth-web/src/components/auth/PendingMemberDataTable.vue
  auth-web/src/components/auth/UserManagement.vue
Labels: enhancement

#1012 staff UI direct routes and pagiantion improvements
  auth-web/src/components/auth/mixins/PaginationMixin.vue
  auth-web/src/components/auth/staff/StaffAccountManagement.vue
  auth-web/src/components/auth/staff/StaffActiveAccountsTable.vue
  auth-web/src/components/auth/staff/StaffPendingAccountInvitationsTable.vue
  auth-web/src/components/auth/staff/StaffPendingAccountsTable.vue
  auth-web/src/components/auth/staff/StaffRejectedAccountsTable.vue
  auth-web/src/routes/router.ts
  auth-web/src/util/common-util.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/staff/ReviewAccountView.vue
  auth-web/src/views/auth/staff/StaffDashboardView.vue
  auth-web/tests/unit/views/SearchBusinessView.spec.ts
Labels: enhancement

#1017 Restore scripts.
  scripts/1pass.sh
  scripts/install_tools.sh
Labels: skip-changelog

#1018 Changes reference of staff dashboard page
  auth-web/src/components/auth/mixins/PaginationMixin.vue
  auth-web/src/components/auth/staff/SetupAccountForm.vue
  auth-web/src/components/auth/staff/StaffAccountManagement.vue
  auth-web/src/routes/router.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/AccountSettings.vue
  auth-web/src/views/auth/staff/ReviewAccountView.vue
  auth-web/src/views/auth/staff/SetupAccountSuccessView.vue
Labels: enhancement

#1020 dev to test merge
  auth-web/src/components/auth/MemberDataTable.vue
  auth-web/src/components/auth/PendingMemberDataTable.vue
  auth-web/src/components/auth/UserManagement.vue
  auth-web/src/components/auth/mixins/PaginationMixin.vue
  auth-web/src/components/auth/staff/SetupAccountForm.vue
  auth-web/src/components/auth/staff/StaffAccountManagement.vue
  auth-web/src/components/auth/staff/StaffActiveAccountsTable.vue
  auth-web/src/components/auth/staff/StaffPendingAccountInvitationsTable.vue
  auth-web/src/components/auth/staff/StaffPendingAccountsTable.vue
  auth-web/src/components/auth/staff/StaffRejectedAccountsTable.vue
  auth-web/src/routes/router.ts
  auth-web/src/util/common-util.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/AccountSettings.vue
  auth-web/src/views/auth/staff/ReviewAccountView.vue
  auth-web/src/views/auth/staff/SetupAccountSuccessView.vue
  auth-web/src/views/auth/staff/StaffDashboardView.vue
  auth-web/tests/unit/views/SearchBusinessView.spec.ts
  scripts/1pass.sh
  scripts/install_tools.sh
Labels: skip-changelog

#1021 adding the missed redirection for 'staff' route
  auth-web/src/routes/router.ts
  auth-web/src/util/constants.ts
Labels: enhancement

#1022 adding the missed redirection (#1021)
  auth-web/src/routes/router.ts
  auth-web/src/util/constants.ts
Labels: skip-changelog

#1019 Create a Reusable component for Search Filter#5010
  auth-web/src/components/auth/AnonymousUserManagement.vue
  auth-web/src/components/auth/UserManagement.vue
  auth-web/src/components/auth/common/SearchFilterInput.vue
  auth-web/src/components/auth/staff/StaffActiveAccountsTable.vue
  auth-web/src/models/searchfilter.ts
Labels: skip-changelog

#1023 Test Deployment
  auth-web/src/components/auth/AnonymousUserManagement.vue
  auth-web/src/components/auth/UserManagement.vue
  auth-web/src/components/auth/common/SearchFilterInput.vue
  auth-web/src/components/auth/staff/StaffActiveAccountsTable.vue
  auth-web/src/models/searchfilter.ts
Labels: skip-changelog

#1025 [entity4339] UI Clean-up
  auth-web/src/components/auth/AnonymousUserManagement.vue
  auth-web/src/components/auth/MemberDataTable.vue
  auth-web/src/components/auth/UserManagement.vue
  auth-web/src/components/auth/common/SearchFilterInput.vue
  auth-web/src/components/auth/mixins/TeamManagementMixin.vue
Labels: enhancement

#1026 Test Deployment
  auth-web/src/components/auth/AnonymousUserManagement.vue
  auth-web/src/components/auth/MemberDataTable.vue
  auth-web/src/components/auth/UserManagement.vue
  auth-web/src/components/auth/common/SearchFilterInput.vue
  auth-web/src/components/auth/mixins/TeamManagementMixin.vue
Labels: skip-changelog

#1028 TOS service screen not appearing #5051
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/src/store/modules/user.ts
Labels: bug

#1029 Test Deployment
  .github/workflows/auth-api-cd.yml
  .github/workflows/auth-web-cd.yml
  .github/workflows/notify-api&queue-cd.yml
  .github/workflows/status-api-cd.yml
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/src/store/modules/user.ts
Labels: skip-changelog

#1030 Show Reset OTP for view staff roles
  auth-api/src/auth_api/resources/user.py
  auth-web/src/util/common-util.ts
Labels: enhancement

#1031 Test Deployment
  auth-api/src/auth_api/resources/user.py
  auth-web/src/util/common-util.ts
Labels: skip-changelog

#1024 search filter unit tests
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/src/components/auth/common/SearchFilterInput.vue
  auth-web/tests/unit/components/SearchFilterInput.spec.ts
Labels: skip-changelog

#1035 Search by username on transaction view#4341
  auth-web/src/components/auth/Transactions.vue
  auth-web/src/components/auth/TransactionsDataTable.vue
  auth-web/src/components/auth/common/DateRangeFilter.vue
  auth-web/src/components/auth/common/SearchFilterInput.vue
  auth-web/src/models/searchfilter.ts
  auth-web/src/models/transaction.ts
  auth-web/src/services/payment.services.ts
  auth-web/src/store/modules/org.ts
Labels: enhancement

#1036 Test Deployment
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/src/components/auth/Transactions.vue
  auth-web/src/components/auth/TransactionsDataTable.vue
  auth-web/src/components/auth/common/DateRangeFilter.vue
  auth-web/src/components/auth/common/SearchFilterInput.vue
  auth-web/src/models/searchfilter.ts
  auth-web/src/models/transaction.ts
  auth-web/src/services/payment.services.ts
  auth-web/src/store/modules/org.ts
  auth-web/tests/unit/components/SearchFilterInput.spec.ts
Labels: skip-changelog

#1037 Orange banner displays when an entity dashboard is restored from a bookmark#4918
  auth-web/package-lock.json
  auth-web/package.json
Labels: skip-changelog

#1038 Test Deployment
  auth-web/package-lock.json
  auth-web/package.json
Labels: skip-changelog

#1039 search filter unit tests + minor ui fixes
  auth-web/src/components/auth/AnonymousUserManagement.vue
  auth-web/src/components/auth/Transactions.vue
  auth-web/src/components/auth/UserManagement.vue
  auth-web/src/components/auth/common/DateRangeFilter.vue
  auth-web/src/components/auth/common/SearchFilterInput.vue
  auth-web/src/components/auth/staff/StaffActiveAccountsTable.vue
  auth-web/src/util/constants.ts
  auth-web/tests/unit/components/DateRangeFilter.spec.ts
  auth-web/tests/unit/components/SearchFilterInput.spec.ts
  auth-web/tests/unit/util/common-util.spec.ts
Labels: skip-changelog

#1040 Test Deployment
  auth-web/src/components/auth/AnonymousUserManagement.vue
  auth-web/src/components/auth/Transactions.vue
  auth-web/src/components/auth/UserManagement.vue
  auth-web/src/components/auth/common/DateRangeFilter.vue
  auth-web/src/components/auth/common/SearchFilterInput.vue
  auth-web/src/components/auth/staff/StaffActiveAccountsTable.vue
  auth-web/src/util/constants.ts
  auth-web/tests/unit/components/DateRangeFilter.spec.ts
  auth-web/tests/unit/components/SearchFilterInput.spec.ts
  auth-web/tests/unit/util/common-util.spec.ts
Labels: skip-changelog

#1041 5128 update bcomp legal type
  auth-web/src/util/constants.ts
Labels: feature
