Repository bcgov/sbc-auth, pull requests merged in 2020-11, with the labels that each got.

#1107 PAD Payment Method - See Confirmation Period Details
  auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
  auth-web/src/components/auth/common/PADInfoForm.vue
  auth-web/src/components/auth/common/PaymentMethods.vue
  auth-web/src/models/Organization.ts
Labels: enhancement

#1108 QA Deployment
  auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
  auth-web/src/components/auth/common/PADInfoForm.vue
  auth-web/src/components/auth/common/PaymentMethods.vue
  auth-web/src/models/Organization.ts
Labels: skip-changelog

#1109 Fix for retaining acc name if user switch between linked and unlinked premiums
  auth-web/src/components/auth/common/PaymentMethods.vue
  auth-web/src/components/auth/create-account/AccountTypeSelector.vue
  auth-web/src/components/auth/create-account/PaymentMethodSelector.vue
  auth-web/src/components/auth/create-account/PremiumChooser.vue
  auth-web/src/store/modules/org.ts
  auth-web/tests/unit/components/DateRangeFilter.spec.ts
  auth-web/tests/unit/components/PaymentMethods.spec.ts
Labels: skip-changelog

#1111 Changing config keys
  queue_services/account-mailer/src/account_mailer/config.py
  queue_services/events-listener/src/events_listener/config.py
Labels: skip-changelog

#1112 Hide payment methods for Members and Coordinators#5548
  auth-api/migrations/versions/c51a33f55be6_create_payment_methods_permission.py
  auth-api/requirements.txt
  auth-web/src/util/common-util.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/AccountSettings.vue
Labels: bug

#1113 QA Deployment
  auth-api/migrations/versions/c51a33f55be6_create_payment_methods_permission.py
  auth-api/requirements.txt
  auth-web/src/util/common-util.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/AccountSettings.vue
  queue_services/account-mailer/src/account_mailer/config.py
  queue_services/events-listener/src/events_listener/config.py
Labels: skip-changelog

#1116 redirecting user to account info, if not admin, during account switch
  auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
Labels: skip-changelog

#1115 entity5364 - Fix Language / Color Inconsistencies in Team Member Confirmation Dialogs
  auth-web/src/components/auth/account-settings/team-management/InviteUsersForm.vue
  auth-web/src/components/auth/account-settings/team-management/MemberDataTable.vue
  auth-web/src/components/auth/account-settings/team-management/UserManagement.vue
  auth-web/src/components/auth/mixins/TeamManagementMixin.vue
  auth-web/src/locales/en.json
  auth-web/tests/unit/components/MemberDataTable.spec.ts
Labels: skip-changelog

#1117 QA Deployment
  auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
  auth-web/src/components/auth/account-settings/team-management/InviteUsersForm.vue
  auth-web/src/components/auth/account-settings/team-management/MemberDataTable.vue
  auth-web/src/components/auth/account-settings/team-management/UserManagement.vue
  auth-web/src/components/auth/mixins/TeamManagementMixin.vue
  auth-web/src/locales/en.json
  auth-web/tests/unit/components/MemberDataTable.spec.ts
Labels: skip-changelog

#1118 [entity5596] Fix Missing Labels for Search Component Inputs
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/components/auth/common/PADInfoForm.vue
  auth-web/src/components/auth/common/PaymentMethods.vue
  auth-web/src/components/auth/common/SearchFilterInput.vue
  auth-web/src/views/auth/AccountSettings.vue
  auth-web/tests/unit/components/SearchFilterInput.spec.ts
Labels: skip-changelog

#1114 5301 - Add email template for refunds
  queue_services/account-mailer/src/account_mailer/config.py
  queue_services/account-mailer/src/account_mailer/email_processors/__init__.py
  queue_services/account-mailer/src/account_mailer/email_processors/refund_requested.py
  queue_services/account-mailer/src/account_mailer/email_templates/REFUND_REQUEST.html
  queue_services/account-mailer/src/account_mailer/email_templates/common/business-dashboard-link.html
  queue_services/account-mailer/src/account_mailer/email_templates/common/footer.html
  queue_services/account-mailer/src/account_mailer/email_templates/common/header.html
  queue_services/account-mailer/src/account_mailer/email_templates/common/logo.html
  queue_services/account-mailer/src/account_mailer/email_templates/common/style.html
  queue_services/account-mailer/src/account_mailer/email_templates/common/whitespace-16px.html
  queue_services/account-mailer/src/account_mailer/email_templates/common/whitespace-24px.html
  queue_services/account-mailer/src/account_mailer/worker.py
  queue_services/account-mailer/tests/integration/test_worker_queue.py
  queue_services/account-mailer/tests/integration/utils.py
Labels: skip-changelog

#1120 Director Search : Login address needs to be updated#5427
  auth-web/src/components/auth/account-settings/team-management/AddUsersSuccess.vue
Labels: bug

#1121 Update for set environment variables issue of GHA.
  .github/workflows/account-mailer-cd.yml
  .github/workflows/auth-api-cd.yml
  .github/workflows/auth-web-cd.yml
  .github/workflows/events-listener-cd.yml
  .github/workflows/integration-testing-dev.yml
  .github/workflows/notify-api&queue-cd.yml
  .github/workflows/status-api-cd.yml
  scripts/1pass.sh
Labels: devops

#1122 QA Deployment
  .github/workflows/account-mailer-cd.yml
  .github/workflows/auth-api-cd.yml
  .github/workflows/auth-web-cd.yml
  .github/workflows/events-listener-cd.yml
  .github/workflows/integration-testing-dev.yml
  .github/workflows/notify-api&queue-cd.yml
  .github/workflows/status-api-cd.yml
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/components/auth/account-settings/team-management/AddUsersSuccess.vue
  auth-web/src/components/auth/common/PADInfoForm.vue
  auth-web/src/components/auth/common/PaymentMethods.vue
  auth-web/src/components/auth/common/SearchFilterInput.vue
  auth-web/src/views/auth/AccountSettings.vue
  auth-web/tests/unit/components/SearchFilterInput.spec.ts
  queue_services/account-mailer/src/account_mailer/config.py
  queue_services/account-mailer/src/account_mailer/email_processors/__init__.py
  queue_services/account-mailer/src/account_mailer/email_processors/refund_requested.py
  queue_services/account-mailer/src/account_mailer/email_templates/REFUND_REQUEST.html
  queue_services/account-mailer/src/account_mailer/email_templates/common/business-dashboard-link.html
  queue_services/account-mailer/src/account_mailer/email_templates/common/footer.html
  queue_services/account-mailer/src/account_mailer/email_templates/common/header.html
  queue_services/account-mailer/src/account_mailer/email_templates/common/logo.html
  queue_services/account-mailer/src/account_mailer/email_templates/common/style.html
  queue_services/account-mailer/src/account_mailer/email_templates/common/whitespace-16px.html
  queue_services/account-mailer/src/account_mailer/email_templates/common/whitespace-24px.html
  queue_services/account-mailer/src/account_mailer/worker.py
  queue_services/account-mailer/tests/integration/test_worker_queue.py
  queue_services/account-mailer/tests/integration/utils.py
  scripts/1pass.sh
Labels: skip-changelog

#1119 Email PAD Confirmation Letter to Account Administrator
  auth-api/src/auth_api/services/rest_service.py
  queue_services/account-mailer/requirements.txt
  queue_services/account-mailer/src/account_mailer/config.py
  queue_services/account-mailer/src/account_mailer/email_processors/pad_confirmation.py
  queue_services/account-mailer/src/account_mailer/pdf_templates/pad_confirmation.html
  queue_services/account-mailer/src/account_mailer/services/notification_service.py
  queue_services/account-mailer/src/account_mailer/worker.py
Labels: enhancement

#1127 Q fixes (#1126)
  .github/workflows/account-mailer-cd.yml
  auth-api/src/auth_api/services/rest_service.py
  queue_services/account-mailer/q_cli.py
  queue_services/account-mailer/requirements.txt
  queue_services/account-mailer/requirements/repo-libraries.txt
  queue_services/account-mailer/setup.cfg
  queue_services/account-mailer/src/account_mailer/config.py
  queue_services/account-mailer/src/account_mailer/email_processors/__init__.py
  queue_services/account-mailer/src/account_mailer/email_processors/pad_confirmation.py
  queue_services/account-mailer/src/account_mailer/email_processors/refund_requested.py
  queue_services/account-mailer/src/account_mailer/email_templates/REFUND_REQUEST.html
  queue_services/account-mailer/src/account_mailer/email_templates/common/business-dashboard-link.html
  queue_services/account-mailer/src/account_mailer/email_templates/common/footer.html
  queue_services/account-mailer/src/account_mailer/email_templates/common/initiative-notice.html
  queue_services/account-mailer/src/account_mailer/email_templates/pad_confirmation_email.html
  queue_services/account-mailer/src/account_mailer/email_templates/refund_request_email.html
  queue_services/account-mailer/src/account_mailer/pdf_templates/common/bc_logo_img.html
  queue_services/account-mailer/src/account_mailer/pdf_templates/common/bc_registry_logo_img.html
  queue_services/account-mailer/src/account_mailer/pdf_templates/common/fonts.html
  queue_services/account-mailer/src/account_mailer/pdf_templates/common/style.html
  queue_services/account-mailer/src/account_mailer/pdf_templates/pad_confirmation.html
  queue_services/account-mailer/src/account_mailer/services/notification_service.py
  queue_services/account-mailer/src/account_mailer/worker.py
Labels: enhancement

#1128 q cli cmd for refund requests
  queue_services/account-mailer/q_cli.py
Labels: skip-changelog

#1129 dev to test merge
  .github/workflows/account-mailer-cd.yml
  auth-api/src/auth_api/services/rest_service.py
  queue_services/account-mailer/q_cli.py
  queue_services/account-mailer/requirements.txt
  queue_services/account-mailer/requirements/repo-libraries.txt
  queue_services/account-mailer/setup.cfg
  queue_services/account-mailer/src/account_mailer/config.py
  queue_services/account-mailer/src/account_mailer/email_processors/__init__.py
  queue_services/account-mailer/src/account_mailer/email_processors/pad_confirmation.py
  queue_services/account-mailer/src/account_mailer/email_processors/refund_requested.py
  queue_services/account-mailer/src/account_mailer/email_templates/REFUND_REQUEST.html
  queue_services/account-mailer/src/account_mailer/email_templates/common/business-dashboard-link.html
  queue_services/account-mailer/src/account_mailer/email_templates/common/footer.html
  queue_services/account-mailer/src/account_mailer/email_templates/common/initiative-notice.html
  queue_services/account-mailer/src/account_mailer/email_templates/pad_confirmation_email.html
  queue_services/account-mailer/src/account_mailer/email_templates/refund_request_email.html
  queue_services/account-mailer/src/account_mailer/pdf_templates/common/bc_logo_img.html
  queue_services/account-mailer/src/account_mailer/pdf_templates/common/bc_registry_logo_img.html
  queue_services/account-mailer/src/account_mailer/pdf_templates/common/fonts.html
  queue_services/account-mailer/src/account_mailer/pdf_templates/common/style.html
  queue_services/account-mailer/src/account_mailer/pdf_templates/pad_confirmation.html
  queue_services/account-mailer/src/account_mailer/services/notification_service.py
  queue_services/account-mailer/src/account_mailer/worker.py
Labels: enhancement, skip-changelog

#1130 email alignment fix
  queue_services/account-mailer/src/account_mailer/email_templates/pad_confirmation_email.html
Labels: skip-changelog

#1131 email alignment fix (#1130)
  queue_services/account-mailer/src/account_mailer/email_templates/pad_confirmation_email.html
Labels: skip-changelog

#1132 Selected payment method not appearing properly#5668
  auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
  auth-web/src/store/modules/org.ts
Labels: bug

#1133 Added suspended_on and new status NSF_SUSPENDED to handled account be…
  auth-api/migrations/versions/fc8b221f938f_added_suspended_date_status.py
  auth-api/src/auth_api/models/org.py
  auth-api/src/auth_api/utils/enums.py
Labels: enhancement

#1135 dev to test merge
  auth-api/migrations/versions/fc8b221f938f_added_suspended_date_status.py
  auth-api/src/auth_api/models/org.py
  auth-api/src/auth_api/utils/enums.py
  auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
  auth-web/src/store/modules/org.ts
Labels: skip-changelog

#1136 Fixed the status
  auth-api/src/auth_api/utils/roles.py
Labels: skip-changelog

#1137 show bank institution number instead of bank name in pad confirmation pdf
  queue_services/account-mailer/src/account_mailer/pdf_templates/pad_confirmation.html
Labels: skip-changelog

#1138 QA Deployment
  auth-api/src/auth_api/utils/roles.py
  queue_services/account-mailer/src/account_mailer/pdf_templates/pad_confirmation.html
Labels: skip-changelog

#1123 Account Freeze NSF - UI
  auth-web/src/App.vue
  auth-web/src/components/auth/account-freeze/AccountOverview.vue
  auth-web/src/components/auth/account-freeze/PaymentReview.vue
  auth-web/src/components/auth/account-freeze/ReviewBankInformation.vue
  auth-web/src/components/auth/common/PADInfoForm.vue
  auth-web/src/components/auth/common/stepper/Stepper.vue
  auth-web/src/components/auth/mixins/NextPageMixin.vue
  auth-web/src/models/Organization.ts
  auth-web/src/routes/index.ts
  auth-web/src/routes/router.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/account-freeze/AccountFreezeUnlockView.vue
  auth-web/src/views/auth/account-freeze/AccountFreezeView.vue
  auth-web/tests/unit/components/AccountOverview.spec.ts
  auth-web/tests/unit/components/PaymentReview.spec.ts
  auth-web/tests/unit/components/ReviewBankInformation.spec.ts
  auth-web/tests/unit/components/UserProfileForm.spec.ts
  auth-web/tests/unit/views/AccountFreezeUnlockView.spec.ts
  auth-web/tests/unit/views/AccountFreezeView.spec.ts
Labels: enhancement

#1141 pad confirmation pdf changes
  queue_services/account-mailer/src/account_mailer/email_processors/pad_confirmation.py
  queue_services/account-mailer/src/account_mailer/email_templates/pad_confirmation_email.html
  queue_services/account-mailer/src/account_mailer/pdf_templates/common/style.html
  queue_services/account-mailer/src/account_mailer/pdf_templates/pad_confirmation.html
Labels: skip-changelog

#1140 Added org status to the permission table
  auth-api/migrations/versions/75336ba7d252_org_type_added_to_permission.py
  auth-api/src/auth_api/models/permissions.py
  auth-api/src/auth_api/resources/permissions.py
  auth-api/src/auth_api/services/permissions.py
  auth-api/tests/unit/api/test_permissions.py
  auth-web/src/services/permission.services.ts
  auth-web/src/store/modules/org.ts
Labels: enhancement

#1143 clean up pad confirmation pdf and email
  queue_services/account-mailer/src/account_mailer/email_processors/pad_confirmation.py
  queue_services/account-mailer/src/account_mailer/pdf_templates/pad_confirmation.html
Labels: skip-changelog

#1144 QA Deployment
  auth-api/migrations/versions/75336ba7d252_org_type_added_to_permission.py
  auth-api/src/auth_api/models/permissions.py
  auth-api/src/auth_api/resources/permissions.py
  auth-api/src/auth_api/services/permissions.py
  auth-api/tests/unit/api/test_permissions.py
  auth-web/src/App.vue
  auth-web/src/components/auth/account-freeze/AccountOverview.vue
  auth-web/src/components/auth/account-freeze/PaymentReview.vue
  auth-web/src/components/auth/account-freeze/ReviewBankInformation.vue
  auth-web/src/components/auth/common/PADInfoForm.vue
  auth-web/src/components/auth/common/stepper/Stepper.vue
  auth-web/src/components/auth/mixins/NextPageMixin.vue
  auth-web/src/models/Organization.ts
  auth-web/src/routes/index.ts
  auth-web/src/routes/router.ts
  auth-web/src/services/permission.services.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/account-freeze/AccountFreezeUnlockView.vue
  auth-web/src/views/auth/account-freeze/AccountFreezeView.vue
  auth-web/tests/unit/components/AccountOverview.spec.ts
  auth-web/tests/unit/components/PaymentReview.spec.ts
  auth-web/tests/unit/components/ReviewBankInformation.spec.ts
  auth-web/tests/unit/components/UserProfileForm.spec.ts
  auth-web/tests/unit/views/AccountFreezeUnlockView.spec.ts
  auth-web/tests/unit/views/AccountFreezeView.spec.ts
  queue_services/account-mailer/src/account_mailer/email_processors/pad_confirmation.py
  queue_services/account-mailer/src/account_mailer/email_templates/pad_confirmation_email.html
  queue_services/account-mailer/src/account_mailer/pdf_templates/common/style.html
  queue_services/account-mailer/src/account_mailer/pdf_templates/pad_confirmation.html
Labels: skip-changelog

#1139 #4402-API- create schemas for all response, write unit tests
  auth-api/src/auth_api/schemas/base_schema.py
  auth-api/src/auth_api/schemas/contact.py
  auth-api/src/auth_api/schemas/schemas/account_response.json
  auth-api/src/auth_api/schemas/schemas/affidavit_response.json
  auth-api/src/auth_api/schemas/schemas/affiliation_response.json
  auth-api/src/auth_api/schemas/schemas/affiliations_response.json
  auth-api/src/auth_api/schemas/schemas/bconline_response.json
  auth-api/src/auth_api/schemas/schemas/business.json
  auth-api/src/auth_api/schemas/schemas/codes.json
  auth-api/src/auth_api/schemas/schemas/contact_response.json
  auth-api/src/auth_api/schemas/schemas/contacts.json
  auth-api/src/auth_api/schemas/schemas/corp_type.json
  auth-api/src/auth_api/schemas/schemas/document.json
  auth-api/src/auth_api/schemas/schemas/error.json
  auth-api/src/auth_api/schemas/schemas/exception.json
  auth-api/src/auth_api/schemas/schemas/invitation_response.json
  auth-api/src/auth_api/schemas/schemas/invitations.json
  auth-api/src/auth_api/schemas/schemas/members.json
  auth-api/src/auth_api/schemas/schemas/membership.json
  auth-api/src/auth_api/schemas/schemas/org_product_subscriptions_response.json
  auth-api/src/auth_api/schemas/schemas/org_response.json
  auth-api/src/auth_api/schemas/schemas/orgs_response.json
  auth-api/src/auth_api/schemas/schemas/paged_response.json
  auth-api/src/auth_api/schemas/schemas/product.json
  auth-api/src/auth_api/schemas/schemas/products.json
  auth-api/src/auth_api/schemas/schemas/user_response.json
  auth-api/src/auth_api/schemas/schemas/user_settings_response.json
  auth-api/src/auth_api/schemas/schemas/users_response.json
  auth-api/tests/unit/api/test_account.py
  auth-api/tests/unit/api/test_bcol_profiles.py
  auth-api/tests/unit/api/test_codes.py
  auth-api/tests/unit/api/test_documents.py
  auth-api/tests/unit/api/test_entity.py
  auth-api/tests/unit/api/test_invitation.py
  auth-api/tests/unit/api/test_org.py
  auth-api/tests/unit/api/test_org_products.py
  auth-api/tests/unit/api/test_product.py
  auth-api/tests/unit/api/test_user.py
  auth-api/tests/unit/api/test_user_settings.py
Labels: enhancement

#1145 Incorrect wording for PAD - Linked Premium account#5719
  auth-web/src/components/auth/common/PADInfoForm.vue
  queue_services/account-mailer/src/account_mailer/email_templates/refund_request_email.html
Labels: bug

#1146 QA deployment
  auth-api/src/auth_api/schemas/base_schema.py
  auth-api/src/auth_api/schemas/contact.py
  auth-api/src/auth_api/schemas/schemas/account_response.json
  auth-api/src/auth_api/schemas/schemas/affidavit_response.json
  auth-api/src/auth_api/schemas/schemas/affiliation_response.json
  auth-api/src/auth_api/schemas/schemas/affiliations_response.json
  auth-api/src/auth_api/schemas/schemas/bconline_response.json
  auth-api/src/auth_api/schemas/schemas/business.json
  auth-api/src/auth_api/schemas/schemas/codes.json
  auth-api/src/auth_api/schemas/schemas/contact_response.json
  auth-api/src/auth_api/schemas/schemas/contacts.json
  auth-api/src/auth_api/schemas/schemas/corp_type.json
  auth-api/src/auth_api/schemas/schemas/document.json
  auth-api/src/auth_api/schemas/schemas/error.json
  auth-api/src/auth_api/schemas/schemas/exception.json
  auth-api/src/auth_api/schemas/schemas/invitation_response.json
  auth-api/src/auth_api/schemas/schemas/invitations.json
  auth-api/src/auth_api/schemas/schemas/members.json
  auth-api/src/auth_api/schemas/schemas/membership.json
  auth-api/src/auth_api/schemas/schemas/org_product_subscriptions_response.json
  auth-api/src/auth_api/schemas/schemas/org_response.json
  auth-api/src/auth_api/schemas/schemas/orgs_response.json
  auth-api/src/auth_api/schemas/schemas/paged_response.json
  auth-api/src/auth_api/schemas/schemas/product.json
  auth-api/src/auth_api/schemas/schemas/products.json
  auth-api/src/auth_api/schemas/schemas/user_response.json
  auth-api/src/auth_api/schemas/schemas/user_settings_response.json
  auth-api/src/auth_api/schemas/schemas/users_response.json
  auth-api/tests/unit/api/test_account.py
  auth-api/tests/unit/api/test_bcol_profiles.py
  auth-api/tests/unit/api/test_codes.py
  auth-api/tests/unit/api/test_documents.py
  auth-api/tests/unit/api/test_entity.py
  auth-api/tests/unit/api/test_invitation.py
  auth-api/tests/unit/api/test_org.py
  auth-api/tests/unit/api/test_org_products.py
  auth-api/tests/unit/api/test_product.py
  auth-api/tests/unit/api/test_user.py
  auth-api/tests/unit/api/test_user_settings.py
  auth-web/src/components/auth/common/PADInfoForm.vue
  queue_services/account-mailer/src/account_mailer/email_templates/refund_request_email.html
Labels: skip-changelog

#1147 #4402 update test_bulk_user.py
  auth-api/tests/unit/api/test_bulk_user.py
Labels: bug

#1148 hide payment method in account settings w.r.t. ld flags
  auth-web/src/views/auth/AccountSettings.vue
Labels: skip-changelog

#1149 QA Deployment
  auth-api/tests/unit/api/test_bulk_user.py
  auth-web/src/views/auth/AccountSettings.vue
Labels: skip-changelog

#1151 misc updates for Name Request
  auth-web/public/config/configuration.json
  auth-web/src/assets/img/Step2_NameRequest_x2.png
  auth-web/src/components/auth/home/NameRequestButton.vue
  auth-web/src/util/config-helper.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/home/RequestNameView.vue
  auth-web/tests/unit/util/config-helper.spec.ts
  auth-web/tests/unit/views/AccountFreezeUnlockView.spec.ts
  auth-web/tests/unit/views/AccountFreezeView.spec.ts
  auth-web/tests/unit/views/HomeView.spec.ts
  auth-web/tests/unit/views/RequestNameView.spec.ts
Labels: enhancement

#1150 extended permission model to authorization
  auth-api/migrations/versions/1c958b749a20_org_status_added_to_authorisation_view.py
  auth-api/migrations/versions/75336ba7d252_org_type_added_to_permission.py
  auth-api/requirements.txt
  auth-api/requirements/prod.txt
  auth-api/src/auth_api/__init__.py
  auth-api/src/auth_api/models/permissions.py
  auth-api/src/auth_api/models/views/authorization.py
  auth-api/src/auth_api/resources/permissions.py
  auth-api/src/auth_api/services/authorization.py
  auth-api/src/auth_api/services/permissions.py
  auth-api/src/auth_api/utils/cache.py
  auth-api/tests/unit/api/test_permissions.py
  auth-api/tests/unit/services/test_permissions.py
  auth-web/src/services/permission.services.ts
Labels: enhancement

#1152 navigation changes for account freeze and account switching
  auth-web/src/components/auth/mixins/NextPageMixin.vue
  auth-web/src/routes/index.ts
  auth-web/src/routes/router.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/util/common-util.ts
  auth-web/src/util/constants.ts
Labels: enhancement

#1153 #5436 #5685 validate duplicate account names
  auth-api/src/auth_api/models/org.py
  auth-api/src/auth_api/services/org.py
  auth-api/tests/unit/models/test_org.py
  auth-api/tests/unit/services/test_org.py
Labels: bug

#1154 Fixed the casing of the permissions
  auth-api/migrations/versions/1c958b749a20_org_status_added_to_authorisation_view.py
  auth-web/src/util/constants.ts
Labels: skip-changelog

#1155 Patch: Dir search user role change modal popup text fix
  auth-web/src/components/auth/account-settings/team-management/AnonymousUserManagement.vue
  auth-web/src/components/auth/mixins/TeamManagementMixin.vue
Labels: skip-changelog

#1157 Changes for Payment Views for PAD settlement
  auth-web/src/components/auth/account-freeze/PaymentReview.vue
  auth-web/src/models/Payment.ts
  auth-web/src/routes/router.ts
  auth-web/src/services/payment.services.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/account-freeze/AccountFreezeUnlockView.vue
  auth-web/src/views/pay/CcPaymentReturnView.vue
  auth-web/src/views/pay/CcPaymentView.vue
Labels: enhancement

#1162 #4831-Account Pending Approval Message refers to wrong Approving Party
  auth-web/src/routes/index.ts
Labels: bug

#1163 org refresh after payment by checking route param
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/views/auth/AccountSettings.vue
  auth-web/src/views/pay/CcPaymentReturnView.vue
  auth-web/src/views/pay/CcPaymentView.vue
Labels: skip-changelog
