Repository bcgov/sbc-auth, pull requests merged in 2020-08, with the labels that each got.

#934 [entity4048] Updating sbc-common-components package
  auth-web/package-lock.json
  auth-web/package.json
Labels: enhancement

#933 change default payment method in auth
  auth-api/config.py
  auth-api/migrations/versions/2e58cc00009b_add_direct_payment_to_payment_types.py
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/utils/enums.py
  auth-api/tests/unit/services/test_org.py
Labels: enhancement

#935 4366 learn more
  auth-web/src/assets/img/learn-more/android-code.jpg
  auth-web/src/assets/img/learn-more/bcsc-code.jpg
  auth-web/src/assets/img/learn-more/desktop-code.jpg
  auth-web/src/assets/img/learn-more/desktop-download.jpg
  auth-web/src/assets/img/learn-more/email.jpg
  auth-web/src/assets/img/learn-more/log-in.jpg
  auth-web/src/assets/img/learn-more/login-form.jpg
  auth-web/src/assets/img/learn-more/mobile-code.jpg
  auth-web/src/assets/img/learn-more/mobile-download.jpg
  auth-web/src/assets/img/learn-more/person-desk.jpg
  auth-web/src/assets/img/learn-more/qr-code.jpg
  auth-web/src/assets/img/learn-more/success.jpg
  auth-web/src/assets/img/learn-more/usb-card.jpg
  auth-web/src/assets/img/learn-more/usb-key.jpg
  auth-web/src/assets/img/learn-more/user-profile.jpg
  auth-web/src/assets/img/learn-more/verify-identity.jpg
  auth-web/src/components/auth/AccountLoginOptionPicker.vue
  auth-web/src/components/auth/LearnMoreBCEID.vue
  auth-web/src/components/auth/LearnMoreBCSC.vue
  auth-web/src/views/auth/AccountLoginOptionsChooser.vue
  auth-web/src/views/auth/AccountLoginOptionsInfo.vue
  auth-web/src/views/auth/AccountSettingsLoginOption.vue
Labels: feature

#937 Changes to support transaction update for direct pay
  auth-web/src/routes/index.ts
  auth-web/src/routes/router.ts
  auth-web/src/services/payment.services.ts
  auth-web/src/views/pay/PaymentReturnView.vue
  auth-web/tests/unit/views/PaymentReturnView.spec.ts
Labels: enhancement

#941 BC/Non-BC resident screen appears twice#4535
  auth-web/src/components/auth/mixins/NextPageMixin.vue
Labels: bug

#940 Add reset otp function.
  .github/workflows/pr-label-check.yml
  auth-api/requirements.txt
  auth-api/src/auth_api/services/keycloak.py
  auth-api/src/auth_api/services/reset.py
  auth-api/tests/unit/services/test_keycloak.py
  auth-api/tests/unit/services/test_reset.py
Labels: enhancement

#943 [entity4366] Content Updates for Learn More Interfaces
  auth-web/src/components/auth/LearnMoreBCEID.vue
  auth-web/src/components/auth/LearnMoreBCSC.vue
Labels: enhancement

#950 feature flag Learn more and disable it till its ready to go to users
  auth-web/src/components/auth/AccountLoginOptionPicker.vue
  auth-web/src/util/constants.ts
Labels: enhancement

#948 Learn More Content Updates
  auth-web/src/assets/img/learn-more/create-account.jpg
  auth-web/src/assets/img/learn-more/usb-card.jpg
  auth-web/src/components/auth/LearnMoreBCEID.vue
  auth-web/src/components/auth/LearnMoreBCSC.vue
Labels: feature

#954 Reverting payment service changes for direct pay
  auth-web/src/routes/router.ts
  auth-web/src/services/payment.services.ts
  auth-web/src/views/pay/PaymentReturnView.vue
  auth-web/tests/unit/views/PaymentReturnView.spec.ts
Labels: bug

#955 Dev to Test merge
  auth-web/src/assets/img/learn-more/create-account.jpg
  auth-web/src/assets/img/learn-more/usb-card.jpg
  auth-web/src/components/auth/LearnMoreBCEID.vue
  auth-web/src/components/auth/LearnMoreBCSC.vue
  auth-web/src/routes/router.ts
  auth-web/src/services/payment.services.ts
  auth-web/src/views/pay/PaymentReturnView.vue
  auth-web/tests/unit/views/PaymentReturnView.spec.ts
Labels: enhancement

#956 Adding direct pay changes
  auth-web/src/routes/router.ts
  auth-web/src/services/payment.services.ts
  auth-web/src/views/pay/PaymentReturnView.vue
  auth-web/tests/unit/views/PaymentReturnView.spec.ts
Labels: enhancement

#957 View, edit GL coding for direct pay#4373
  auth-web/src/components/auth/staff/GLCodeDetailsModal.vue
  auth-web/src/components/auth/staff/GLCodesDataTable.vue
  auth-web/src/locales/en.json
  auth-web/src/models/Staff.ts
  auth-web/src/routes/router.ts
  auth-web/src/services/payment.services.ts
  auth-web/src/store/modules/staff.ts
  auth-web/src/util/common-util.ts
  auth-web/src/views/auth/staff/GLCodesListView.vue
Labels: enhancement

#960 [entity4373] UI Updates to GL Code Interfaces
  auth-web/src/assets/scss/overrides.scss
  auth-web/src/components/auth/staff/GLCodeDetailsModal.vue
  auth-web/src/components/auth/staff/GLCodesDataTable.vue
  auth-web/src/views/auth/staff/GLCodesListView.vue
  auth-web/src/views/auth/staff/SearchBusinessView.vue
Labels: feature

#958 [entity4647] Adding Incorporation Number to Transactions List
  auth-web/src/components/auth/TransactionsDataTable.vue
  auth-web/src/store/modules/org.ts
Labels: feature

#961 Statements - View Account Statements#3638
  auth-web/src/components/auth/Statements.vue
  auth-web/src/locales/en.json
  auth-web/src/models/statement.ts
  auth-web/src/routes/router.ts
  auth-web/src/services/payment.services.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/views/auth/AccountSettings.vue
Labels: enhancement, feature

#969 changing back date format as per the design
  auth-web/src/components/auth/staff/GLCodeDetailsModal.vue
  auth-web/src/components/auth/staff/GLCodesDataTable.vue
Labels: skip-changelog

#963 Statements - Set Statement Frequency#3637 #3310
  auth-web/src/components/auth/Statements.vue
  auth-web/src/components/auth/StatementsSettings.vue
  auth-web/src/models/statement.ts
  auth-web/src/services/payment.services.ts
  auth-web/src/store/modules/org.ts
Labels: enhancement

#968 [entity3637] UI Updates / Improvements - Statements Interfaces
  auth-web/src/components/auth/Statements.vue
  auth-web/src/components/auth/StatementsSettings.vue
Labels: feature

#972 Download Statements #3649, Email Notifications for Statements#3310
  auth-web/src/assets/scss/base.scss
  auth-web/src/components/auth/Statements.vue
  auth-web/src/components/auth/StatementsSettings.vue
  auth-web/src/models/statement.ts
  auth-web/src/services/payment.services.ts
  auth-web/src/store/modules/org.ts
Labels: enhancement, feature

#973 fix for pdf download and get filename from backend
  auth-web/src/components/auth/Statements.vue
  auth-web/src/services/payment.services.ts
  auth-web/src/store/modules/org.ts
Labels: skip-changelog

#977 dev to test merge
  auth-web/src/assets/scss/base.scss
  auth-web/src/components/auth/Statements.vue
  auth-web/src/components/auth/StatementsSettings.vue
  auth-web/src/models/statement.ts
  auth-web/src/services/payment.services.ts
  auth-web/src/store/modules/org.ts
  docs/docs/api_contract/auth-api-1.0.0.yaml
Labels: skip-changelog

#978 Account settings ui
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/src/components/auth/StatementsSettings.vue
  auth-web/src/views/auth/AccountSettings.vue
Labels: skip-changelog

#979 Account settings ui (#978)
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/src/components/auth/StatementsSettings.vue
  auth-web/src/views/auth/AccountSettings.vue
Labels: skip-changelog

#975 Changes for adding version to tables
  auth-api/config.py
  auth-api/migrations/env.py
  auth-api/migrations/versions/5cf63f567a62_adding_version.py
  auth-api/requirements.txt
  auth-api/requirements/prod.txt
  auth-api/src/auth_api/models/account_login_options.py
  auth-api/src/auth_api/models/account_payment_settings.py
  auth-api/src/auth_api/models/affidavit.py
  auth-api/src/auth_api/models/affiliation.py
  auth-api/src/auth_api/models/base_model.py
  auth-api/src/auth_api/models/contact.py
  auth-api/src/auth_api/models/contact_link.py
  auth-api/src/auth_api/models/db.py
  auth-api/src/auth_api/models/documents.py
  auth-api/src/auth_api/models/entity.py
  auth-api/src/auth_api/models/membership.py
  auth-api/src/auth_api/models/membership_status_code.py
  auth-api/src/auth_api/models/org.py
  auth-api/src/auth_api/models/org_settings.py
  auth-api/src/auth_api/models/org_status.py
  auth-api/src/auth_api/models/product_subscription.py
  auth-api/src/auth_api/models/product_subscription_role.py
  auth-api/src/auth_api/models/user.py
  auth-api/src/auth_api/schemas/schemas/user.json
  auth-api/src/auth_api/services/entity.py
  auth-api/src/auth_api/services/membership.py
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/products.py
  auth-api/src/auth_api/services/reset.py
  auth-api/src/auth_api/services/user.py
  auth-api/tests/unit/api/test_user.py
  auth-api/tests/unit/models/test_documents.py
  auth-api/tests/utilities/factory_utils.py
  auth-web/public/config/configuration.json
Labels: enhancement

#980 [entity4366] Add BCSC URL to Auth Options
  auth-web/src/components/auth/AccountLoginOptionPicker.vue
  auth-web/src/components/auth/TransactionsDataTable.vue
  auth-web/src/views/auth/AccountSettings.vue
Labels: feature

#983 Status API : Changes to pay alert to allow custom messages for custom time frame
  auth-web/package-lock.json
  auth-web/package.json
  status-api/config.py
  status-api/requirements.txt
  status-api/src/status_api/__init__.py
  status-api/src/status_api/resources/__init__.py
  status-api/src/status_api/services/status.py
  status-api/tests/unit/services/test_status.py
Labels: enhancement
