Repository bcgov/sbc-auth, pull requests merged in 2020-10, with the labels that each got.

#1044 [entity4341] General UI Improvements / Clean-up
  auth-web/src/components/auth/AccountInfo.vue
  auth-web/src/components/auth/AnonymousUserManagement.vue
  auth-web/src/components/auth/MemberDataTable.vue
  auth-web/src/components/auth/Statements.vue
  auth-web/src/components/auth/TeamManagement.vue
  auth-web/src/components/auth/Transactions.vue
  auth-web/src/components/auth/TransactionsDataTable.vue
  auth-web/src/components/auth/UserManagement.vue
  auth-web/src/components/auth/common/DateRangeFilter.vue
  auth-web/src/components/auth/common/SearchFilterInput.vue
  auth-web/src/views/auth/AccountSettings.vue
  auth-web/tests/unit/components/DateRangeFilter.spec.ts
Labels: skip-changelog

#1045 Create Account folder reorganize
  auth-web/src/components/auth/create-account/AccountCreateBasic.vue
  auth-web/src/components/auth/create-account/AccountCreatePremium.vue
  auth-web/src/components/auth/create-account/AccountTypeSelector.vue
  auth-web/src/components/auth/create-account/CreateAccountInfoForm.vue
  auth-web/src/components/auth/create-account/non-bcsc/AccountInstructions.vue
  auth-web/src/components/auth/create-account/non-bcsc/AffidavitDownload.vue
  auth-web/src/components/auth/create-account/non-bcsc/NotaryContactForm.vue
  auth-web/src/components/auth/create-account/non-bcsc/NotaryInformationForm.vue
  auth-web/src/components/auth/create-account/non-bcsc/UploadAffidavitStep.vue
  auth-web/src/routes/router.ts
  auth-web/src/views/auth/CreateAccountView.vue
  auth-web/src/views/auth/DuplicateTeamWarningView.vue
  auth-web/src/views/auth/create-account/AccountChangeSuccessView.vue
  auth-web/src/views/auth/create-account/AccountChangeView.vue
  auth-web/src/views/auth/create-account/AccountCreationSuccessView.vue
  auth-web/src/views/auth/create-account/AccountSetupView.vue
  auth-web/src/views/auth/create-account/non-bcsc/NonBcscAccountCreationSuccessView.vue
  auth-web/src/views/auth/create-account/non-bcsc/NonBcscAccountSetupView.vue
  auth-web/src/views/auth/create-account/non-bcsc/NonBcscInfoView.vue
  auth-web/tests/unit/components/CreateAccountInfoForm.spec.ts
Labels: skip-changelog

#1034 4238 fix cancel button
  auth-web/src/components/auth/UserProfileForm.vue
Labels: bug

#1050 fix for non existing account types
  auth-api/migrations/versions/959d8ff75e82_payment_change.py
Labels: skip-changelog

#1049 Changes to transactions response
  auth-web/src/models/transaction.ts
  auth-web/src/store/modules/org.ts
Labels: skip-changelog

#1055 4874: Changes to GHA to use jwt from relationship vault
  .github/workflows/auth-api-cd.yml
  .github/workflows/notify-api&queue-cd.yml
  .github/workflows/status-api-cd.yml
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/public/config/kc/keycloak.json
Labels: skip-changelog

#1056 Updating common components version to 2.4.1
  auth-web/package-lock.json
  auth-web/package.json
Labels: skip-changelog

#1053 Changes for supporting payment_type in request
  auth-api/requirements.txt
  auth-api/src/auth_api/schemas/schemas/org.json
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/utils/enums.py
  auth-api/tests/docker/docker-compose.yml
  auth-api/tests/unit/api/test_org.py
  auth-api/tests/unit/services/test_org.py
  auth-api/tests/utilities/factory_scenarios.py
Labels: enhancement

#1059 fixing broken commit
  auth-api/migrations/versions/959d8ff75e82_payment_change.py
Labels: skip-changelog

#1054 Choose payment during basic account setup #4740 - ui
  auth-web/src/components/auth/create-account/PaymentMethodSelector.vue
  auth-web/src/views/auth/create-account/AccountSetupView.vue
  auth-web/tests/unit/components/PaymentMethodSelector.spec.ts
Labels: enhancement

#1057 mailing address enabled for basic accounts as well
  auth-api/src/auth_api/services/org.py
  auth-api/tests/unit/api/test_org.py
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/components/auth/create-account/AccountCreateBasic.vue
  auth-web/src/store/modules/org.ts
  auth-web/tests/unit/components/AccountCreateBasic.spec.ts
Labels: enhancement

#1060 Choose payment during basic account setup #4740
  auth-web/public/config/kc/keycloak.json
  auth-web/src/components/auth/common/stepper/Stepper.vue
  auth-web/src/components/auth/create-account/PaymentMethodSelector.vue
  auth-web/src/components/auth/create-account/UserProfileForm.vue
  auth-web/src/models/Organization.ts
  auth-web/src/models/user.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/store/modules/user.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/create-account/AccountSetupView.vue
  auth-web/src/views/auth/create-account/non-bcsc/NonBcscAccountSetupView.vue
  auth-web/tests/unit/components/Stepper.spec.ts
Labels: skip-changelog

#1061 Dev to test
  .github/workflows/auth-api-cd.yml
  .github/workflows/notify-api&queue-cd.yml
  .github/workflows/status-api-cd.yml
  auth-api/migrations/versions/959d8ff75e82_payment_change.py
  auth-api/requirements.txt
  auth-api/src/auth_api/schemas/schemas/org.json
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/utils/enums.py
  auth-api/tests/docker/docker-compose.yml
  auth-api/tests/unit/api/test_org.py
  auth-api/tests/unit/services/test_org.py
  auth-api/tests/utilities/factory_scenarios.py
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/public/config/kc/keycloak.json
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/components/auth/common/stepper/Stepper.vue
  auth-web/src/components/auth/create-account/AccountCreateBasic.vue
  auth-web/src/components/auth/create-account/PaymentMethodSelector.vue
  auth-web/src/components/auth/create-account/UserProfileForm.vue
  auth-web/src/models/Organization.ts
  auth-web/src/models/transaction.ts
  auth-web/src/models/user.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/store/modules/user.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/create-account/AccountSetupView.vue
  auth-web/src/views/auth/create-account/non-bcsc/NonBcscAccountSetupView.vue
  auth-web/tests/unit/components/AccountCreateBasic.spec.ts
  auth-web/tests/unit/components/PaymentMethodSelector.spec.ts
  auth-web/tests/unit/components/Stepper.spec.ts
  codecov.yaml
Labels: skip-changelog

#1064 [entity4740] Front-end Fixes
  auth-web/src/components/auth/common/stepper/Stepper.vue
  auth-web/src/components/auth/create-account/AccountCreateBasic.vue
  auth-web/src/components/auth/create-account/PaymentMethodSelector.vue
Labels: skip-changelog

#1062 Feature flag payment method step in account creation
  auth-web/src/components/auth/create-account/UserProfileForm.vue
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/create-account/AccountSetupView.vue
  auth-web/src/views/auth/create-account/non-bcsc/NonBcscAccountSetupView.vue
Labels: skip-changelog

#1065 Feature flags done for https://github.com/bcgov/entity/issues/5144
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/components/auth/create-account/AccountCreateBasic.vue
  auth-web/tests/unit/components/AccountCreateBasic.spec.ts
Labels: skip-changelog

#1069 Updated HomeView Banner Msg
  auth-web/src/views/auth/home/HomeView.vue
Labels: enhancement

#1067 Update & to "and" in BC Registries and Online Services#5219
  auth-api/src/auth_api/services/invitation.py
  auth-api/src/auth_api/services/membership.py
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/user.py
  auth-web/src/locales/en.json
Labels: enhancement

#1070 [entity4740] Payment Selector and Stepper Updates
  auth-web/src/components/auth/common/stepper/Stepper.vue
  auth-web/src/components/auth/create-account/PaymentMethodSelector.vue
  auth-web/src/views/auth/create-account/AccountSetupView.vue
Labels: skip-changelog

#1043 4772 add view for PAD tos + dialog
  auth-web/src/components/auth/PAD/PADAgreementDialog.vue
  auth-web/src/components/auth/PAD/PADTermsOfUse.vue
Labels: enhancement

#1063 5052 premium selector radio button
  auth-web/src/components/auth/create-account/AccountCreateBasic.vue
  auth-web/src/components/auth/create-account/AccountCreatePremium.vue
  auth-web/src/components/auth/create-account/PremiumChooser.vue
  auth-web/src/views/auth/create-account/AccountChangeView.vue
  auth-web/src/views/auth/create-account/AccountSetupView.vue
Labels: enhancement

#1072 Choose payment method during premium account setup #4741 - PAD UI only
  auth-web/src/components/auth/common/PADInfoForm.vue
  auth-web/src/components/auth/common/PaymentMethods.vue
  auth-web/src/components/auth/common/TermsOfUseDialog.vue
  auth-web/src/components/auth/create-account/PaymentMethodSelector.vue
  auth-web/src/util/constants.ts
  auth-web/tests/unit/components/UserProfileForm.spec.ts
Labels: enhancement

#1077 feature flagged premium account chooser
  auth-web/src/views/auth/create-account/AccountChangeView.vue
  auth-web/src/views/auth/create-account/AccountSetupView.vue
  auth-web/src/views/auth/create-account/non-bcsc/NonBcscAccountSetupView.vue
Labels: skip-changelog

#1076 Choose payment method during premium account setup - BCOL UI
  auth-web/src/components/auth/common/LinkedBCOLBanner.vue
  auth-web/src/components/auth/common/PADInfoForm.vue
  auth-web/src/components/auth/common/PaymentMethods.vue
  auth-web/src/components/auth/create-account/AccountCreatePremium.vue
  auth-web/src/components/auth/create-account/PaymentMethodSelector.vue
  auth-web/src/util/config-helper.ts
  auth-web/tests/unit/components/PaymentMethodSelector.spec.ts
  auth-web/tests/unit/components/PaymentMethods.spec.ts
Labels: enhancement

#1082 Adding random string to keycloak json URL to force load the json
  auth-web/src/main.ts
Labels: bug

#1071 fixing issues with config location breaking tests
  auth-api/migrations/versions/959d8ff75e82_payment_change.py
  auth-api/pre_hook_create_database.py
  auth-api/src/auth_api/__init__.py
  auth-api/src/auth_api/config.py
  auth-api/src/auth_api/models/invitation.py
  auth-api/src/auth_api/services/documents.py
  auth-api/src/auth_api/services/invitation.py
  auth-api/src/auth_api/services/membership.py
  auth-api/tests/unit/api/test_bulk_user.py
  auth-api/tests/unit/conf/test_configuration.py
  auth-api/tests/unit/models/test_invitation.py
  auth-api/tests/utilities/factory_scenarios.py
Labels: enhancement

#1073 Events listener added
  queue_services/events-listener/.envrc
  queue_services/events-listener/Dockerfile
  queue_services/events-listener/LICENSE
  queue_services/events-listener/MANIFEST.in
  queue_services/events-listener/Makefile
  queue_services/events-listener/README.md
  queue_services/events-listener/app.py
  queue_services/events-listener/jenkins/dev.groovy
  queue_services/events-listener/jenkins/prod.groovy
  queue_services/events-listener/jenkins/test.groovy
  queue_services/events-listener/logging.conf
  queue_services/events-listener/openshift/templates/events-listener-build.json
  queue_services/events-listener/openshift/templates/events-listener-deploy.json
  queue_services/events-listener/openshift/templates/events-listener-pipeline.json
  queue_services/events-listener/q_cli.py
  queue_services/events-listener/requirements.txt
  queue_services/events-listener/requirements/dev.txt
  queue_services/events-listener/requirements/prod.txt
  queue_services/events-listener/requirements/repo-libraries.txt
  queue_services/events-listener/scripts/verify_license_headers.sh
  queue_services/events-listener/setup.cfg
  queue_services/events-listener/setup.py
  queue_services/events-listener/src/events_listener/__init__.py
  queue_services/events-listener/src/events_listener/config.py
  queue_services/events-listener/src/events_listener/utils.py
  queue_services/events-listener/src/events_listener/version.py
  queue_services/events-listener/src/events_listener/worker.py
  queue_services/events-listener/tests/__init__.py
  queue_services/events-listener/tests/conftest.py
  queue_services/events-listener/tests/docker-compose.yml
  queue_services/events-listener/tests/integration/__init__.py
  queue_services/events-listener/tests/integration/test_worker_queue.py
  queue_services/events-listener/tests/integration/utils.py
Labels: enhancement

#1075 GHA for queue listeners added
  .github/workflows/account-mailer-cd.yml
  .github/workflows/account-mailer-ci.yml
  .github/workflows/events-listener-cd.yml
  .github/workflows/events-listener-ci.yml
  codecov.yaml
Labels: devops

#1074 Mailer queue implemented
  queue_services/account-mailer/.envrc
  queue_services/account-mailer/Dockerfile
  queue_services/account-mailer/LICENSE
  queue_services/account-mailer/MANIFEST.in
  queue_services/account-mailer/Makefile
  queue_services/account-mailer/README.md
  queue_services/account-mailer/app.py
  queue_services/account-mailer/jenkins/dev.groovy
  queue_services/account-mailer/jenkins/prod.groovy
  queue_services/account-mailer/jenkins/test.groovy
  queue_services/account-mailer/logging.conf
  queue_services/account-mailer/openshift/templates/account-mailer-build.json
  queue_services/account-mailer/openshift/templates/account-mailer-deploy.json
  queue_services/account-mailer/openshift/templates/account-mailer-pipeline.json
  queue_services/account-mailer/q_cli.py
  queue_services/account-mailer/requirements.txt
  queue_services/account-mailer/requirements/dev.txt
  queue_services/account-mailer/requirements/prod.txt
  queue_services/account-mailer/requirements/repo-libraries.txt
  queue_services/account-mailer/scripts/verify_license_headers.sh
  queue_services/account-mailer/setup.cfg
  queue_services/account-mailer/setup.py
  queue_services/account-mailer/src/account_mailer/__init__.py
  queue_services/account-mailer/src/account_mailer/config.py
  queue_services/account-mailer/src/account_mailer/email_processors/__init__.py
  queue_services/account-mailer/src/account_mailer/email_processors/payment_completed.py
  queue_services/account-mailer/src/account_mailer/utils.py
  queue_services/account-mailer/src/account_mailer/version.py
  queue_services/account-mailer/src/account_mailer/worker.py
  queue_services/account-mailer/tests/__init__.py
  queue_services/account-mailer/tests/conftest.py
  queue_services/account-mailer/tests/docker-compose.yml
  queue_services/account-mailer/tests/integration/__init__.py
  queue_services/account-mailer/tests/integration/test_worker_queue.py
  queue_services/account-mailer/tests/integration/utils.py
Labels: enhancement

#1079 Link premium to BC Online Account#5052
  auth-web/src/components/auth/common/PaymentMethods.vue
  auth-web/src/components/auth/create-account/AccountCreateBasic.vue
  auth-web/src/components/auth/create-account/AccountTypeSelector.vue
  auth-web/src/components/auth/create-account/PaymentMethodSelector.vue
  auth-web/src/components/auth/create-account/PremiumChooser.vue
  auth-web/src/store/modules/org.ts
  auth-web/tests/unit/components/PaymentMethodSelector.spec.ts
Labels: skip-changelog

#1084 fixing wrong enum in org schema
  auth-api/src/auth_api/schemas/schemas/org.json
Labels: skip-changelog

#1086 Link premium to BC Online Account#5052 - Learn More Popup and content
  auth-web/src/components/auth/create-account/PremiumChooser.vue
Labels: enhancement

#1083 PAD Agreement#4772
  auth-web/src/components/auth/PAD/PADAgreementDialog.vue
  auth-web/src/components/auth/PAD/PADTermsOfUse.vue
  auth-web/src/components/auth/common/PADInfoForm.vue
  auth-web/src/components/auth/common/TermsOfUse.vue
  auth-web/src/components/auth/common/TermsOfUseDialog.vue
  auth-web/src/models/TermsOfUseDocument.ts
  auth-web/src/services/document.services.ts
  auth-web/src/store/modules/user.ts
  auth-web/src/util/common-util.ts
  auth-web/src/views/auth/TermsOfServiceView.vue
Labels: enhancement

#1088 Migration to prd script added
  auth-api/migrations/versions/18a4955730f9_migrating_for_prod.py
  auth-web/src/main.ts
Labels: skip-changelog

#1089 Adding PAD details and mailing address to pay API
  auth-api/requirements.txt
  auth-api/src/auth_api/exceptions/errors.py
  auth-api/src/auth_api/schemas/schemas/org.json
  auth-api/src/auth_api/schemas/schemas/payment_info.json
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/utils/enums.py
  auth-api/tests/unit/api/test_org.py
  auth-api/tests/unit/services/test_org.py
  auth-api/tests/utilities/factory_scenarios.py
Labels: Do Not Merge, enhancement

#1093 Update payment method for basic org
  auth-api/src/auth_api/resources/org.py
  auth-api/src/auth_api/schemas/schemas/org.json
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/rest_service.py
  auth-api/tests/unit/api/test_org.py
  auth-api/tests/unit/services/test_org.py
  auth-api/tests/utilities/factory_scenarios.py
  auth-api/tests/utilities/factory_utils.py
Labels: enhancement

#1094 Account creation api changes - UI integration
  auth-web/src/components/auth/common/LinkedBCOLBanner.vue
  auth-web/src/components/auth/common/PADInfoForm.vue
  auth-web/src/components/auth/common/PaymentMethods.vue
  auth-web/src/components/auth/common/TermsOfUseDialog.vue
  auth-web/src/components/auth/create-account/AccountCreateBasic.vue
  auth-web/src/components/auth/create-account/AccountCreatePremium.vue
  auth-web/src/components/auth/create-account/BcolLogin.vue
  auth-web/src/components/auth/create-account/PremiumChooser.vue
  auth-web/src/components/auth/create-account/UserProfileForm.vue
  auth-web/src/models/Organization.ts
  auth-web/src/store/modules/org.ts
Labels: skip-changelog

#1085 #5289 Reuse name of dissolved account.
  auth-api/requirements.txt
  auth-api/src/auth_api/models/org.py
  auth-api/src/auth_api/resources/org.py
  auth-api/src/auth_api/services/org.py
  auth-api/tests/unit/models/test_org.py
  auth-api/tests/unit/services/test_org.py
  auth-web/src/services/org.services.ts
Labels: bug

#1095 Update payment method for a basic account#5053
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
  auth-web/src/components/auth/common/PaymentMethods.vue
  auth-web/src/components/auth/create-account/PaymentMethodSelector.vue
  auth-web/src/models/Organization.ts
  auth-web/src/models/bcol.ts
  auth-web/src/routes/router.ts
  auth-web/src/services/org.services.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/views/auth/AccountSettings.vue
  auth-web/src/views/auth/create-account/AccountSetupView.vue
  auth-web/src/views/auth/create-account/non-bcsc/NonBcscAccountSetupView.vue
Labels: enhancement

#1096 QA Deployment
  README.md
  auth-api/requirements.txt
  auth-api/src/auth_api/exceptions/errors.py
  auth-api/src/auth_api/models/org.py
  auth-api/src/auth_api/resources/org.py
  auth-api/src/auth_api/schemas/schemas/org.json
  auth-api/src/auth_api/schemas/schemas/payment_info.json
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/rest_service.py
  auth-api/src/auth_api/utils/enums.py
  auth-api/tests/unit/api/test_org.py
  auth-api/tests/unit/models/test_org.py
  auth-api/tests/unit/services/test_org.py
  auth-api/tests/utilities/factory_scenarios.py
  auth-api/tests/utilities/factory_utils.py
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
  auth-web/src/components/auth/common/LinkedBCOLBanner.vue
  auth-web/src/components/auth/common/PADInfoForm.vue
  auth-web/src/components/auth/common/PaymentMethods.vue
  auth-web/src/components/auth/common/TermsOfUseDialog.vue
  auth-web/src/components/auth/create-account/AccountCreateBasic.vue
  auth-web/src/components/auth/create-account/AccountCreatePremium.vue
  auth-web/src/components/auth/create-account/BcolLogin.vue
  auth-web/src/components/auth/create-account/PaymentMethodSelector.vue
  auth-web/src/components/auth/create-account/PremiumChooser.vue
  auth-web/src/components/auth/create-account/UserProfileForm.vue
  auth-web/src/models/Organization.ts
  auth-web/src/models/bcol.ts
  auth-web/src/routes/router.ts
  auth-web/src/services/org.services.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/views/auth/AccountSettings.vue
  auth-web/src/views/auth/create-account/AccountSetupView.vue
  auth-web/src/views/auth/create-account/non-bcsc/NonBcscAccountSetupView.vue
Labels: skip-changelog

#1097 [entity5052] UI Clean-up
  auth-web/src/assets/scss/overrides.scss
  auth-web/src/components/auth/common/LinkedBCOLBanner.vue
  auth-web/src/components/auth/common/PADInfoForm.vue
  auth-web/src/components/auth/common/PaymentMethods.vue
  auth-web/src/components/auth/common/TermsOfUseDialog.vue
  auth-web/src/components/auth/common/stepper/Stepper.vue
  auth-web/src/components/auth/create-account/AccountCreateBasic.vue
  auth-web/src/components/auth/create-account/AccountCreatePremium.vue
  auth-web/src/components/auth/create-account/BcolLogin.vue
  auth-web/src/components/auth/create-account/PaymentMethodSelector.vue
  auth-web/src/components/auth/create-account/PremiumChooser.vue
  auth-web/src/components/auth/create-account/UserProfileForm.vue
  auth-web/src/views/auth/create-account/AccountSetupView.vue
Labels: skip-changelog

#1100 QA Deployment
  auth-web/src/assets/scss/overrides.scss
  auth-web/src/components/auth/common/LinkedBCOLBanner.vue
  auth-web/src/components/auth/common/PADInfoForm.vue
  auth-web/src/components/auth/common/PaymentMethods.vue
  auth-web/src/components/auth/common/TermsOfUseDialog.vue
  auth-web/src/components/auth/common/stepper/Stepper.vue
  auth-web/src/components/auth/create-account/AccountCreateBasic.vue
  auth-web/src/components/auth/create-account/AccountCreatePremium.vue
  auth-web/src/components/auth/create-account/BcolLogin.vue
  auth-web/src/components/auth/create-account/PaymentMethodSelector.vue
  auth-web/src/components/auth/create-account/PremiumChooser.vue
  auth-web/src/components/auth/create-account/UserProfileForm.vue
  auth-web/src/views/auth/create-account/AccountSetupView.vue
  notify-api/requirements.txt
Labels: skip-changelog

#1099 PAD bank account validation for premium accounts#4773
  auth-web/src/components/auth/common/ModalDialog.vue
  auth-web/src/components/auth/common/PADInfoForm.vue
  auth-web/src/components/auth/common/stepper/Stepper.vue
  auth-web/src/models/Organization.ts
  auth-web/src/services/payment.services.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/views/auth/create-account/AccountSetupView.vue
  auth-web/src/views/auth/create-account/non-bcsc/NonBcscAccountSetupView.vue
Labels: enhancement

#1101 QA Deployment
  auth-web/src/components/auth/common/ModalDialog.vue
  auth-web/src/components/auth/common/PADInfoForm.vue
  auth-web/src/components/auth/common/stepper/Stepper.vue
  auth-web/src/models/Organization.ts
  auth-web/src/services/payment.services.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/views/auth/create-account/AccountSetupView.vue
  auth-web/src/views/auth/create-account/non-bcsc/NonBcscAccountSetupView.vue
Labels: skip-changelog

#1102 refactoring axios creation and added sentry
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/public/config/configuration.json
  auth-web/src/main.ts
  auth-web/src/services/bcol.services.ts
  auth-web/src/services/business.services.ts
  auth-web/src/services/document.services.ts
  auth-web/src/services/invitation.services.ts
  auth-web/src/services/org.services.ts
  auth-web/src/services/payment.services.ts
  auth-web/src/services/permission.services.ts
  auth-web/src/services/staff.services.ts
  auth-web/src/services/user.services.ts
  auth-web/src/util/http-util.ts
Labels: enhancement

#1103 updated sbc-common-components
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/public/css/addresscomplete-2.30.min.css
  auth-web/public/index.html
  auth-web/public/js/addresscomplete-2.30.min.js
Labels: skip-changelog

#1104 dev to test merge
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/public/config/configuration.json
  auth-web/public/css/addresscomplete-2.30.min.css
  auth-web/public/index.html
  auth-web/public/js/addresscomplete-2.30.min.js
  auth-web/src/main.ts
  auth-web/src/services/bcol.services.ts
  auth-web/src/services/business.services.ts
  auth-web/src/services/document.services.ts
  auth-web/src/services/invitation.services.ts
  auth-web/src/services/org.services.ts
  auth-web/src/services/payment.services.ts
  auth-web/src/services/permission.services.ts
  auth-web/src/services/staff.services.ts
  auth-web/src/services/user.services.ts
  auth-web/src/util/http-util.ts
Labels: skip-changelog

#1105 Account creation bug fixes
  auth-web/src/components/auth/create-account/AccountTypeSelector.vue
  auth-web/src/components/auth/create-account/UserProfileForm.vue
Labels: skip-changelog

#1106 QA Deployment
  auth-web/src/components/auth/create-account/AccountTypeSelector.vue
  auth-web/src/components/auth/create-account/UserProfileForm.vue
Labels: skip-changelog
