Repository bcgov/sbc-auth, pull requests merged in 2020-12, with the labels that each got.

#1165 account settings url fixed
  auth-web/src/views/auth/account-freeze/AccountFreezeUnlockView.vue
Labels: skip-changelog

#1166 fixed the DB connection
  .github/workflows/events-listener-cd.yml
Labels: skip-changelog

#1167 PAD validation in Account Unlock Stepper
  auth-web/src/components/auth/account-freeze/ReviewBankInformation.vue
Labels: skip-changelog

#1169 Account unlock success page UI
  auth-web/src/components/auth/account-settings/transaction/TransactionsDataTable.vue
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/account-freeze/AccountFreezeUnlockView.vue
  auth-web/src/views/auth/account-freeze/AccountUnlockSuccessView.vue
Labels: enhancement

#1160 Account events changes
  queue_services/events-listener/openshift/templates/events-listener-deploy.json
  queue_services/events-listener/q_cli.py
  queue_services/events-listener/requirements.txt
  queue_services/events-listener/requirements/repo-libraries.txt
  queue_services/events-listener/src/events_listener/config.py
  queue_services/events-listener/src/events_listener/worker.py
Labels: skip-changelog

#1171 patch fix for demo
  auth-web/src/components/auth/account-freeze/ReviewBankInformation.vue
Labels: skip-changelog

#1172 pad verification fix in unlock stepper
  auth-web/src/components/auth/account-freeze/ReviewBankInformation.vue
  auth-web/src/components/auth/common/PADInfoForm.vue
Labels: skip-changelog

#1170 Fix for flush not saving details for account events
  queue_services/events-listener/coverage.xml
  queue_services/events-listener/q_cli.py
  queue_services/events-listener/src/events_listener/worker.py
  queue_services/events-listener/tests/integration/test_worker_queue.py
  queue_services/events-listener/tests/integration/utils.py
Labels: skip-changelog

#1174 test deployment
  .github/workflows/events-listener-cd.yml
  auth-api/migrations/versions/1c958b749a20_org_status_added_to_authorisation_view.py
  auth-api/migrations/versions/75336ba7d252_org_type_added_to_permission.py
  auth-api/requirements.txt
  auth-api/requirements/prod.txt
  auth-api/src/auth_api/__init__.py
  auth-api/src/auth_api/models/org.py
  auth-api/src/auth_api/models/permissions.py
  auth-api/src/auth_api/models/views/authorization.py
  auth-api/src/auth_api/resources/permissions.py
  auth-api/src/auth_api/services/authorization.py
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/permissions.py
  auth-api/src/auth_api/utils/cache.py
  auth-api/tests/unit/api/test_permissions.py
  auth-api/tests/unit/models/test_org.py
  auth-api/tests/unit/services/test_org.py
  auth-api/tests/unit/services/test_permissions.py
  auth-web/public/config/configuration.json
  auth-web/src/assets/img/Step2_NameRequest_x2.png
  auth-web/src/components/auth/account-freeze/AccountOverview.vue
  auth-web/src/components/auth/account-freeze/PaymentReview.vue
  auth-web/src/components/auth/account-freeze/ReviewBankInformation.vue
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
  auth-web/src/components/auth/account-settings/transaction/TransactionsDataTable.vue
  auth-web/src/components/auth/common/PADInfoForm.vue
  auth-web/src/components/auth/home/NameRequestButton.vue
  auth-web/src/components/auth/mixins/NextPageMixin.vue
  auth-web/src/models/Organization.ts
  auth-web/src/models/Payment.ts
  auth-web/src/models/invoice.ts
  auth-web/src/routes/index.ts
  auth-web/src/routes/router.ts
  auth-web/src/services/payment.services.ts
  auth-web/src/services/permission.services.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/util/common-util.ts
  auth-web/src/util/config-helper.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/AccountSettings.vue
  auth-web/src/views/auth/account-freeze/AccountFreezeUnlockView.vue
  auth-web/src/views/auth/account-freeze/AccountUnlockSuccessView.vue
  auth-web/src/views/auth/home/RequestNameView.vue
  auth-web/src/views/pay/CcPaymentReturnView.vue
  auth-web/src/views/pay/CcPaymentView.vue
  auth-web/tests/unit/util/config-helper.spec.ts
  auth-web/tests/unit/views/AccountFreezeUnlockView.spec.ts
  auth-web/tests/unit/views/AccountFreezeView.spec.ts
  auth-web/tests/unit/views/HomeView.spec.ts
  auth-web/tests/unit/views/RequestNameView.spec.ts
  queue_services/events-listener/coverage.xml
  queue_services/events-listener/openshift/templates/events-listener-deploy.json
  queue_services/events-listener/q_cli.py
  queue_services/events-listener/requirements.txt
  queue_services/events-listener/requirements/repo-libraries.txt
  queue_services/events-listener/src/events_listener/config.py
  queue_services/events-listener/src/events_listener/worker.py
  queue_services/events-listener/tests/integration/test_worker_queue.py
  queue_services/events-listener/tests/integration/utils.py
Labels: devops

#1175 Fixed the pip issues
  auth-api/requirements.txt
  auth-api/requirements/repo-libraries.txt
Labels: bug

#1178 Clean up make file. Replace latest to specific version of the image tag.
  .github/workflows/auth-api-cd.yml
  .github/workflows/auth-api-ci.yml
  .github/workflows/auth-web-ci.yml
  auth-api/Makefile
  auth-api/setup.cfg
  auth-web/.gitignore
  auth-web/Dockerfile
  auth-web/Makefile
Labels: devops

#1179 Fix for ui breaking due to navigation from account info page
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/components/auth/account-settings/account-info/OrgAdminContact.vue
Labels: skip-changelog

#1177 Blocking other routes for Admin as well
  auth-web/src/components/auth/mixins/NextPageMixin.vue
  auth-web/src/routes/index.ts
  auth-web/src/routes/router.ts
Labels: skip-changelog

#1173 PAD Terms of service
  auth-api/migrations/versions/316ae45f54bc_pad_tos.py
  auth-web/src/components/auth/common/PADInfoForm.vue
  auth-web/src/components/auth/common/TermsOfUse.vue
  auth-web/src/components/auth/common/TermsOfUseDialog.vue
Labels: enhancement

#1180 QA Deployment
  .github/workflows/auth-api-ci.yml
  .github/workflows/auth-web-ci.yml
  auth-api/Makefile
  auth-api/migrations/versions/316ae45f54bc_pad_tos.py
  auth-api/setup.cfg
  auth-web/.gitignore
  auth-web/Dockerfile
  auth-web/Makefile
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/components/auth/account-settings/account-info/OrgAdminContact.vue
  auth-web/src/components/auth/common/PADInfoForm.vue
  auth-web/src/components/auth/common/TermsOfUse.vue
  auth-web/src/components/auth/common/TermsOfUseDialog.vue
  auth-web/src/components/auth/mixins/NextPageMixin.vue
  auth-web/src/routes/index.ts
  auth-web/src/routes/router.ts
Labels: skip-changelog

#1181 Online banking changes
  auth-web/public/config/configuration.json
  auth-web/src/components/pay/PaymentCard.vue
  auth-web/src/services/payment.services.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/util/config-helper.ts
  auth-web/src/views/pay/PaymentView.vue
Labels: enhancement

#1184 PAD TOS changes
  auth-api/src/auth_api/resources/documents.py
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/utils/enums.py
Labels: skip-changelog

#1186 Updating PR template as CI does the checklist tasks.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: skip-changelog

#1183 Makefile and CI flow clean up.
  .github/workflows/account-mailer-cd.yml
  .github/workflows/account-mailer-ci.yml
  .github/workflows/auth-api-cd.yml
  .github/workflows/auth-api-ci.yml
  .github/workflows/auth-web-cd.yml
  .github/workflows/auth-web-ci.yml
  .github/workflows/draft-release.yml
  .github/workflows/events-listener-cd.yml
  .github/workflows/events-listener-ci.yml
  .github/workflows/main-pr-check.yml
  .github/workflows/notify-api&queue-cd.yml
  .github/workflows/notify-api-ci.yml
  .github/workflows/notify-queue-ci.yml
  .github/workflows/pr-label-check.yml
  .github/workflows/restart_mailhog.yml
  .github/workflows/status-api-cd.yml
  .github/workflows/status-api-ci.yml
  auth-api/Makefile
  auth-web/Makefile
  notify-api/Makefile
  notify-api/requirements.txt
  notify-api/setup.cfg
  notify-api/src/notify_api/db/models/notification.py
  notify-api/tests/conftest.py
  queue_services/account-mailer/Makefile
  queue_services/account-mailer/requirements.txt
  queue_services/account-mailer/requirements/prod.txt
  queue_services/account-mailer/requirements/repo-libraries.txt
  queue_services/account-mailer/setup.cfg
  queue_services/events-listener/Makefile
  queue_services/events-listener/requirements.txt
  queue_services/events-listener/requirements/prod.txt
  queue_services/events-listener/requirements/repo-libraries.txt
  queue_services/notify-queue/Makefile
  queue_services/notify-queue/requirements.txt
  queue_services/notify-queue/tests/conftest.py
  status-api/Makefile
  status-api/requirements.txt
  status-api/requirements/repo-libraries.txt
  status-api/setup.cfg
Labels: devops

#1187 Add check strictness of build in CI flow.
  .github/workflows/account-mailer-ci.yml
  .github/workflows/auth-api-ci.yml
  .github/workflows/auth-web-ci.yml
  .github/workflows/events-listener-ci.yml
  .github/workflows/notify-api-ci.yml
  .github/workflows/notify-queue-ci.yml
  .github/workflows/status-api-ci.yml
  auth-api/Makefile
  notify-api/Makefile
  queue_services/account-mailer/Makefile
  queue_services/account-mailer/requirements.txt
  queue_services/events-listener/Makefile
  queue_services/notify-queue/Makefile
  status-api/Makefile
Labels: devops

#1185 [entity5775] NSF Interface UI Clean-up
  auth-web/src/assets/scss/overrides.scss
  auth-web/src/components/auth/account-freeze/AccountOverview.vue
  auth-web/src/components/auth/account-freeze/PaymentReview.vue
  auth-web/src/components/auth/account-freeze/ReviewBankInformation.vue
  auth-web/src/components/auth/common/stepper/Stepper.vue
  auth-web/src/views/auth/account-freeze/AccountFreezeUnlockView.vue
  auth-web/src/views/auth/account-freeze/AccountFreezeView.vue
  auth-web/tests/unit/views/AccountFreezeUnlockView.spec.ts
  auth-web/tests/unit/views/AccountFreezeView.spec.ts
Labels: skip-changelog

#1190 Fixed casing
  auth-api/src/auth_api/services/org.py
Labels: skip-changelog

#1192 [entity4772] Content Update for PAD Terms and Conditions
  auth-api/migrations/versions/316ae45f54bc_pad_tos.py
Labels: skip-changelog

#1191 Sending auth user name to pay
  auth-api/src/auth_api/models/base_model.py
  auth-api/src/auth_api/services/org.py
Labels: bug

#1197 Payment Method - Can't Save Payment Method When Accidentally Clicking…
  auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
Labels: bug

#1188 Email notify account admins and coordinators of freeze#4855
  queue_services/account-mailer/q_cli.py
  queue_services/account-mailer/src/account_mailer/config.py
  queue_services/account-mailer/src/account_mailer/email_processors/account_restored.py
  queue_services/account-mailer/src/account_mailer/email_processors/account_suspended.py
  queue_services/account-mailer/src/account_mailer/email_templates/account_restored_email.html
  queue_services/account-mailer/src/account_mailer/email_templates/account_suspended_email.html
  queue_services/account-mailer/src/account_mailer/worker.py
Labels: enhancement

#1199 changes for adding org authorisaton end point
  auth-api/migrations/versions/e38ad1ce6d21_added_bank_permissions.py
  auth-api/requirements.txt
  auth-api/src/auth_api/models/views/authorization.py
  auth-api/src/auth_api/resources/__init__.py
  auth-api/src/auth_api/resources/org_authorizations.py
  auth-api/src/auth_api/services/authorization.py
  auth-web/src/services/org.services.ts
  docs/docs/api_contract/auth-api-1.0.0.yaml
Labels: enhancement

#1200 NSF - PAD Information not pulled
  auth-web/src/store/modules/org.ts
Labels: bug

#1201 Fixed the bank info not showing for NSF accounts
  auth-api/migrations/versions/e38ad1ce6d21_added_bank_permissions.py
Labels: skip-changelog

#1211 5779 linux
  queue_services/account-mailer/q_cli.py
  queue_services/account-mailer/src/account_mailer/email_processors/pad_confirmation.py
Labels: bug

#1212 quick fix for the broken payment update method
  auth-api/src/auth_api/resources/org.py
  auth-api/src/auth_api/services/org.py
  auth-api/tests/unit/services/test_org.py
Labels: bug

#1210 Update payment method for a premium account linked to BCOL: From BCO…
  auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
  auth-web/src/components/auth/common/PaymentMethods.vue
  auth-web/tests/unit/components/AccountPaymentMethods.spec.ts
Labels: enhancement

#1216 validation error on masked bank account
  auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
  auth-web/src/components/auth/common/PADInfoForm.vue
  auth-web/src/util/common-util.ts
Labels: bug

#1219 Feature/5095
  auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
  auth-web/src/components/auth/common/PaymentMethods.vue
  auth-web/src/store/modules/org.ts
Labels: enhancement

#1221 Update payment method for premium account linked to BCOL: From PAD to…
  auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
  auth-web/src/components/auth/common/PADInfoForm.vue
  auth-web/src/components/auth/common/PaymentMethods.vue
  auth-web/src/models/Organization.ts
Labels: enhancement

#1222 Patch fix
  auth-api/src/auth_api/models/views/authorization.py
  auth-api/src/auth_api/services/authorization.py
Labels: bug, enhancement

#1218 5640-Attach Copy of PAD Terms & Conditions Confirmation Letter.
  .github/workflows/account-mailer-cd.yml
  .github/workflows/account-mailer-ci.yml
  queue_services/account-mailer/app.py
  queue_services/account-mailer/q_cli.py
  queue_services/account-mailer/src/account_mailer/config.py
  queue_services/account-mailer/src/account_mailer/email_processors/pad_confirmation.py
  queue_services/account-mailer/src/account_mailer/services/minio_service.py
  queue_services/account-mailer/tests/conftest.py
  queue_services/account-mailer/tests/docker/docker-compose.yml
Labels: enhancement

#1214 Changes to support names
  auth-api/migrations/versions/aaa29018c0a1_added_namex_product.py
  auth-api/src/auth_api/__init__.py
  auth-api/src/auth_api/resources/org_authorizations.py
  auth-api/src/auth_api/schemas/product_code.py
  auth-api/src/auth_api/services/authorization.py
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/products.py
  auth-api/src/auth_api/utils/enums.py
  auth-api/tests/unit/api/test_org_authorisations.py
  auth-api/tests/unit/services/test_authorization.py
  auth-api/tests/unit/services/test_org.py
Labels: enhancement

#1227 valiadtion for bank info
  auth-web/src/components/auth/account-freeze/ReviewBankInformation.vue
  auth-web/src/components/auth/common/PADInfoForm.vue
  auth-web/src/components/auth/common/PaymentMethods.vue
Labels: bug

#1228 Adding pad_invoice and pad_activation_mails
  auth-api/requirements.txt
  auth-api/requirements/prod.txt
  auth-api/src/auth_api/services/queue_publisher.py
  auth-api/src/auth_api/utils/handlers.py
  queue_services/account-mailer/q_cli.py
  queue_services/account-mailer/src/account_mailer/email_processors/common_mailer.py
  queue_services/account-mailer/src/account_mailer/email_templates/account_conf_over_email.html
  queue_services/account-mailer/src/account_mailer/email_templates/pad_invoice_email.html
  queue_services/account-mailer/src/account_mailer/enums.py
  queue_services/account-mailer/src/account_mailer/worker.py
  queue_services/account-mailer/tests/integration/test_worker_queue.py
  queue_services/events-listener/requirements.txt
  queue_services/events-listener/requirements/repo-libraries.txt
  queue_services/events-listener/src/events_listener/config.py
  queue_services/events-listener/src/events_listener/worker.py
Labels: enhancement

#1231 correcting reqs
  queue_services/events-listener/requirements.txt
  queue_services/events-listener/requirements/repo-libraries.txt
Labels: skip-changelog

#1232 6038 : Fixing NSF partial payments
  auth-web/src/components/auth/account-freeze/AccountOverview.vue
  auth-web/src/models/invoice.ts
  auth-web/src/store/modules/org.ts
Labels: skip-changelog

#1233 Dev to Test
  auth-api/requirements.txt
  auth-api/requirements/prod.txt
  auth-api/src/auth_api/services/queue_publisher.py
  auth-api/src/auth_api/utils/handlers.py
  auth-web/src/components/auth/account-freeze/AccountOverview.vue
  auth-web/src/models/invoice.ts
  auth-web/src/store/modules/org.ts
  queue_services/account-mailer/q_cli.py
  queue_services/account-mailer/src/account_mailer/email_processors/common_mailer.py
  queue_services/account-mailer/src/account_mailer/email_templates/account_conf_over_email.html
  queue_services/account-mailer/src/account_mailer/email_templates/pad_invoice_email.html
  queue_services/account-mailer/src/account_mailer/enums.py
  queue_services/account-mailer/src/account_mailer/worker.py
  queue_services/account-mailer/tests/integration/test_worker_queue.py
  queue_services/events-listener/requirements.txt
  queue_services/events-listener/requirements/repo-libraries.txt
  queue_services/events-listener/src/events_listener/config.py
  queue_services/events-listener/src/events_listener/worker.py
Labels: skip-changelog

#1234 addedd payment mehod side menu permission for staff user
  auth-web/src/util/common-util.ts
Labels: bug

#1237 removing base64 logging and fixed config
  queue_services/account-mailer/src/account_mailer/worker.py
  queue_services/events-listener/src/events_listener/config.py
Labels: enhancement

#1238 removing base64 logging and fixed config (#1237)
  queue_services/account-mailer/src/account_mailer/worker.py
  queue_services/events-listener/src/events_listener/config.py
Labels: enhancement

#1239 addedd payment mehod side menu permission for staff user
  auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
Labels: bug

#1240 Fix for NR CLI
  queue_services/account-mailer/q_cli.py
  queue_services/account-mailer/src/account_mailer/email_templates/account_conf_over_email.html
Labels: skip-changelog

#1241 dev to test merge
  auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
  queue_services/account-mailer/q_cli.py
  queue_services/account-mailer/src/account_mailer/email_templates/account_conf_over_email.html
Labels: skip-changelog

#1243 removed update call if there is not change in bank information
  auth-web/src/components/auth/account-freeze/ReviewBankInformation.vue
Labels: bug

#1242 Adding account status in user_Settings api
  auth-api/src/auth_api/models/user_settings.py
  auth-api/src/auth_api/schemas/user_settings.py
  auth-api/src/auth_api/services/user_settings.py
Labels: enhancement

#1246 minor bug fixes in q
  queue_services/account-mailer/src/account_mailer/enums.py
  queue_services/account-mailer/src/account_mailer/worker.py
  queue_services/events-listener/src/events_listener/config.py
  queue_services/events-listener/src/events_listener/worker.py
Labels: skip-changelog
