Repository bcgov/sbc-auth, pull requests merged in 2020-07, with the labels that each got.

#912 Move pr label check to development branch.
  .github/workflows/main-pr-check.yml
  .github/workflows/pr-label-check.yml
Labels: devops

#919 added new permission to view contacts
  auth-web/src/components/auth/AccountInfo.vue
  auth-web/src/util/common-util.ts
  auth-web/src/util/constants.ts
Labels: bug

#918 Add delete user, assign role function in Keycloak service and add tester role endpoint in Reset api.
  auth-api/src/auth_api/resources/reset.py
  auth-api/src/auth_api/services/keycloak.py
  auth-api/src/auth_api/services/reset.py
  auth-api/src/auth_api/utils/enums.py
  auth-api/tests/docker/setup/demo-realm.json
  auth-api/tests/unit/api/test_reset.py
  auth-api/tests/unit/services/test_keycloak.py
  auth-api/tests/unit/services/test_reset.py
  auth-api/tests/utilities/factory_scenarios.py
Labels: devops

#921 Rollback the keycloak service delete user and assign role function.
  auth-api/src/auth_api/resources/reset.py
  auth-api/src/auth_api/services/keycloak.py
  auth-api/src/auth_api/services/reset.py
  auth-api/tests/unit/api/test_reset.py
  auth-api/tests/unit/services/test_keycloak.py
  auth-api/tests/unit/services/test_reset.py
Labels: bug

#923 Account info not visible for Account Coordinator/User -Fixed
  auth-api/migrations/versions/32b50299e3a3_permission_for_account_coordinators.py
Labels: bug

#925 Update content on affidavit instructions#4272
  auth-web/src/components/auth/NonBcscAccounts/AffidavitDownload.vue
Labels: feature

#915 [entity4084] Create Account Button and Menu Item
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/src/components/auth/MemberDataTable.vue
  auth-web/src/components/auth/TransactionsDataTable.vue
  auth-web/src/views/auth/AccountSettings.vue
Labels: feature

#929 fixing the lock version
  auth-web/package-lock.json
Labels: skip-changelog
