Repository bcgov/sbc-auth, pull requests merged in 2021-02, with the labels that each got.

#1333 Feature/5662
  auth-web/src/components/pay/PayWithCreditCard.vue
  auth-web/src/components/pay/PayWithOnlineBanking.vue
  auth-web/src/components/pay/PaymentCard.vue
  auth-web/src/services/payment.services.ts
  auth-web/src/views/pay/PaymentView.vue
  auth-web/tests/unit/components/PayWithCreditCard.spec.ts
  auth-web/tests/unit/components/PayWithOnlineBanking.spec.ts
  auth-web/tests/unit/components/PaymentCard.spec.ts
Labels: enhancement

#1336 correcting message type for the outstanding invoice type
  queue_services/account-mailer/src/account_mailer/enums.py
Labels: skip-changelog

#1338 Adding attribute to elements in UI #6275
  auth-web/src/components/auth/common/PADInfoForm.vue
  auth-web/src/components/auth/common/PaymentMethods.vue
  auth-web/src/components/auth/common/TermsOfUseDialog.vue
  auth-web/src/components/auth/common/stepper/Stepper.vue
  auth-web/src/components/auth/create-account/AccountCreateBasic.vue
  auth-web/src/components/auth/create-account/AccountCreatePremium.vue
  auth-web/src/components/auth/create-account/AccountTypeSelector.vue
  auth-web/src/components/auth/create-account/BcolLogin.vue
  auth-web/src/components/auth/create-account/PaymentMethodSelector.vue
  auth-web/src/components/auth/create-account/PremiumChooser.vue
  auth-web/src/components/auth/create-account/UserProfileForm.vue
  auth-web/src/views/auth/create-account/AccountCreationSuccessView.vue
  auth-web/src/views/auth/create-account/AccountSetupView.vue
  auth-web/tests/unit/components/AccountOverview.spec.ts
  auth-web/tests/unit/components/AccountSuspendAlert.spec.ts
  auth-web/tests/unit/components/StaffSuspendedAccountsTable.spec.ts
  auth-web/tests/unit/util/config-helper.spec.ts
  auth-web/tests/unit/views/AccountFreezeUnlockView.spec.ts
Labels: enhancement

#1340 Adding attribute to elements in UI #6275 (#1338)
  auth-web/src/components/auth/common/PADInfoForm.vue
  auth-web/src/components/auth/common/PaymentMethods.vue
  auth-web/src/components/auth/common/TermsOfUseDialog.vue
  auth-web/src/components/auth/common/stepper/Stepper.vue
  auth-web/src/components/auth/create-account/AccountCreateBasic.vue
  auth-web/src/components/auth/create-account/AccountCreatePremium.vue
  auth-web/src/components/auth/create-account/AccountTypeSelector.vue
  auth-web/src/components/auth/create-account/BcolLogin.vue
  auth-web/src/components/auth/create-account/PaymentMethodSelector.vue
  auth-web/src/components/auth/create-account/PremiumChooser.vue
  auth-web/src/components/auth/create-account/UserProfileForm.vue
  auth-web/src/views/auth/create-account/AccountCreationSuccessView.vue
  auth-web/src/views/auth/create-account/AccountSetupView.vue
  auth-web/tests/unit/components/AccountOverview.spec.ts
  auth-web/tests/unit/components/AccountSuspendAlert.spec.ts
  auth-web/tests/unit/components/StaffSuspendedAccountsTable.spec.ts
  auth-web/tests/unit/util/config-helper.spec.ts
  auth-web/tests/unit/views/AccountFreezeUnlockView.spec.ts
Labels: devops

#1342 Amount displayed in OB pending amount email
  queue_services/account-mailer/src/account_mailer/email_templates/paymanet_pending.html
Labels: bug

#1339 #4909-Provide administrators the ability to remove other admins.
  auth-api/src/auth_api/services/invitation.py
  auth-api/src/auth_api/services/membership.py
  auth-web/src/components/auth/account-settings/team-management/MemberDataTable.vue
Labels: enhancement

#1334 Changes to reflect backend changes on pay to restructure GL code structure
  auth-web/src/components/auth/staff/gl-code/GLCodeDetailsModal.vue
  auth-web/src/components/auth/staff/gl-code/GLCodesDataTable.vue
  auth-web/src/models/Staff.ts
  auth-web/src/services/payment.services.ts
  auth-web/src/store/modules/staff.ts
Labels: enhancement

#1345 Fix lint errors.
  auth-web/src/components/auth/account-settings/team-management/MemberDataTable.vue
  auth-web/tests/unit/components/PayWithCreditCard.spec.ts
  auth-web/tests/unit/components/PayWithOnlineBanking.spec.ts
  auth-web/tests/unit/components/PaymentCard.spec.ts
Labels: bug

#1344 Dev to Test #4909
  auth-api/src/auth_api/services/invitation.py
  auth-api/src/auth_api/services/membership.py
  auth-web/src/components/auth/account-settings/team-management/MemberDataTable.vue
  auth-web/src/components/auth/staff/gl-code/GLCodeDetailsModal.vue
  auth-web/src/components/auth/staff/gl-code/GLCodesDataTable.vue
  auth-web/src/models/Staff.ts
  auth-web/src/services/payment.services.ts
  auth-web/src/store/modules/staff.ts
  auth-web/tests/unit/components/PayWithCreditCard.spec.ts
  auth-web/tests/unit/components/PayWithOnlineBanking.spec.ts
  auth-web/tests/unit/components/PaymentCard.spec.ts
  queue_services/account-mailer/src/account_mailer/email_templates/paymanet_pending.html
Labels: skip-changelog

#1348 Payment when you have a credit #5662
  auth-web/src/components/pay/PayWithOnlineBanking.vue
Labels: bug

#1350 account suspend header fix
  auth-web/src/views/auth/account-freeze/AccountFreezeUnlockView.vue
  auth-web/src/views/auth/account-freeze/AccountFreezeView.vue
  auth-web/src/views/auth/account-freeze/AccountSuspendedView.vue
Labels: skip-changelog

#1347 Added suspend/activate accounts
  auth-api/migrations/versions/8260fac9943d_suspended_status.py
  auth-api/requirements.txt
  auth-api/src/auth_api/resources/org.py
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/permissions.py
  auth-api/src/auth_api/utils/enums.py
  auth-api/src/auth_api/utils/roles.py
  auth-api/tests/unit/api/test_org.py
  auth-api/tests/unit/services/test_org.py
  auth-api/tests/utilities/factory_scenarios.py
Labels: enhancement

#1343 [entity5702] Locate Bank Account Information Dialog
  auth-web/src/assets/img/cheque-sample.jpg
  auth-web/src/components/auth/common/PADInfoForm.vue
Labels: feature

#1351 added tofix for credit amount
  auth-web/src/components/pay/PayWithOnlineBanking.vue
Labels: skip-changelog

#1352 Implementing suspend account server call from org service
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/services/org.services.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/views/auth/account-freeze/AccountFreezeUnlockView.vue
  auth-web/src/views/auth/account-freeze/AccountFreezeView.vue
  auth-web/src/views/auth/account-freeze/AccountSuspendedView.vue
  auth-web/tests/unit/components/AccountInfo.spec.ts
  auth-web/tests/unit/views/AccountFreezeUnlockView.spec.ts
Labels: enhancement

#1354 multiple status handled
  auth-api/src/auth_api/models/org.py
  auth-api/src/auth_api/resources/org.py
  auth-api/src/auth_api/services/org.py
  auth-api/tests/unit/api/test_org.py
  auth-web/src/components/auth/staff/account-management/StaffActiveAccountsTable.vue
  auth-web/src/components/auth/staff/account-management/StaffSuspendedAccountsTable.vue
  auth-web/src/models/Organization.ts
  auth-web/src/services/staff.services.ts
Labels: enhancement

#1355 Staff manually suspend account#6121 | version updated
  auth-web/package-lock.json
  auth-web/package.json
Labels: skip-changelog

#1356 Staff manually suspend account#6121
  auth-web/src/routes/index.ts
Labels: skip-changelog

#1357 ReviewBankInformation unit test fix
  auth-web/src/components/auth/account-freeze/ReviewBankInformation.vue
  auth-web/src/components/auth/common/PADInfoForm.vue
  auth-web/tests/unit/components/ReviewBankInformation.spec.ts
Labels: skip-changelog

#1359 Added search result for incorporations in staff dashboard
  auth-web/src/models/business.ts
  auth-web/src/services/org.services.ts
  auth-web/src/store/modules/business.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/views/auth/staff/IncorporationSearchResultView.vue
  auth-web/src/views/auth/staff/StaffDashboardView.vue
  auth-web/tests/unit/views/IncorporationSearchResultView.spec.ts
  auth-web/tests/unit/views/SearchBusinessView.spec.ts
Labels: enhancement

#1362 6404-Staff not able to remove an invitation
  auth-api/requirements.txt
  auth-api/src/auth_api/resources/org.py
  auth-api/src/auth_api/services/org.py
  notify-api/requirements.txt
Labels: bug, enhancement

#1361 Generate Passcode component
  auth-web/src/locales/en.json
  auth-web/src/util/common-util.ts
  auth-web/src/views/auth/staff/GeneratePasscodeView.vue
  auth-web/src/views/auth/staff/IncorporationSearchResultView.vue
  auth-web/src/views/auth/staff/StaffDashboardView.vue
  auth-web/tests/unit/views/GeneratePasscodeView.spec.ts
Labels: enhancement

#1364 QA comments fix for 6121
  auth-api/src/auth_api/services/org.py
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/components/auth/common/AccountSuspendAlert.vue
  auth-web/src/views/auth/AccountSettings.vue
Labels: skip-changelog

#1363 DEV to TEST
  auth-api/requirements.txt
  auth-api/src/auth_api/resources/org.py
  auth-api/src/auth_api/services/org.py
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/components/auth/common/AccountSuspendAlert.vue
  auth-web/src/locales/en.json
  auth-web/src/models/business.ts
  auth-web/src/services/org.services.ts
  auth-web/src/store/modules/business.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/util/common-util.ts
  auth-web/src/views/auth/AccountSettings.vue
  auth-web/src/views/auth/staff/GeneratePasscodeView.vue
  auth-web/src/views/auth/staff/IncorporationSearchResultView.vue
  auth-web/src/views/auth/staff/StaffDashboardView.vue
  auth-web/tests/unit/views/GeneratePasscodeView.spec.ts
  auth-web/tests/unit/views/IncorporationSearchResultView.spec.ts
  auth-web/tests/unit/views/SearchBusinessView.spec.ts
  notify-api/requirements.txt
Labels: skip-changelog

#1365 Test cases for 6121 and 6277 tasks
  auth-web/tests/unit/components/AccountInfo.spec.ts
  auth-web/tests/unit/views/AccountSuspendedView.spec.ts
  auth-web/tests/unit/views/GeneratePasscodeView.spec.ts
  auth-web/tests/unit/views/IncorporationSearchResultView.spec.ts
Labels: skip-changelog

#1366 Provide Clear Message on Result of Credit Card Payment#6325
  auth-web/src/components/pay/common/PaymentErrorMessage.vue
  auth-web/src/locales/en.json
  auth-web/src/util/constants.ts
  auth-web/src/views/pay/PaymentReturnView.vue
  auth-web/tests/unit/components/PaymentErrorMessage.spec.ts
  auth-web/tests/unit/views/PaymentReturnView.spec.ts
Labels: enhancement

#1368 Provide Clear Message on Result of Credit Card Payment#6325
  auth-web/src/views/pay/PaymentReturnView.vue
Labels: skip-changelog

#1369 Feature/6325 2
  auth-web/src/components/pay/common/PaymentErrorMessage.vue
  auth-web/src/views/pay/PaymentReturnView.vue
Labels: skip-changelog

#1372 updated sbc common component version
  auth-web/package-lock.json
  auth-web/package.json
Labels: skip-changelog

#1371 Bug/6277 redirect issue
  auth-web/src/components/auth/common/AccountSuspendAlert.vue
  auth-web/src/store/modules/org.ts
  auth-web/src/views/auth/staff/IncorporationSearchResultView.vue
  auth-web/src/views/auth/staff/StaffDashboardView.vue
  auth-web/tests/unit/views/IncorporationSearchResultView.spec.ts
Labels: skip-changelog

#1376 GeneratePasscode UI updates
  auth-web/src/views/auth/staff/GeneratePasscodeView.vue
Labels: skip-changelog

#1375 6391 - Wording on Account Info Screen
  auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
  auth-web/tests/unit/components/AccountPaymentMethods.spec.ts
Labels: enhancement

#1377 Provide Clear Message on Result of Credit Card Payment#6325
  auth-web/src/locales/en.json
Labels: skip-changelog

#1378 Dev to test
  auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
  auth-web/src/locales/en.json
  auth-web/src/views/auth/staff/GeneratePasscodeView.vue
  auth-web/tests/unit/components/AccountPaymentMethods.spec.ts
Labels: skip-changelog

#1379 Add visual for PAD Payment Method (void cheque)
  auth-web/src/components/auth/common/PADInfoForm.vue
Labels: skip-changelog

#1381 dev to test
  auth-web/src/components/auth/common/PADInfoForm.vue
Labels: skip-changelog

#1367 Changes for sending email for JV failures
  .github/workflows/account-mailer-ci.yml
  .gitignore
  queue_services/account-mailer/requirements.txt
  queue_services/account-mailer/src/account_mailer/config.py
  queue_services/account-mailer/src/account_mailer/email_processors/ejv_failures.py
  queue_services/account-mailer/src/account_mailer/email_templates/ejv_failed_email.html
  queue_services/account-mailer/src/account_mailer/enums.py
  queue_services/account-mailer/src/account_mailer/services/minio_service.py
  queue_services/account-mailer/src/account_mailer/worker.py
  queue_services/account-mailer/tests/conftest.py
  queue_services/account-mailer/tests/docker/docker-compose.yml
  queue_services/account-mailer/tests/integration/test_worker_queue.py
Labels: enhancement

#1384 pay loading issue
  auth-web/src/views/pay/PaymentReturnView.vue
Labels: skip-changelog

#1385 pay loading issue (#1384)
  auth-web/src/views/pay/PaymentReturnView.vue
Labels: skip-changelog

#1386 pay loading issue (#1384) (#1385)
  auth-web/src/views/pay/PaymentReturnView.vue
Labels: skip-changelog
