Repository bcgov/sbc-auth, pull requests merged in 2021-04, with the labels that each got.

#1487 Update configuration.json
  auth-web/public/config/configuration.json
Labels: devops

#1486 Added product subscription for clients
  auth-api/migrations/versions/b22ee0cd18ad_productsubscriptionsstatus_added.py
  auth-api/requirements.txt
  auth-api/src/auth_api/config.py
  auth-api/src/auth_api/exceptions/errors.py
  auth-api/src/auth_api/models/__init__.py
  auth-api/src/auth_api/models/product_code.py
  auth-api/src/auth_api/models/product_subscription.py
  auth-api/src/auth_api/models/product_subscriptions_status.py
  auth-api/src/auth_api/resources/org_products.py
  auth-api/src/auth_api/services/authorization.py
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/products.py
  auth-api/src/auth_api/utils/enums.py
  auth-api/src/auth_api/utils/roles.py
  auth-api/tests/unit/api/test_org.py
  auth-api/tests/unit/api/test_org_products.py
  auth-api/tests/unit/services/test_org.py
  auth-api/tests/utilities/factory_scenarios.py
  auth-api/tests/utilities/factory_utils.py
Labels: enhancement

#1484 Wills Registry - Submit Request for Access#6872
  auth-web/src/components/auth/account-settings/product/ProductPackage.vue
  auth-web/src/components/auth/common/Product.vue
  auth-web/src/locales/en.json
  auth-web/src/models/Organization.ts
  auth-web/src/routes/router.ts
  auth-web/src/services/org.services.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/AccountSettings.vue
  auth-web/tests/unit/components/Product.spec.ts
  auth-web/tests/unit/components/ProductPackage.spec.ts
Labels: WIP, enhancement

#1490 incorporated PR comments , permissions fixed
  auth-api/migrations/versions/19a7733fd001_merge_heads.py
  auth-api/migrations/versions/68c71d35f671_product_setting_permission_and_view_.py
  auth-api/src/auth_api/services/products.py
  auth-web/src/components/auth/account-settings/product/ProductPackage.vue
  auth-web/src/store/modules/org.ts
Labels: skip-changelog

#1492 Wills Registry - Submit Request for Access#6872
  auth-web/src/components/auth/account-settings/product/ProductPackage.vue
  auth-web/src/components/auth/common/Product.vue
Labels: skip-changelog

#1495 Bug/invite
  auth-web/src/locales/en.json
  auth-web/src/views/auth/staff/SetupAccountSuccessView.vue
Labels: skip-changelog

#1494 Jwt wrapper
  auth-api/src/auth_api/__init__.py
  auth-api/src/auth_api/auth.py
  auth-api/src/auth_api/jwt_wrapper.py
  auth-api/src/auth_api/resources/account.py
  auth-api/src/auth_api/resources/bcol_profiles.py
  auth-api/src/auth_api/resources/bulk_user.py
  auth-api/src/auth_api/resources/codes.py
  auth-api/src/auth_api/resources/documents.py
  auth-api/src/auth_api/resources/documents_affidavit.py
  auth-api/src/auth_api/resources/entity.py
  auth-api/src/auth_api/resources/invitation.py
  auth-api/src/auth_api/resources/notifications.py
  auth-api/src/auth_api/resources/org.py
  auth-api/src/auth_api/resources/org_api_keys.py
  auth-api/src/auth_api/resources/org_authorizations.py
  auth-api/src/auth_api/resources/org_products.py
  auth-api/src/auth_api/resources/permissions.py
  auth-api/src/auth_api/resources/products.py
  auth-api/src/auth_api/resources/reset.py
  auth-api/src/auth_api/resources/task.py
  auth-api/src/auth_api/resources/user.py
  auth-api/src/auth_api/resources/user_settings.py
  auth-api/tests/conftest.py
Labels: skip-changelog

#1489 Updated affiliation modal
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/src/components/auth/common/HelpDialog.vue
  auth-web/src/components/auth/manage-business/AddBusinessForm.vue
  auth-web/src/components/auth/manage-business/AddNameRequestForm.vue
  auth-web/src/components/auth/manage-business/EntityManagement.vue
  auth-web/src/locales/en.json
  auth-web/src/util/common-util.ts
  auth-web/src/views/auth/HomeViewOutdated.vue
  auth-web/src/views/auth/home/HomeView.vue
  auth-web/src/views/auth/home/MaintainBusinessView.vue
  auth-web/tests/unit/components/AddBusinessForm.spec.ts
  auth-web/tests/unit/components/AddNameRequestForm.spec.ts
  auth-web/tests/unit/components/PaymentMethods.spec.ts
  auth-web/tests/unit/util/common-util.spec.ts
Labels: enhancement

#1498 Adding exclusion of json file from pre caching
  auth-web/vue.config.js
Labels: skip-changelog

#1504 Feature/6886 test cases
  auth-api/tests/unit/api/test_task.py
  auth-api/tests/unit/services/test_task.py
Labels: skip-changelog

#1506 Minio url update for account-mailer
  queue_services/account-mailer/src/account_mailer/email_templates/common/style.html
  queue_services/account-mailer/src/account_mailer/pdf_templates/common/fonts.html
Labels: bug, skip-changelog

#1509 4118 - update product subscription task implementation
  auth-api/src/auth_api/models/task.py
  auth-api/src/auth_api/resources/task.py
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/products.py
  auth-api/src/auth_api/services/task.py
  auth-api/src/auth_api/utils/enums.py
  auth-api/tests/unit/api/test_task.py
  auth-api/tests/unit/models/test_task.py
  auth-api/tests/unit/services/test_org.py
  auth-api/tests/unit/services/test_task.py
  auth-api/tests/utilities/factory_utils.py
Labels: enhancement

#1505 Review Requests to Access Wills Search & Registration Application#4118
  auth-web/src/components/auth/common/Product.vue
  auth-web/src/components/auth/common/ProductTOS.vue
  auth-web/src/components/auth/staff/review-task/AccessRequestModal.vue
  auth-web/src/components/auth/staff/review-task/AccountAdministrator.vue
  auth-web/src/components/auth/staff/review-task/AccountInformation.vue
  auth-web/src/components/auth/staff/review-task/AccountStatus.vue
  auth-web/src/components/auth/staff/review-task/AgreementInformation.vue
  auth-web/src/components/auth/staff/review-task/DownloadAffidavit.vue
  auth-web/src/components/auth/staff/review-task/NotaryInformation.vue
  auth-web/src/views/auth/staff/ReviewAccountView.vue
Labels: WIP, enhancement

#1515 Feature/4118 backend part2
  auth-api/migrations/versions/885632ab6357_insert_tasks_table_with_pending_orgs.py
  auth-api/src/auth_api/resources/task.py
  auth-api/src/auth_api/services/task.py
  auth-api/tests/unit/api/test_task.py
Labels: WIP, enhancement

#1514 added base 64 encode of the org name
  auth-api/src/auth_api/services/invitation.py
  auth-api/src/auth_api/utils/util.py
  auth-api/tests/unit/utils/test_util.py
  auth-web/src/components/auth/mixins/NextPageMixin.vue
  auth-web/src/routes/router.ts
Labels: bug

#1518 Review Requests to Access Wills Search & Registration Application#4118
  auth-web/src/models/Task.ts
  auth-web/src/services/task.services.ts
  auth-web/src/store/index.ts
  auth-web/src/store/modules/staff.ts
  auth-web/src/store/modules/task.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/staff/ReviewAccountView.vue
Labels: WIP, skip-changelog

#1519 Fetch Tasks Pagination issue Fix
  auth-api/src/auth_api/models/task.py
  auth-api/src/auth_api/resources/task.py
  auth-api/src/auth_api/services/task.py
  auth-api/tests/unit/api/test_task.py
  auth-api/tests/unit/services/test_task.py
Labels: WIP, enhancement

#1520 4118 - Add column in tasks table and update logic
  auth-api/migrations/versions/031a07fb0811_add_account_id_column_in_tasks_table.py
  auth-api/src/auth_api/models/task.py
  auth-api/src/auth_api/schemas/schemas/task_request.json
  auth-api/src/auth_api/services/products.py
  auth-api/src/auth_api/services/task.py
  auth-api/tests/unit/api/test_task.py
  auth-api/tests/unit/models/test_task.py
  auth-api/tests/unit/services/test_task.py
Labels: WIP, enhancement

#1521 Clean up for product subscriptions and tasks
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/products.py
  auth-api/src/auth_api/services/task.py
  auth-api/tests/unit/api/test_org_products.py
  auth-api/tests/unit/api/test_task.py
Labels: skip-changelog

#1522 Fix for pending approval pages
  auth-web/src/components/auth/mixins/NextPageMixin.vue
  auth-web/src/routes/index.ts
  auth-web/src/routes/router.ts
Labels: skip-changelog

#1525 Automated Query Request #6972
  jobs/notebook-report/Dockerfile
  jobs/notebook-report/Makefile
  jobs/notebook-report/README.md
  jobs/notebook-report/config.py
  jobs/notebook-report/logging.conf
  jobs/notebook-report/notebookreport.py
  jobs/notebook-report/openshift/Readme.md
  jobs/notebook-report/openshift/templates/bc.yaml
  jobs/notebook-report/openshift/templates/cronjob.yaml
  jobs/notebook-report/requirements.txt
  jobs/notebook-report/requirements/dev.txt
  jobs/notebook-report/requirements/prod.txt
  jobs/notebook-report/run.sh
  jobs/notebook-report/setup.cfg
  jobs/notebook-report/setup.py
  jobs/notebook-report/tests/unit/__init__.py
  jobs/notebook-report/tests/unit/conftest.py
  jobs/notebook-report/tests/unit/test_job.py
  jobs/notebook-report/util/__init__.py
  jobs/notebook-report/util/logging.py
  jobs/notebook-report/weekly/auth.ipynb
Labels: devops

#1526 4118 - fetch tasks and task type update
  auth-api/migrations/versions/885632ab6357_insert_tasks_table_with_pending_orgs.py
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/products.py
  auth-api/src/auth_api/utils/enums.py
  auth-api/tests/unit/api/test_task.py
  auth-api/tests/unit/models/test_task.py
  auth-api/tests/unit/services/test_task.py
  auth-api/tests/utilities/factory_utils.py
  auth-web/src/components/auth/staff/account-management/StaffAccountManagement.vue
  auth-web/src/components/auth/staff/account-management/StaffPendingAccountsTable.vue
  auth-web/src/models/Task.ts
  auth-web/src/services/task.services.ts
  auth-web/src/store/modules/staff.ts
  auth-web/src/store/modules/task.ts
  auth-web/src/util/constants.ts
Labels: WIP, enhancement

#1527 Feature/4118 1
  auth-web/src/components/auth/staff/review-task/AccountStatus.vue
  auth-web/src/store/modules/staff.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/staff/ReviewAccountView.vue
Labels: skip-changelog

#1528 Feature/4118 2
  auth-web/src/components/auth/staff/review-task/AccountStatus.vue
  auth-web/src/models/Task.ts
  auth-web/src/services/task.services.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/staff/ReviewAccountView.vue
Labels: skip-changelog

#1530 added new column TaskRelationshipStatus in Tasks table
  auth-api/migrations/versions/031a07fb0811_add_account_id_column_in_tasks_table.py
  auth-api/migrations/versions/885632ab6357_insert_tasks_table_with_pending_orgs.py
  auth-api/src/auth_api/models/task.py
  auth-api/src/auth_api/resources/task.py
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/products.py
  auth-api/src/auth_api/services/task.py
  auth-api/src/auth_api/utils/enums.py
  auth-api/tests/unit/api/test_task.py
  auth-api/tests/unit/models/test_task.py
  auth-api/tests/unit/services/test_task.py
  auth-api/tests/utilities/factory_utils.py
  auth-web/src/components/auth/staff/account-management/StaffAccountManagement.vue
  auth-web/src/services/task.services.ts
  auth-web/src/store/modules/task.ts
Labels: enhancement

#1533 Review Requests to Access Wills Search & Registration Application#4118
  auth-web/src/services/task.services.ts
Labels: skip-changelog

#1529 4118 approval
  auth-api/migrations/versions/031a07fb0811_add_account_id_column_in_tasks_table.py
  auth-api/migrations/versions/885632ab6357_insert_tasks_table_with_pending_orgs.py
  auth-api/src/auth_api/models/task.py
  auth-api/src/auth_api/resources/task.py
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/products.py
  auth-api/src/auth_api/services/task.py
  auth-api/src/auth_api/utils/enums.py
  auth-api/tests/unit/api/test_task.py
  auth-api/tests/unit/models/test_task.py
  auth-api/tests/unit/services/test_task.py
  auth-api/tests/utilities/factory_utils.py
  auth-web/src/components/auth/staff/account-management/StaffAccountManagement.vue
  auth-web/src/components/auth/staff/account-management/StaffPendingAccountsTable.vue
  auth-web/src/components/auth/staff/review-task/AccountStatus.vue
  auth-web/src/models/Task.ts
  auth-web/src/services/task.services.ts
  auth-web/src/store/index.ts
  auth-web/src/store/modules/staff.ts
  auth-web/src/store/modules/task.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/staff/ReviewAccountView.vue
Labels: enhancement

#1534 migration changes
  auth-api/migrations/versions/031a07fb0811_add_account_id_column_in_tasks_table.py
  auth-api/migrations/versions/885632ab6357_insert_tasks_table_with_pending_orgs.py
Labels: enhancement, skip-changelog

#1535 Review Requests to Access Wills Search & Registration Application#4118
  auth-web/src/components/auth/staff/account-management/StaffPendingAccountsTable.vue
  auth-web/src/components/auth/staff/review-task/AccountStatus.vue
  auth-web/src/views/auth/staff/ReviewAccountView.vue
Labels: skip-changelog

#1536 Feature/4118 rejected tasks dashboard
  auth-api/migrations/versions/885632ab6357_insert_tasks_table_with_pending_orgs.py
  auth-api/src/auth_api/services/products.py
  auth-api/src/auth_api/utils/enums.py
  auth-api/tests/unit/api/test_task.py
  auth-api/tests/unit/services/test_task.py
  auth-web/src/components/auth/staff/account-management/StaffAccountManagement.vue
  auth-web/src/components/auth/staff/account-management/StaffPendingAccountsTable.vue
  auth-web/src/components/auth/staff/account-management/StaffRejectedAccountsTable.vue
  auth-web/src/models/Task.ts
  auth-web/src/services/task.services.ts
  auth-web/src/store/modules/task.ts
Labels: WIP, enhancement

#1539 dev to master push for Test merge
  auth-api/migrations/versions/885632ab6357_insert_tasks_table_with_pending_orgs.py
Labels: skip-changelog

#1542 4118 - Migration script and notification mail update
  auth-api/migrations/versions/885632ab6357_insert_tasks_table_with_pending_orgs.py
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/task.py
Labels: enhancement, skip-changelog

#1543 4118 - merge master from dev
  auth-api/migrations/versions/885632ab6357_insert_tasks_table_with_pending_orgs.py
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/task.py
Labels: skip-changelog

#1545 Review Requests to Access Wills Search & Registration Application#411…
  auth-web/src/components/auth/common/Product.vue
Labels: skip-changelog

#1541 Changes for sending email for BCOL refunds
  queue_services/account-mailer/requirements.txt
  queue_services/account-mailer/src/account_mailer/config.py
  queue_services/account-mailer/src/account_mailer/email_processors/refund_requested.py
  queue_services/account-mailer/src/account_mailer/email_templates/bcol_refund_request_email.html
  queue_services/account-mailer/src/account_mailer/email_templates/creditcard_refund_request_email.html
  queue_services/account-mailer/src/account_mailer/enums.py
  queue_services/account-mailer/src/account_mailer/worker.py
  queue_services/account-mailer/tests/conftest.py
  queue_services/account-mailer/tests/integration/test_worker_queue.py
  queue_services/account-mailer/tests/integration/utils.py
Labels: enhancement

#1548 Formatting refund email
  queue_services/account-mailer/src/account_mailer/email_templates/bcol_refund_request_email.html
Labels: skip-changelog

#1550 Change Title from Search Cooperatives to Search Business#6591
  auth-web/src/views/auth/staff/StaffDashboardView.vue
  auth-web/tests/unit/components/AgreementInformation.spec.ts
  auth-web/tests/unit/components/Product.spec.ts
  auth-web/tests/unit/components/ProductTOS.spec.ts
Labels: skip-changelog

#1551 Fixed Roles not getting displayed for GOVM member invitations
  auth-api/src/auth_api/services/invitation.py
Labels: bug

#1553 Fix for affidavit not refreshing issue
  auth-web/src/store/modules/staff.ts
  auth-web/src/views/auth/staff/ReviewAccountView.vue
Labels: bug

#1555 Change Title from Search Cooperatives to Search Business#6591
  auth-web/src/views/auth/staff/StaffDashboardView.vue
Labels: skip-changelog

#1557 2.5.13 patch 3
  auth-web/src/components/auth/staff/account-management/StaffPendingAccountsTable.vue
  auth-web/src/components/auth/staff/account-management/StaffRejectedAccountsTable.vue
  auth-web/src/store/modules/staff.ts
Labels: bug, skip-changelog

#1547 activity log listener queue added
  .github/workflows/activity-log-listener-cd.yml
  .github/workflows/activity-log-listener-ci.yml
  codecov.yaml
  queue_services/activity-log-listener/.envrc
  queue_services/activity-log-listener/Dockerfile
  queue_services/activity-log-listener/LICENSE
  queue_services/activity-log-listener/MANIFEST.in
  queue_services/activity-log-listener/Makefile
  queue_services/activity-log-listener/README.md
  queue_services/activity-log-listener/app.py
  queue_services/activity-log-listener/coverage.xml
  queue_services/activity-log-listener/devops/vaults.json
  queue_services/activity-log-listener/jenkins/dev.groovy
  queue_services/activity-log-listener/jenkins/prod.groovy
  queue_services/activity-log-listener/jenkins/test.groovy
  queue_services/activity-log-listener/logging.conf
  queue_services/activity-log-listener/openshift/templates/bc.yaml
  queue_services/activity-log-listener/openshift/templates/dc.yaml
  queue_services/activity-log-listener/openshift/templates/pipeline.yaml
  queue_services/activity-log-listener/q_cli.py
  queue_services/activity-log-listener/requirements.txt
  queue_services/activity-log-listener/requirements/dev.txt
  queue_services/activity-log-listener/requirements/prod.txt
  queue_services/activity-log-listener/requirements/repo-libraries.txt
  queue_services/activity-log-listener/scripts/verify_license_headers.sh
  queue_services/activity-log-listener/setup.cfg
  queue_services/activity-log-listener/setup.py
  queue_services/activity-log-listener/src/activity_log_listener/__init__.py
  queue_services/activity-log-listener/src/activity_log_listener/config.py
  queue_services/activity-log-listener/src/activity_log_listener/utils.py
  queue_services/activity-log-listener/src/activity_log_listener/version.py
  queue_services/activity-log-listener/src/activity_log_listener/worker.py
  queue_services/activity-log-listener/tests/__init__.py
  queue_services/activity-log-listener/tests/conftest.py
  queue_services/activity-log-listener/tests/docker-compose.yml
  queue_services/activity-log-listener/tests/integration/__init__.py
  queue_services/activity-log-listener/tests/integration/test_worker_queue.py
  queue_services/activity-log-listener/tests/integration/utils.py
Labels: skip-changelog

#1546 activity logs added
  auth-api/migrations/versions/d0392ebda924_activity_stream.py
  auth-api/src/auth_api/config.py
  auth-api/src/auth_api/models/__init__.py
  auth-api/src/auth_api/models/activity_log.py
  auth-api/src/auth_api/resources/__init__.py
  auth-api/src/auth_api/resources/acitivity_log.py
  auth-api/src/auth_api/schemas/__init__.py
  auth-api/src/auth_api/schemas/activity_log.py
  auth-api/src/auth_api/services/__init__.py
  auth-api/src/auth_api/services/activity_log.py
  auth-api/src/auth_api/services/activity_log_publisher.py
  auth-api/src/auth_api/services/affiliation.py
  auth-api/src/auth_api/services/entity.py
  auth-api/src/auth_api/utils/enums.py
  auth-api/tests/unit/api/test_activity_log.py
  auth-api/tests/unit/services/test_entity.py
  auth-api/tests/utilities/factory_utils.py
Labels: enhancement

#1558 add missing product codes
  auth-api/src/auth_api/services/products.py
Labels: skip-changelog

#1559 Feature/6895 backend 1
  auth-api/src/auth_api/resources/org.py
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/task.py
  auth-api/src/auth_api/utils/enums.py
  auth-api/tests/unit/services/test_task.py
Labels: WIP, enhancement, python

#1560 Ministry Government Account Prime contact selects the Product Pacakg…
  auth-web/src/components/auth/common/Product.vue
  auth-web/src/components/auth/create-account/ProductPackages.vue
  auth-web/src/services/org.services.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/views/auth/create-account/GovmAccountSetupView.vue
  auth-web/tests/unit/components/ProductPackages.spec.ts
Labels: WIP, enhancement

#1562 BCeID/2FA Changes to Registry App for desktop plugin#7314
  auth-web/src/components/auth/BceidInviteLanding.vue
  auth-web/src/components/auth/create-account/non-bcsc/AccountInstructions.vue
Labels: enhancement

#1561 GOVM needs default approvals
  auth-api/src/auth_api/services/products.py
  auth-api/tests/unit/api/test_org.py
Labels: enhancement

#1564 GOVM account dont need default products
  auth-api/src/auth_api/services/org.py
  auth-api/tests/unit/api/test_org.py
Labels: skip-changelog

#1566 Wills Registry - Submit Request for Access#6872 | wording changes
  auth-web/src/components/auth/account-settings/product/ProductPackage.vue
  auth-web/src/components/auth/common/Product.vue
  auth-web/src/views/auth/AccountSettings.vue
Labels: skip-changelog

#1565 Open NR UI in same tab
  auth-web/src/assets/scss/base.scss
  auth-web/src/components/auth/home/NameRequestButton.vue
  auth-web/src/views/auth/home/RequestNameView.vue
  auth-web/tests/unit/views/RequestNameView.spec.ts
Labels: bug, enhancement

#1567 Wills Registry - Submit Request for Access#6872 | submit button
  auth-web/src/components/auth/common/Product.vue
Labels: skip-changelog

#1568 dev to test merge
  auth-api/src/auth_api/services/org.py
  auth-api/tests/unit/api/test_org.py
  auth-web/src/assets/scss/base.scss
  auth-web/src/components/auth/account-settings/product/ProductPackage.vue
  auth-web/src/components/auth/common/Product.vue
  auth-web/src/components/auth/home/NameRequestButton.vue
  auth-web/src/views/auth/AccountSettings.vue
  auth-web/src/views/auth/home/RequestNameView.vue
  auth-web/tests/unit/views/RequestNameView.spec.ts
Labels: devops

#1569 Affidavit fix
  auth-api/migrations/versions/a37f90e6802d_affidavit_inactive_status_added.py
  auth-api/src/auth_api/models/affidavit.py
  auth-api/src/auth_api/services/affidavit.py
  auth-api/src/auth_api/utils/enums.py
  auth-api/tests/unit/api/test_org.py
  auth-api/tests/unit/services/test_affidavit.py
  auth-api/tests/utilities/factory_scenarios.py
Labels: enhancement

#1571 Fix account name display in pending pages #7369
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/src/App.vue
  auth-web/src/components/auth/staff/review-task/AccessRequestModal.vue
Labels: bug

#1573 updated task migration to cover all cases
  auth-api/migrations/versions/031a07fb0811_add_account_id_column_in_tasks_table.py
  auth-api/migrations/versions/885632ab6357_insert_tasks_table_with_pending_orgs.py
Labels: bug, skip-changelog

#1575 Merge dev to master (#1573)
  auth-api/migrations/versions/031a07fb0811_add_account_id_column_in_tasks_table.py
  auth-api/migrations/versions/885632ab6357_insert_tasks_table_with_pending_orgs.py
Labels: bug, skip-changelog

#1577 Fix account name display in pending pages #7369
  auth-web/src/components/auth/staff/review-task/AccessRequestModal.vue
  auth-web/src/views/auth/staff/ReviewAccountView.vue
Labels: skip-changelog

#1578 dev to test
  auth-web/src/components/auth/staff/review-task/AccessRequestModal.vue
  auth-web/src/views/auth/staff/ReviewAccountView.vue
Labels: skip-changelog

#1579 updated govm handling in update org
  auth-api/src/auth_api/services/org.py
Labels: WIP, enhancement

#1582 Reject tab next button disabled issue fix
  auth-web/src/components/auth/staff/account-management/StaffRejectedAccountsTable.vue
Labels: bug, skip-changelog
