Repository bcgov/sbc-auth, pull requests merged in 2021-12, with the labels that each got.

#1839 redirect URL token fix
  auth-web/src/views/auth/TermsOfServiceView.vue
Labels: skip-changelog

#1840 Adding new product code check for super admin service accounts
  auth-api/src/auth_api/services/authorization.py
Labels: skip-changelog

#1841 9332: Changes to accept GOVN account requests
  auth-api/migrations/versions/9f3450623765_task_action.py
  auth-api/src/auth_api/models/task.py
  auth-api/src/auth_api/services/affidavit.py
  auth-api/src/auth_api/services/invitation.py
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/products.py
  auth-api/src/auth_api/services/validators/access_type.py
  auth-api/src/auth_api/utils/enums.py
  auth-api/tests/unit/api/test_task.py
  auth-api/tests/unit/services/test_task.py
  auth-api/tests/utilities/factory_utils.py
Labels: enhancement

#1843 Adding user to get tasks/id
  auth-api/src/auth_api/schemas/task.py
  auth-api/src/auth_api/services/api_gateway.py
  auth-api/src/auth_api/services/task.py
Labels: skip-changelog

#1842 Non-Ministry User Account creation#9332
  auth-web/src/components/auth/common/PaymentMethods.vue
  auth-web/src/components/auth/create-account/AccountTypeSelector.vue
  auth-web/src/store/modules/org.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/ChooseAuthMethodView.vue
  auth-web/src/views/auth/create-account/AccountSetupView.vue
  auth-web/src/views/auth/create-account/non-bcsc/NonBcscAccountSetupView.vue
Labels: enhancement, WIP

#1844 9327 9333 - Staff Review screen UI WIP changes
  auth-api/src/auth_api/services/invitation.py
  auth-web/src/models/Task.ts
  auth-web/src/store/modules/staff.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/staff/ReviewAccountView.vue
  auth-web/tests/unit/services/task.service.spec.ts
Labels: enhancement, WIP

#1845 Non-Ministry Account - BC Services Card Staff Review#9333
  auth-web/src/components/auth/staff/review-task/AccessRequestModal.vue
  auth-web/src/plugins/vuetify.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/ChooseAuthMethodView.vue
Labels: enhancement

#1846 9327 - backend changes
  auth-api/src/auth_api/config.py
  auth-api/src/auth_api/models/task.py
  auth-api/src/auth_api/services/affidavit.py
  auth-api/src/auth_api/services/task.py
  auth-api/tests/unit/models/test_task.py
  queue_services/account-mailer/src/account_mailer/email_templates/resubmit_bceid_admin.html
  queue_services/account-mailer/src/account_mailer/enums.py
  queue_services/account-mailer/src/account_mailer/worker.py
Labels: enhancement, WIP

#1847 EJV payment method for GOVM account
  auth-web/src/store/modules/org.ts
Labels: bug

#1849 9327 - change GOVM task action
  auth-api/src/auth_api/config.py
  auth-api/src/auth_api/services/org.py
  auth-web/src/routes/router.ts
Labels: enhancement, WIP

#1851 Adding GET affidavit by user endpoint
  auth-api/src/auth_api/models/affidavit.py
  auth-api/src/auth_api/resources/user.py
  auth-api/src/auth_api/services/affidavit.py
  auth-api/tests/unit/api/test_user.py
Labels: enhancement

#1852 Staff approves/reject the new admin#9327
  auth-web/src/services/org.services.ts
  auth-web/src/services/user.services.ts
  auth-web/src/store/modules/staff.ts
Labels: skip-changelog

#1853 Fixing account_id on task clone
  auth-api/src/auth_api/services/affidavit.py
Labels: skip-changelog

#1854 Staff approves/reject the new admin#9327 | redirect after re-upload
  auth-web/src/views/auth/create-account/non-bcsc/NonBcscAdminInviteSetupView.vue
  auth-web/tests/unit/views/NonBcscAdminInviteSetupView.spec.ts
Labels: skip-changelog

#1850 Feature/9333-update task service to handle GOVN org requests
  auth-api/src/auth_api/services/affidavit.py
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/task.py
  auth-api/tests/unit/api/test_org.py
  auth-api/tests/unit/api/test_task.py
  auth-api/tests/unit/services/test_affidavit.py
  auth-api/tests/unit/services/test_org.py
  auth-api/tests/utilities/factory_scenarios.py
Labels: enhancement, WIP

#1855 9327 - Account mailer content update for BCeId admin template
  queue_services/account-mailer/src/account_mailer/email_templates/resubmit_bceid_admin.html
Labels: bug

#1857 notary data was not reloading while account change
  auth-web/src/views/auth/staff/ReviewAccountView.vue
Labels: skip-changelog

#1856 Notify API spec update
  docs/docs/api_contract/notify-api-1.0.0.yaml
Labels: skip-changelog

#1859 API Key added to the developer settings view
  auth-web/src/components/auth/account-settings/advance-settings/ExistingAPIKeys.vue
Labels: enhancement

#1858 removed idir validation and replaced with email validation
  auth-web/src/components/auth/account-settings/team-management/InviteUsersForm.vue
  auth-web/src/components/auth/staff/SetupGovmAccountForm.vue
  auth-web/src/util/common-util.ts
  auth-web/tests/unit/components/InviteUsersForm.spec.ts
Labels: enhancement

#1861 Fixing affidavit flag on re-send invitation
  auth-api/src/auth_api/services/invitation.py
Labels: skip-changelog

#1860 Authentication menu for govn uer
  auth-web/src/components/auth/mixins/AccountMixin.vue
  auth-web/src/views/auth/AccountSettings.vue
Labels: skip-changelog

#1862 9326 - Refactoring AffidavitService - retrieve affidavit based on user and task status
  auth-api/src/auth_api/models/affidavit.py
  auth-api/src/auth_api/resources/user.py
  auth-api/src/auth_api/services/affidavit.py
  auth-api/src/auth_api/services/task.py
  auth-api/tests/unit/api/test_user.py
  auth-api/tests/utilities/factory_scenarios.py
  auth-web/src/services/user.services.ts
  auth-web/src/store/modules/staff.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/staff/ReviewAccountView.vue
Labels: bug

#1866 10255 - Refactoring Orgs Patch to accept status and access types
  auth-api/src/auth_api/exceptions/errors.py
  auth-api/src/auth_api/resources/org.py
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/utils/enums.py
  auth-api/tests/unit/api/test_org.py
  auth-api/tests/unit/services/test_org.py
Labels: enhancement, WIP

#1867 10255 - Add premium account to non ministry feature UI changes
  auth-web/src/components/auth/account-settings/account-info/AccountAccessType.vue
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/locales/en.json
  auth-web/src/models/Organization.ts
  auth-web/src/services/org.services.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/util/constants.ts
  auth-web/tests/unit/components/AccountAccessType.spec.ts
Labels: enhancement

#1868 Change the Prod Stat Fee and Service fee for Ministry and Non Ministr…
  auth-web/src/components/auth/account-settings/product/ProductPackage.vue
  auth-web/src/components/auth/common/Product.vue
  auth-web/src/components/auth/common/ProductFeeSelector.vue
  auth-web/src/components/auth/common/ProductFeeViewEdit.vue
  auth-web/src/components/auth/staff/review-task/ProductFee.vue
  auth-web/src/models/Organization.ts
  auth-web/src/services/payment.services.ts
  auth-web/src/store/modules/org.ts
  auth-web/tests/unit/components/ProductFeeSelector.spec.ts
  auth-web/tests/unit/components/ProductFeeViewEdit.spec.ts
Labels: enhancement, WIP, feature

#1869 Change the Prod Stat Fee and Service fee for Ministry and Non Ministr…
  auth-web/src/components/auth/account-settings/product/ProductPackage.vue
Labels: skip-changelog
