Repository bcgov/sbc-auth, pull requests merged in 2021-11, with the labels that each got.

#1801 Changes for creating different keycloak clients for sandbox and prod consumers
  auth-api/migrations/versions/be4475027882_rename_tables.py
  auth-api/src/auth_api/services/api_gateway.py
  auth-api/src/auth_api/services/keycloak.py
  auth-api/src/auth_api/utils/api_gateway.py
  auth-api/src/auth_api/utils/constants.py
  auth-api/tests/docker/setup/demo-realm.json
  auth-api/tests/unit/api/test_org_api_keys.py
Labels: enhancement

#1799 API users can turn off key#7071
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/public/config/configuration.json
  auth-web/src/components/auth/account-settings/advance-settings/DeveloperAccess.vue
  auth-web/src/components/auth/account-settings/advance-settings/ExistingAPIKeys.vue
  auth-web/src/components/auth/common/AccountLoginOptionPicker.vue
  auth-web/src/locales/en.json
  auth-web/src/routes/router.ts
  auth-web/src/services/org.services.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/util/config-helper.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/AccountSettings.vue
  auth-web/tests/unit/components/DeveloperAccess.spec.ts
  auth-web/tests/unit/components/ExistingAPIKeys.spec.ts
Labels: enhancement, WIP

#1805 Changes to create a sandbox pay account when API key is generated first time for sandbox
  auth-api/src/auth_api/config.py
  auth-api/src/auth_api/services/api_gateway.py
  auth-api/tests/unit/api/test_org_api_keys.py
Labels: enhancement

#1806 BC Registry: Change of Account Name#9561
  auth-web/src/assets/scss/overrides.scss
  auth-web/src/components/auth/account-settings/account-info/AccountDetails.vue
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/components/auth/account-settings/account-info/AccountMailingAddress.vue
Labels: enhancement, WIP

#1809 removed create button
  auth-web/src/components/auth/account-settings/advance-settings/DeveloperAccess.vue
Labels: skip-changelog

#1808 BC Registry: Change of Account Name#9561
  auth-web/src/components/auth/account-settings/account-info/AccountDetails.vue
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/components/auth/common/AccountBusinessType.vue
  auth-web/src/components/auth/common/AccountBusinessTypePicker.vue
  auth-web/src/components/auth/mixins/AccountMixin.vue
Labels: enhancement

#1810 Changes to authorization for api gw key authorization.
  auth-api/src/auth_api/services/authorization.py
Labels: skip-changelog

#1811 UX for 9561 and 7071 | reverted mdi icon version
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/src/assets/scss/base.scss
  auth-web/src/components/auth/account-settings/account-info/AccountDetails.vue
  auth-web/src/components/auth/account-settings/advance-settings/ExistingAPIKeys.vue
  auth-web/src/components/auth/common/AccountBusinessType.vue
  auth-web/src/components/auth/common/AccountLoginOptionPicker.vue
  auth-web/src/views/auth/AccountSettings.vue
Labels: skip-changelog

#1812 Fixing issue with authorization for api gw users
  auth-api/src/auth_api/services/authorization.py
  auth-api/src/auth_api/utils/user_context.py
Labels: skip-changelog

#1813 Fixing message in q_cli for lockAccount message.
  .github/workflows/account-mailer-cd.yml
  .github/workflows/account-mailer-ci.yml
  .github/workflows/activity-log-listener-cd.yml
  .github/workflows/activity-log-listener-ci.yml
  .github/workflows/business-events-listener-cd.yml
  .github/workflows/business-events-listener-ci.yml
  .github/workflows/events-listener-cd.yml
  .github/workflows/events-listener-ci.yml
  queue_services/events-listener/q_cli.py
  queue_services/events-listener/src/events_listener/config.py
Labels: bug

#1814 Unit test 9561
  auth-web/src/components/auth/account-settings/account-info/AccountDetails.vue
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/components/auth/account-settings/account-info/AccountMailingAddress.vue
  auth-web/src/components/auth/common/AccountBusinessType.vue
  auth-web/tests/unit/components/AccountDetails.spec.ts
  auth-web/tests/unit/components/AccountMailingAddress.spec.ts
Labels: skip-changelog

#1815 cc should be sent as direct pay
  auth-web/src/store/modules/org.ts
Labels: skip-changelog

#1820 Accept Invite and Upload Affidavit for new Admin#9326
  auth-web/src/components/auth/BceidInviteLanding.vue
  auth-web/src/components/auth/account-settings/team-management/InviteUsersForm.vue
  auth-web/src/components/auth/create-account/non-bcsc/AffidavitDownload.vue
  auth-web/src/components/auth/mixins/NextPageMixin.vue
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/AcceptInviteLandingView.vue
  auth-web/src/views/auth/AcceptInviteView.vue
  auth-web/src/views/auth/TermsOfServiceView.vue
Labels: enhancement, WIP

#1818 Changes to invite BCeID admin
  auth-api/migrations/versions/09dd4ea64775_verified_user.py
  auth-api/src/auth_api/models/membership.py
  auth-api/src/auth_api/models/user.py
  auth-api/src/auth_api/services/invitation.py
  auth-api/src/auth_api/services/task.py
  auth-api/src/auth_api/utils/enums.py
  auth-api/tests/unit/api/test_invitation.py
  auth-api/tests/utilities/factory_scenarios.py
  queue_services/account-mailer/src/account_mailer/email_templates/business_invitation_email_for_bceid.html
  queue_services/activity-log-listener/src/activity_log_listener/config.py
Labels: enhancement

#1823 Fixing migration
  auth-api/migrations/versions/09dd4ea64775_verified_user.py
Labels: skip-changelog

#1821 Feature/9326
  auth-web/src/components/auth/create-account/UserProfileForm.vue
  auth-web/src/components/auth/create-account/non-bcsc/UploadAffidavitStep.vue
  auth-web/src/routes/router.ts
  auth-web/src/views/auth/create-account/non-bcsc/NonBcscAdminInviteSetupView.vue
  auth-web/tests/unit/views/NonBcscAdminInviteSetupView.spec.ts
Labels: enhancement, WIP

#1825 9439 - user name settings for staff send notification for affidavit r…
  auth-api/src/auth_api/services/org.py
Labels: bug

#1826 Bug/9439 jwttoken
  auth-api/src/auth_api/services/org.py
Labels: bug

#1827 Accept Invite and Upload Affidavit for new Admin#9326
  auth-web/src/components/auth/BceidInviteLanding.vue
  auth-web/src/components/auth/create-account/non-bcsc/AffidavitDownload.vue
  auth-web/src/components/auth/mixins/NextPageMixin.vue
  auth-web/src/locales/en.json
  auth-web/src/models/Organization.ts
  auth-web/src/routes/router.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/AcceptInviteLandingView.vue
  auth-web/src/views/auth/AcceptInviteView.vue
  auth-web/src/views/auth/TermsOfServiceView.vue
  auth-web/src/views/auth/create-account/non-bcsc/NonBcscAdminInviteSetupView.vue
Labels: enhancement, WIP

#1829 Changes to support pending staff review for memberships
  auth-api/src/auth_api/utils/roles.py
Labels: skip-changelog

#1822 Changes to key generation to point to different endpoint based on key environment
  auth-api/src/auth_api/config.py
  auth-api/src/auth_api/services/api_gateway.py
Labels: skip-changelog

#1830 Accept Invite and Upload Affidavit for new Admin#9326
  auth-web/src/components/auth/create-account/non-bcsc/AffidavitDownload.vue
  auth-web/src/components/auth/mixins/NextPageMixin.vue
  auth-web/src/locales/en.json
  auth-web/src/routes/index.ts
  auth-web/src/views/auth/AcceptInviteLandingView.vue
  auth-web/src/views/auth/PendingApprovalView.vue
Labels: skip-changelog

#1832 Admin invite email content fix
  queue_services/account-mailer/src/account_mailer/email_templates/business_invitation_email_for_bceid.html
Labels: skip-changelog
