Repository bcgov/sbc-auth, pull requests merged in 2021-01, with the labels that each got.

#1230 [entity5722] Update Account Type Information
  auth-web/src/components/auth/create-account/AccountTypeSelector.vue
Labels: enhancement

#1245 5721-Update User Terms.
  auth-api/migrations/versions/c10f494d7e10_add_tos_verion_4.py
  auth-api/tests/unit/api/test_documents.py
  auth-api/tests/unit/models/test_documents.py
  auth-api/tests/unit/services/test_documents.py
  auth-api/tests/unit/services/test_user.py
  auth-web/src/components/auth/common/TermsOfUse.vue
  auth-web/src/routes/router.ts
  auth-web/src/views/auth/PADTermsAndConditionsView.vue
  auth-web/src/views/auth/TermsOfServiceView.vue
Labels: enhancement

#1249 Generate and Download Invoice - Online Banking
  auth-web/src/components/pay/PaymentCard.vue
  auth-web/src/locales/en.json
  auth-web/src/services/payment.services.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/views/pay/PaymentView.vue
Labels: enhancement

#1248 User in-app notification of suspended account
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/src/models/Organization.ts
  auth-web/src/routes/index.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/views/auth/account-freeze/AccountFreezeView.vue
  auth-web/tests/unit/views/AccountFreezeView.spec.ts
Labels: enhancement

#1254 Dev to Test
  auth-api/migrations/versions/c10f494d7e10_add_tos_verion_4.py
  auth-api/tests/unit/api/test_documents.py
  auth-api/tests/unit/models/test_documents.py
  auth-api/tests/unit/services/test_documents.py
  auth-api/tests/unit/services/test_user.py
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/src/components/auth/common/TermsOfUse.vue
  auth-web/src/components/auth/create-account/AccountTypeSelector.vue
  auth-web/src/components/pay/PaymentCard.vue
  auth-web/src/locales/en.json
  auth-web/src/models/Organization.ts
  auth-web/src/routes/index.ts
  auth-web/src/routes/router.ts
  auth-web/src/services/payment.services.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/views/auth/PADTermsAndConditionsView.vue
  auth-web/src/views/auth/TermsOfServiceView.vue
  auth-web/src/views/auth/account-freeze/AccountFreezeView.vue
  auth-web/src/views/pay/PaymentView.vue
  auth-web/tests/unit/views/AccountFreezeView.spec.ts
Labels: skip-changelog

#1250 [entity6010] Develop Static Price List Interface
  auth-web/src/routes/router.ts
  auth-web/src/views/auth/PriceListView.vue
Labels: feature

#1253 Adding permissions for pending affidavit review account
  auth-api/migrations/versions/0f310e71e51d_affidavit_pending_status_permissions.py
  auth-api/src/auth_api/services/permissions.py
  auth-web/package-lock.json
  auth-web/package.json
  docs/docs/api_contract/auth-api-1.0.0.yaml
Labels: bug

#1252 Added new events to publish staff related action emails
  auth-api/src/auth_api/config.py
  auth-api/src/auth_api/services/invitation.py
  auth-api/src/auth_api/services/membership.py
  auth-api/src/auth_api/utils/account_mailer.py
  auth-api/tests/conftest.py
  auth-api/tests/docker/docker-compose.yml
Labels: enhancement

#1255 Added new email templates
  auth-api/src/auth_api/utils/account_mailer.py
  queue_services/account-mailer/q_cli.py
  queue_services/account-mailer/src/account_mailer/email_templates/admin_removed_email.html
  queue_services/account-mailer/src/account_mailer/email_templates/team_modified_email.html
  queue_services/account-mailer/src/account_mailer/enums.py
  queue_services/account-mailer/src/account_mailer/worker.py
  queue_services/account-mailer/tests/integration/test_worker_queue.py
Labels: enhancement

#1257 adding nats 1pwd entry to auth-api
  .github/workflows/auth-api-cd.yml
Labels: skip-changelog

#1258 6010-Add fee schedule link to user terms and conditions.
  auth-api/migrations/versions/f7362101e761_add_fee_schedule_link.py
  auth-api/requirements.txt
Labels: enhancement

#1259 payment to continue instead of failing
  auth-web/src/views/pay/PaymentView.vue
Labels: skip-changelog

#1260 added edit and view for nsf account for admins
  auth-api/migrations/versions/b72d4946fb3c_added_view_edit_for_nsf_account.py
Labels: bug

#1264 Bank validation fix in the UI
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/src/components/auth/account-freeze/ReviewBankInformation.vue
  auth-web/src/views/pay/PaymentView.vue
  auth-web/tests/unit/components/AccountPaymentMethods.spec.ts
Labels: bug

#1262 Change PAD information
  auth-web/src/components/auth/account-freeze/ReviewBankInformation.vue
  auth-web/src/components/auth/common/PADInfoForm.vue
  auth-web/src/components/auth/common/PaymentMethods.vue
  auth-web/src/components/auth/common/TermsOfUseDialog.vue
  auth-web/tests/unit/components/PADInfoForm.spec.ts
Labels: enhancement

#1263 test deployment
  .github/workflows/auth-api-cd.yml
  auth-api/migrations/versions/b72d4946fb3c_added_view_edit_for_nsf_account.py
  auth-api/migrations/versions/f7362101e761_add_fee_schedule_link.py
  auth-api/requirements.txt
  auth-api/src/auth_api/services/user.py
  auth-api/tests/unit/services/test_user.py
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/src/components/auth/account-freeze/ReviewBankInformation.vue
  auth-web/src/components/auth/common/PADInfoForm.vue
  auth-web/src/components/auth/common/PaymentMethods.vue
  auth-web/src/components/auth/common/TermsOfUseDialog.vue
  auth-web/src/views/pay/PaymentView.vue
  auth-web/tests/unit/components/AccountPaymentMethods.spec.ts
  auth-web/tests/unit/components/PADInfoForm.spec.ts
Labels: bug, enhancement

#1267 [entity6010] Fixing Issue with Nav Bar showing on Price List View
  auth-web/src/routes/router.ts
Labels: skip-changelog

#1265 Name Request - Don't allow Online Banking for basic users for name r…
  auth-web/src/components/pay/PaymentCard.vue
  auth-web/src/models/invoice.ts
  auth-web/src/views/pay/PaymentView.vue
Labels: enhancement

#1266 Update config value and vaults setup.
  .github/workflows/auth-api-cd.yml
  auth-api/requirements.txt
  auth-api/src/auth_api/__init__.py
  auth-api/src/auth_api/config.py
  auth-api/src/auth_api/services/codes.py
  auth-api/src/auth_api/services/invitation.py
  auth-api/src/auth_api/services/keycloak.py
  auth-api/src/auth_api/services/queue_publisher.py
  auth-api/src/auth_api/services/user.py
  auth-api/vaults.json
Labels: devops

#1268 removing a wrong file which breaks product code schema
  auth-api/src/auth_api/schemas/product_code.py
Labels: skip-changelog

#1269 dev to test merge
  .github/workflows/auth-api-cd.yml
  auth-api/requirements.txt
  auth-api/src/auth_api/__init__.py
  auth-api/src/auth_api/config.py
  auth-api/src/auth_api/schemas/product_code.py
  auth-api/src/auth_api/services/codes.py
  auth-api/src/auth_api/services/invitation.py
  auth-api/src/auth_api/services/keycloak.py
  auth-api/src/auth_api/services/queue_publisher.py
  auth-api/src/auth_api/services/user.py
  auth-api/vaults.json
  auth-web/src/components/pay/PaymentCard.vue
  auth-web/src/models/invoice.ts
  auth-web/src/routes/router.ts
  auth-web/src/views/pay/PaymentView.vue
Labels: devops

#1271 Name Request - Don't allow Online Banking for basic users for name r…
  auth-web/src/components/pay/PaymentCard.vue
Labels: bug

#1270 5723: Changes to bank details hints and validation
  auth-api/src/auth_api/services/affiliation.py
  auth-web/src/components/auth/common/PADInfoForm.vue
Labels: enhancement

#1272 Clean up config values and vaults.json file.
  .github/workflows/account-mailer-cd.yml
  .github/workflows/account-mailer-ci.yml
  .github/workflows/auth-web-cd.yml
  .github/workflows/events-listener-cd.yml
  .github/workflows/notify-api&queue-cd.yml
  .github/workflows/status-api-cd.yml
  auth-api/devops/vaults.json
  notify-api/devops/vaults.json
  notify-api/requirements.txt
  notify-api/requirements/prod.txt
  queue_services/account-mailer/devops/vaults.json
  queue_services/account-mailer/src/account_mailer/config.py
  queue_services/account-mailer/src/account_mailer/worker.py
  queue_services/events-listener/devops/vaults.json
  queue_services/events-listener/src/events_listener/config.py
  queue_services/notify-queue/ops/vaults.json
  queue_services/notify-queue/requirements.txt
  queue_services/notify-queue/requirements/prod.txt
  status-api/devops/vaults.json
Labels: devops

#1275 Rename folder name.
  queue_services/notify-queue/devops/vaults.json
Labels: devops

#1273 staff level access made read only
  auth-api/migrations/versions/eaef1147f25c_permissions_for_frcr_review.py
  auth-api/src/auth_api/resources/org.py
  auth-api/src/auth_api/services/org.py
  auth-api/tests/unit/api/test_org.py
  auth-web/src/components/auth/account-freeze/ReviewBankInformation.vue
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
  auth-web/src/components/auth/account-settings/statement/StatementsSettings.vue
  auth-web/src/components/auth/common/AccountLoginOptionPicker.vue
  auth-web/src/components/auth/common/LinkedBCOLBanner.vue
  auth-web/src/components/auth/common/PADInfoForm.vue
  auth-web/src/components/auth/common/PaymentMethods.vue
  auth-web/src/components/auth/create-account/AccountTypeSelector.vue
  auth-web/src/directives/can.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/util/common-util.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/AccountSettings.vue
  docs/docs/api_contract/auth-api-1.0.0.yaml
Labels: Do Not Merge, enhancement

#1276 Merged to master
  .github/workflows/account-mailer-cd.yml
  .github/workflows/account-mailer-ci.yml
  .github/workflows/events-listener-cd.yml
  .github/workflows/notify-api&queue-cd.yml
  .github/workflows/status-api-cd.yml
  auth-api/devops/vaults.json
  auth-api/migrations/versions/eaef1147f25c_permissions_for_frcr_review.py
  auth-api/src/auth_api/resources/org.py
  auth-api/src/auth_api/services/affiliation.py
  auth-api/src/auth_api/services/org.py
  auth-api/tests/unit/api/test_org.py
  auth-web/src/components/auth/account-freeze/ReviewBankInformation.vue
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
  auth-web/src/components/auth/account-settings/statement/StatementsSettings.vue
  auth-web/src/components/auth/common/AccountLoginOptionPicker.vue
  auth-web/src/components/auth/common/LinkedBCOLBanner.vue
  auth-web/src/components/auth/common/PADInfoForm.vue
  auth-web/src/components/auth/common/PaymentMethods.vue
  auth-web/src/components/auth/create-account/AccountTypeSelector.vue
  auth-web/src/components/pay/PaymentCard.vue
  auth-web/src/directives/can.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/util/common-util.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/AccountSettings.vue
  docs/docs/api_contract/auth-api-1.0.0.yaml
  notify-api/devops/vaults.json
  notify-api/requirements.txt
  notify-api/requirements/prod.txt
  queue_services/account-mailer/devops/vaults.json
  queue_services/account-mailer/src/account_mailer/config.py
  queue_services/account-mailer/src/account_mailer/worker.py
  queue_services/events-listener/devops/vaults.json
  queue_services/events-listener/src/events_listener/config.py
  queue_services/notify-queue/devops/vaults.json
  queue_services/notify-queue/requirements.txt
  queue_services/notify-queue/requirements/prod.txt
  status-api/devops/vaults.json
Labels: skip-changelog

#1278 Update PAD info - Multiple admins
  auth-web/src/components/auth/common/PaymentMethods.vue
Labels: bug

#1280 Fixing typos
  auth-api/migrations/versions/eaef1147f25c_permissions_for_frcr_review.py
  auth-web/src/components/auth/common/AccountLoginOptionPicker.vue
  auth-web/src/util/constants.ts
Labels: skip-changelog

#1283 adding disabled for basic accounts
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
Labels: skip-changelog

#1285 Added check for incomplete profile
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/components/auth/manage-business/EntityManagement.vue
  auth-web/src/main.ts
  auth-web/src/routes/componentHooks.ts
Labels: enhancement

#1287 Account info UI for old Basic account
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
  auth-web/src/components/auth/account-settings/statement/StatementsSettings.vue
Labels: bug

#1286 added LD flags for enable upgrade downgrade
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/util/constants.ts
Labels: skip-changelog

#1282 [entity5490] UI Clean-up
  auth-web/src/components/pay/PaymentCard.vue
  auth-web/src/views/pay/PaymentView.vue
Labels: skip-changelog

#1290 Members need not to be blocked from navigating since they cant change…
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
Labels: bug

#1293 [entity5722] Remove Reference to Developer API
  auth-web/src/components/auth/create-account/AccountTypeSelector.vue
Labels: skip-changelog

#1292 5721-Update user terms and conditions.
  auth-api/migrations/versions/5f51253eeced_update_tos_version_4.py
  auth-api/requirements.txt
  auth-web/src/locales/en.json
Labels: bug

#1277 Update rocket chat url.
  auth-api/jenkins/dev.groovy
  auth-api/jenkins/prod.groovy
  auth-api/jenkins/test.groovy
  auth-web/jenkins/dev.groovy
  auth-web/jenkins/prod.groovy
  auth-web/jenkins/test.groovy
  notify-api/jenkins/dev.groovy
  notify-api/jenkins/prod.groovy
  notify-api/jenkins/test.groovy
  queue_services/account-mailer/jenkins/dev.groovy
  queue_services/account-mailer/jenkins/prod.groovy
  queue_services/account-mailer/jenkins/test.groovy
  queue_services/events-listener/jenkins/dev.groovy
  queue_services/events-listener/jenkins/prod.groovy
  queue_services/events-listener/jenkins/test.groovy
  queue_services/notify-queue/jenkins/dev.groovy
  queue_services/notify-queue/jenkins/prod.groovy
  queue_services/notify-queue/jenkins/test.groovy
  status-api/jenkins/dev.groovy
  status-api/jenkins/prod.groovy
  status-api/jenkins/test.groovy
Labels: devops

#1289 Changes for sending emails for online banking payments
  queue_services/account-mailer/src/account_mailer/email_templates/online_banking_over_payment.html
  queue_services/account-mailer/src/account_mailer/email_templates/online_banking_payment.html
  queue_services/account-mailer/src/account_mailer/email_templates/online_banking_under_payment.html
  queue_services/account-mailer/src/account_mailer/enums.py
  queue_services/account-mailer/src/account_mailer/worker.py
  queue_services/account-mailer/tests/integration/test_worker_queue.py
Labels: enhancement

#1294 dev to master
  .github/workflows/main-pr-check.yml
  .github/workflows/pr-label-check.yml
  auth-api/jenkins/dev.groovy
  auth-api/jenkins/prod.groovy
  auth-api/jenkins/test.groovy
  auth-api/migrations/versions/5f51253eeced_update_tos_version_4.py
  auth-api/requirements.txt
  auth-web/jenkins/dev.groovy
  auth-web/jenkins/prod.groovy
  auth-web/jenkins/test.groovy
  auth-web/src/components/auth/create-account/AccountTypeSelector.vue
  auth-web/src/locales/en.json
  notify-api/jenkins/dev.groovy
  notify-api/jenkins/prod.groovy
  notify-api/jenkins/test.groovy
  queue_services/account-mailer/jenkins/dev.groovy
  queue_services/account-mailer/jenkins/prod.groovy
  queue_services/account-mailer/jenkins/test.groovy
  queue_services/account-mailer/src/account_mailer/email_templates/online_banking_over_payment.html
  queue_services/account-mailer/src/account_mailer/email_templates/online_banking_payment.html
  queue_services/account-mailer/src/account_mailer/email_templates/online_banking_under_payment.html
  queue_services/account-mailer/src/account_mailer/enums.py
  queue_services/account-mailer/src/account_mailer/worker.py
  queue_services/account-mailer/tests/integration/test_worker_queue.py
  queue_services/events-listener/jenkins/dev.groovy
  queue_services/events-listener/jenkins/prod.groovy
  queue_services/events-listener/jenkins/test.groovy
  queue_services/notify-queue/jenkins/dev.groovy
  queue_services/notify-queue/jenkins/prod.groovy
  queue_services/notify-queue/jenkins/test.groovy
  status-api/jenkins/dev.groovy
  status-api/jenkins/prod.groovy
  status-api/jenkins/test.groovy
Labels: enhancement

#1296 Changes for sending emails for online banking payments.
  queue_services/account-mailer/src/account_mailer/email_templates/online_banking_over_payment.html
  queue_services/account-mailer/src/account_mailer/email_templates/online_banking_payment.html
  queue_services/account-mailer/src/account_mailer/email_templates/online_banking_under_payment.html
Labels: skip-changelog

#1297 Dev to Test
  queue_services/account-mailer/src/account_mailer/email_templates/online_banking_over_payment.html
  queue_services/account-mailer/src/account_mailer/email_templates/online_banking_payment.html
  queue_services/account-mailer/src/account_mailer/email_templates/online_banking_under_payment.html
Labels: skip-changelog

#1299 Commenting the cache code to initiate the value on every load.
  auth-web/src/util/config-helper.ts
Labels: skip-changelog

#1300 Dev to Test
  auth-web/src/util/config-helper.ts
Labels: skip-changelog

#1295 [entity6010] Update Price List Content
  auth-web/src/views/auth/PriceListView.vue
Labels: skip-changelog

#1298 [entity6167] Update Online Banking Payment Method Content
  auth-web/src/components/auth/common/PaymentMethods.vue
Labels: skip-changelog

#1302 fix for invitation flow breaking
  auth-web/src/App.vue
Labels: bug

#1303 dev to test merge
  auth-web/src/App.vue
  auth-web/src/components/auth/common/PaymentMethods.vue
  auth-web/src/views/auth/PriceListView.vue
Labels: devops

#1305 adding PAD_EDIT for nsf accounts
  auth-api/migrations/versions/a490b2db8b13_added_pad_edit_for_nsf_accounts.py
Labels: bug

#1308 bug fix for invitations
  auth-web/src/App.vue
  auth-web/src/components/auth/mixins/NextPageMixin.vue
Labels: bug

#1311 Fix for mandatory address flag
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/components/auth/manage-business/EntityManagement.vue
  auth-web/src/util/constants.ts
Labels: skip-changelog

#1316 suspended account staff
  auth-web/src/components/auth/staff/account-management/StaffSuspendedAccountsTable.vue
Labels: skip-changelog

#1310 CFS is down when PAD is created #5440
  queue_services/account-mailer/q_cli.py
  queue_services/account-mailer/src/account_mailer/email_templates/pad_setup_failed.html
  queue_services/account-mailer/src/account_mailer/enums.py
  queue_services/account-mailer/src/account_mailer/worker.py
  queue_services/account-mailer/tests/integration/test_worker_queue.py
Labels: enhancement

#1321 Staff - See NSF Banner in Account Views #5093
  auth-web/src/components/auth/account-freeze/AccountOverview.vue
  auth-web/src/components/auth/common/AccountSuspendAlert.vue
  auth-web/src/components/auth/staff/account-management/StaffSuspendedAccountsTable.vue
  auth-web/src/models/invoice.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/views/auth/AccountSettings.vue
  auth-web/tests/unit/components/AccountOverview.spec.ts
  auth-web/tests/unit/components/AccountSuspendAlert.spec.ts
  auth-web/tests/unit/components/StaffSuspendedAccountsTable.spec.ts
  auth-web/tests/unit/views/AccountFreezeUnlockView.spec.ts
Labels: enhancement

#1320 table renaming added
  auth-api/migrations/versions/be4475027882_rename_tables.py
  auth-api/src/auth_api/models/account_login_options.py
  auth-api/src/auth_api/models/account_payment_settings.py
  auth-api/src/auth_api/models/affidavit.py
  auth-api/src/auth_api/models/affidavit_status.py
  auth-api/src/auth_api/models/affiliation.py
  auth-api/src/auth_api/models/base_model.py
  auth-api/src/auth_api/models/contact.py
  auth-api/src/auth_api/models/contact_link.py
  auth-api/src/auth_api/models/corp_type.py
  auth-api/src/auth_api/models/entity.py
  auth-api/src/auth_api/models/invitation.py
  auth-api/src/auth_api/models/invitation_membership.py
  auth-api/src/auth_api/models/invitation_type.py
  auth-api/src/auth_api/models/invite_status.py
  auth-api/src/auth_api/models/membership.py
  auth-api/src/auth_api/models/membership_status_code.py
  auth-api/src/auth_api/models/membership_type.py
  auth-api/src/auth_api/models/org.py
  auth-api/src/auth_api/models/org_settings.py
  auth-api/src/auth_api/models/org_status.py
  auth-api/src/auth_api/models/org_type.py
  auth-api/src/auth_api/models/payment_type.py
  auth-api/src/auth_api/models/product_code.py
  auth-api/src/auth_api/models/product_role_code.py
  auth-api/src/auth_api/models/product_subscription.py
  auth-api/src/auth_api/models/product_subscription_role.py
  auth-api/src/auth_api/models/product_type_code.py
  auth-api/src/auth_api/models/user.py
  auth-api/src/auth_api/models/user_status_code.py
  auth-api/src/auth_api/schemas/__init__.py
  auth-api/src/auth_api/schemas/membership_types.py
  auth-api/tests/unit/api/test_codes.py
  auth-api/tests/unit/services/test_codes.py
  auth-web/src/services/staff.services.ts
  auth-web/src/services/user.services.ts
Labels: enhancement

#1322 5912 account name should be unique - API
  auth-api/migrations/versions/dfd28e2b34a3_add_bcol_account_name_to_org.py
  auth-api/src/auth_api/models/org.py
  auth-api/src/auth_api/schemas/schemas/org_response.json
  auth-api/src/auth_api/services/org.py
  auth-api/tests/unit/api/test_org.py
  auth-api/tests/unit/services/test_org.py
  auth-api/tests/utilities/factory_scenarios.py
Labels: enhancement

#1324 changes column desc to description
  auth-api/migrations/versions/b23a04d2e331_desc_to_description.py
  auth-api/migrations/versions/be4475027882_rename_tables.py
  auth-api/src/auth_api/models/base_model.py
  auth-api/src/auth_api/models/product_role_code.py
  auth-api/src/auth_api/schemas/basecode_type.py
  auth-api/src/auth_api/schemas/corp_type.py
  auth-api/src/auth_api/schemas/membership_types.py
  auth-api/src/auth_api/services/products.py
  auth-api/tests/unit/models/test_affiliation.py
  auth-api/tests/unit/models/test_invitation.py
  auth-api/tests/unit/models/test_membership.py
  auth-api/tests/unit/models/test_org.py
  auth-api/tests/utilities/factory_utils.py
Labels: enhancement

#1323 duplicate name check added for bcol
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/components/auth/common/PaymentMethods.vue
  auth-web/src/components/auth/create-account/AccountCreatePremium.vue
  auth-web/src/models/Organization.ts
  auth-web/src/store/modules/org.ts
Labels: enhancement

#1325 validation corrected ; show account name for premium as well
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/components/auth/create-account/AccountCreatePremium.vue
Labels: bug

#1330 6185 Update link for Benefit Company static page on business registry app
  auth-web/src/views/auth/home/DecideBusinessView.vue
  auth-web/src/views/auth/home/HomeView.vue
Labels: enhancement

#1329 Feature/6043
  queue_services/account-mailer/q_cli.py
  queue_services/account-mailer/src/account_mailer/email_templates/paymanet_pending.html
  queue_services/account-mailer/src/account_mailer/enums.py
  queue_services/account-mailer/src/account_mailer/worker.py
  queue_services/account-mailer/tests/integration/test_worker_queue.py
Labels: enhancement
