Repository bcgov/sbc-auth, pull requests merged in 2021-03, with the labels that each got.

#1387 progress bar style
  auth-web/src/assets/scss/layout.scss
  auth-web/src/views/pay/PaymentReturnView.vue
  auth-web/src/views/pay/PaymentView.vue
Labels: skip-changelog

#1389 Dev to Test
  auth-web/src/assets/scss/layout.scss
  auth-web/src/views/pay/PaymentReturnView.vue
  auth-web/src/views/pay/PaymentView.vue
Labels: skip-changelog

#1393 comment generate passcode menu for 6277 Prod move
  auth-web/src/views/auth/staff/IncorporationSearchResultView.vue
Labels: skip-changelog

#1392 Feature/6472 frontend
  auth-api/src/auth_api/models/suspension_reason_code.py
  auth-api/src/auth_api/schemas/org.py
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/components/auth/staff/account-management/StaffAccountManagement.vue
  auth-web/src/components/auth/staff/account-management/StaffSuspendedAccountsTable.vue
  auth-web/src/locales/en.json
  auth-web/src/models/Code.ts
  auth-web/src/models/Organization.ts
  auth-web/src/services/codes.service.ts
  auth-web/src/services/org.services.ts
  auth-web/src/store/index.ts
  auth-web/src/store/modules/codes.ts
  auth-web/src/store/modules/org.ts
  auth-web/tests/unit/components/AccountInfo.spec.ts
  auth-web/tests/unit/services/codes.service.spec.ts
Labels: WIP, enhancement

#1395 Changes for removing product role codes and adding ppr authorizations
  auth-api/migrations/versions/69a7e464fef3_product_role_changes.py
  auth-api/requirements.txt
  auth-api/src/auth_api/models/__init__.py
  auth-api/src/auth_api/models/product_code.py
  auth-api/src/auth_api/models/product_role_code.py
  auth-api/src/auth_api/models/product_subscription.py
  auth-api/src/auth_api/models/product_subscription_role.py
  auth-api/src/auth_api/models/views/authorization.py
  auth-api/src/auth_api/resources/org_authorizations.py
  auth-api/src/auth_api/schemas/product_subscription.py
  auth-api/src/auth_api/schemas/product_subscription_roles.py
  auth-api/src/auth_api/schemas/schemas/org_product_subscriptions_response.json
  auth-api/src/auth_api/services/authorization.py
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/products.py
  auth-api/tests/unit/api/test_account.py
  auth-api/tests/unit/api/test_org_authorisations.py
  auth-api/tests/unit/models/views/test_authorization.py
  auth-api/tests/unit/services/test_authorization.py
  auth-api/tests/unit/services/test_membership.py
  auth-api/tests/unit/services/test_org.py
  auth-api/tests/utilities/factory_utils.py
Labels: enhancement

#1399 Sending the invite to create an Ministry Account#6598
  auth-web/src/components/auth/staff/account-management/StaffCreateAccountModal.vue
Labels: skip-changelog

#1397 changes for GOVM accounts
  auth-api/email_templates/govm_business_invitation_email.html
  auth-api/migrations/versions/d5b5eb2e8dd0_added_branch_name.py
  auth-api/src/auth_api/exceptions/errors.py
  auth-api/src/auth_api/models/org.py
  auth-api/src/auth_api/schemas/schemas/org.json
  auth-api/src/auth_api/services/invitation.py
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/utils/enums.py
  auth-api/tests/unit/api/test_org.py
  auth-api/tests/unit/services/test_org.py
  auth-api/tests/utilities/factory_scenarios.py
  auth-web/public/config/configuration.json
Labels: enhancement

#1403 Feature/6598 4
  auth-web/src/components/auth/staff/SetupGovmAccountForm.vue
  auth-web/src/components/auth/staff/account-management/StaffCreateAccountModal.vue
  auth-web/src/routes/router.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/staff/SetupGovmAccountView.vue
  auth-web/tests/unit/components/SetupGovmAccountForm.spec.ts
  auth-web/tests/unit/components/StaffCreateAccountModal.spec.ts
  auth-web/tests/unit/views/SetupGovmAccountView.spec.ts
Labels: skip-changelog

#1404 dev to test
  auth-web/src/components/auth/staff/SetupGovmAccountForm.vue
  auth-web/src/components/auth/staff/account-management/StaffCreateAccountModal.vue
  auth-web/src/routes/router.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/staff/SetupGovmAccountView.vue
  auth-web/tests/unit/components/SetupGovmAccountForm.spec.ts
  auth-web/tests/unit/components/StaffCreateAccountModal.spec.ts
  auth-web/tests/unit/views/SetupGovmAccountView.spec.ts
Labels: skip-changelog

#1402 Bug - 6686 Entity dashboard bug fix
  auth-web/src/views/auth/staff/IncorporationSearchResultView.vue
Labels: bug, skip-changelog

#1405 Email invitation to government ministry account team member#6537 | l…
  auth-web/src/views/auth/AcceptInviteLandingView.vue
Labels: enhancement

#1408 fixing the alembic scripts
  auth-api/migrations/versions/69a7e464fef3_product_role_changes.py
  auth-api/migrations/versions/d5b5eb2e8dd0_added_branch_name.py
Labels: skip-changelog

#1406 6536 - Added email verification in invite members component
  auth-web/src/components/auth/account-settings/team-management/InviteUsersForm.vue
  auth-web/src/components/auth/account-settings/team-management/UserManagement.vue
  auth-web/src/components/auth/mixins/TeamManagementMixin.vue
  auth-web/src/locales/en.json
  auth-web/tests/unit/components/InviteUsersForm.spec.ts
Labels: enhancement

#1407 Login changes for govm account users
  auth-api/migrations/versions/4c6ca48245be_user_remove_roles.py
  auth-api/src/auth_api/models/documents.py
  auth-api/src/auth_api/models/user.py
  auth-api/src/auth_api/resources/user.py
  auth-api/src/auth_api/services/invitation.py
  auth-api/src/auth_api/services/keycloak.py
  auth-api/src/auth_api/services/user.py
  auth-api/src/auth_api/utils/constants.py
  auth-api/src/auth_api/utils/roles.py
  auth-api/tests/conftest.py
  auth-api/tests/docker/setup/demo-realm.json
  auth-api/tests/unit/api/test_invitation.py
  auth-api/tests/unit/api/test_user.py
  auth-api/tests/unit/models/test_invitation.py
  auth-api/tests/unit/models/test_user.py
  auth-api/tests/unit/services/test_keycloak.py
  auth-api/tests/unit/services/test_user.py
  auth-api/tests/utilities/factory_scenarios.py
  auth-api/tests/utilities/factory_utils.py
Labels: enhancement

#1411 payment cancel error title
  auth-web/src/components/pay/common/PaymentErrorMessage.vue
Labels: skip-changelog

#1410 display issue
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/components/auth/staff/account-management/StaffAccountManagement.vue
Labels: skip-changelog

#1416 6426 Give BC Registries and Online Services Staff the ability to support suspended accounts.
  auth-api/src/auth_api/resources/org.py
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/components/auth/staff/account-management/StaffAccountManagement.vue
  auth-web/src/util/constants.ts
  auth-web/tests/unit/components/AccountInfo.spec.ts
Labels: enhancement

#1421 changes for approved status for govm first user
  auth-api/src/auth_api/services/invitation.py
  auth-api/tests/unit/services/test_invitation.py
Labels: skip-changelog

#1417 Feature/6472 new UI behaviour
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/tests/unit/components/AccountInfo.spec.ts
Labels: skip-changelog

#1424 6746-Two fields appearing with same information for staff
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
Labels: bug

#1423 Feature/5716 pdf template
  queue_services/account-mailer/src/account_mailer/email_processors/pad_confirmation.py
  queue_services/account-mailer/src/account_mailer/email_templates/common/style.html
  queue_services/account-mailer/src/account_mailer/pdf_templates/common/bc_logo_img.html
  queue_services/account-mailer/src/account_mailer/pdf_templates/common/bc_registry_logo_img.html
  queue_services/account-mailer/src/account_mailer/pdf_templates/common/fonts.html
  queue_services/account-mailer/src/account_mailer/worker.py
Labels: enhancement

#1420 Clean Up Tasks to Support Government Ministry Accounts
  auth-web/src/components/auth/mixins/NextPageMixin.vue
  auth-web/src/util/constants.ts
Labels: skip-changelog

#1426 6746-Adjust layout.
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
Labels: bug

#1427 Auth dev to test
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/components/auth/mixins/NextPageMixin.vue
  auth-web/src/util/constants.ts
Labels: skip-changelog

#1428 Feature/5716 typo correction
  queue_services/account-mailer/src/account_mailer/pdf_templates/common/fonts.html
Labels: feature, skip-changelog

#1429 Feature/6472 add suspensionreason in alert banner
  auth-web/src/components/auth/common/AccountSuspendAlert.vue
Labels: enhancement, skip-changelog

#1430 Fix for bceid users missing public role
  auth-api/src/auth_api/resources/user.py
Labels: bug

#1432 Fixing issue with staff users getting added to gov account group
  auth-api/src/auth_api/resources/user.py
  auth-api/src/auth_api/services/keycloak.py
Labels: skip-changelog

#1434 Changing status from PENDING_AFFIDAVIT_REVIEW to generic PENDING_STAFF_REVIEW
  auth-api/migrations/versions/2d71e7d7cc18_removed_pending_affidavit_review.py
  auth-api/requirements.txt
  auth-api/requirements/prod.txt
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/permissions.py
  auth-api/src/auth_api/utils/enums.py
  auth-api/src/auth_api/utils/roles.py
  auth-api/tests/unit/api/test_org.py
  auth-api/tests/unit/services/test_affidavit.py
  auth-api/tests/unit/services/test_org.py
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/src/components/auth/mixins/NextPageMixin.vue
  auth-web/src/routes/index.ts
  auth-web/src/store/modules/staff.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/staff/ReviewAccountView.vue
Labels: enhancement

#1435 6220 UI changes
  auth-web/src/components/auth/manage-business/EntityManagement.vue
  auth-web/src/components/auth/manage-business/PasscodeResetOptionsModal.vue
  auth-web/src/locales/en.json
  auth-web/src/models/Organization.ts
  auth-web/src/views/auth/staff/IncorporationSearchResultView.vue
  auth-web/tests/unit/views/PasscodeResetOptionsModal.spec.ts
Labels: WIP, enhancement

#1438 Incorrect screen displayed for user/coordinator for suspended account
  auth-web/src/store/modules/org.ts
Labels: bug

#1440 Incorrect screen displayed for user/coordinator for suspended account…
  auth-web/src/store/modules/org.ts
Labels: bug

#1441 Changes for publishing reset passcode email
  auth-api/src/auth_api/services/entity.py
  auth-api/src/auth_api/services/invitation.py
  auth-api/src/auth_api/utils/account_mailer.py
  auth-api/tests/unit/api/test_invitation.py
  auth-api/tests/utilities/factory_scenarios.py
Labels: enhancement

#1436 Feature/6706
  auth-web/src/components/auth/common/GLPaymentForm.vue
  auth-web/src/components/auth/create-account/AccountCreateBasic.vue
  auth-web/src/components/auth/create-account/GovmContactInfoForm.vue
  auth-web/src/components/auth/create-account/GovmPaymentMethodSelector.vue
  auth-web/src/components/auth/create-account/ProductPackages.vue
  auth-web/src/models/Organization.ts
  auth-web/src/routes/router.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/views/auth/create-account/GovmAccountSetupView.vue
  auth-web/tests/unit/components/GLPaymentForm.spec.ts
  auth-web/tests/unit/components/GovmContactInfoForm.spec.ts
  auth-web/tests/unit/components/GovmPaymentMethodSelector.spec.ts
  auth-web/tests/unit/components/ProductPackages.spec.ts
  auth-web/tests/unit/views/GovmAccountSetupView.spec.ts
Labels: enhancement

#1446 6220-reset passcode-backend.
  auth-api/src/auth_api/resources/org.py
  auth-api/src/auth_api/services/affiliation.py
  auth-api/src/auth_api/services/entity.py
  auth-api/tests/unit/services/test_affiliation.py
  auth-api/tests/unit/services/test_entity.py
  auth-api/tests/unit/services/test_org.py
Labels: enhancement

#1450 Ministry Account Email invite and IDIR login #6704
  auth-web/src/components/auth/staff/SetupAccountForm.vue
  auth-web/src/components/auth/staff/SetupGovmAccountForm.vue
  auth-web/src/routes/router.ts
  auth-web/src/views/auth/staff/SetupAccountSuccessView.vue
Labels: enhancement

#1449 Update KNP templates.
  devops/openshift/templates/knp-nats.yaml
  devops/openshift/templates/knp.yaml
  devops/openshift/templates/nsp.yaml
Labels: devops

#1442 Feature/6703
  auth-web/src/components/auth/manage-business/PasscodeResetOptionsModal.vue
  auth-web/src/locales/en.json
  auth-web/src/models/business.ts
  auth-web/src/views/auth/staff/GeneratePasscodeView.vue
  auth-web/src/views/auth/staff/IncorporationSearchResultView.vue
  auth-web/tests/unit/views/GeneratePasscodeView.spec.ts
  auth-web/tests/unit/views/PasscodeResetOptionsModal.spec.ts
Labels: WIP, enhancement

#1447 changes for org update for govm accounts
  auth-api/requirements.txt
  auth-api/src/auth_api/exceptions/errors.py
  auth-api/src/auth_api/models/org.py
  auth-api/src/auth_api/resources/org.py
  auth-api/src/auth_api/schemas/schemas/distribution_code.json
  auth-api/src/auth_api/schemas/schemas/org.json
  auth-api/src/auth_api/schemas/schemas/org_product_subscription.json
  auth-api/src/auth_api/schemas/schemas/payment_info.json
  auth-api/src/auth_api/services/invitation.py
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/products.py
  auth-api/src/auth_api/utils/roles.py
  auth-api/tests/unit/api/test_org.py
  auth-api/tests/unit/services/test_org.py
  auth-api/tests/utilities/factory_scenarios.py
Labels: skip-changelog

#1453 Prime Contact create the request for Ministry Government Account #6706
  auth-web/src/components/auth/common/GLPaymentForm.vue
  auth-web/src/components/auth/create-account/AccountCreateBasic.vue
  auth-web/src/models/Organization.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/views/auth/create-account/GovmAccountSetupView.vue
Labels: enhancement

#1451 Send passcode reset email
  queue_services/account-mailer/q_cli.py
  queue_services/account-mailer/requirements.txt
  queue_services/account-mailer/src/account_mailer/email_processors/common_mailer.py
  queue_services/account-mailer/src/account_mailer/email_templates/reset_passcode.html
  queue_services/account-mailer/src/account_mailer/enums.py
  queue_services/account-mailer/src/account_mailer/worker.py
  queue_services/account-mailer/tests/integration/test_worker_queue.py
Labels: enhancement

#1452 6220 UI changes to consume remove affiliations API
  auth-api/src/auth_api/resources/org.py
  auth-api/src/auth_api/services/affiliation.py
  auth-api/tests/unit/api/test_org.py
  auth-api/tests/utilities/factory_scenarios.py
  auth-web/src/components/auth/manage-business/EntityManagement.vue
  auth-web/src/components/auth/manage-business/PasscodeResetOptionsModal.vue
  auth-web/src/locales/en.json
  auth-web/src/models/Organization.ts
  auth-web/src/services/org.services.ts
  auth-web/src/store/modules/business.ts
  auth-web/tests/unit/views/PasscodeResetOptionsModal.spec.ts
Labels: WIP, enhancement

#1456 Prime Contact create the request for Ministry Government Account #6706
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/src/components/auth/create-account/AccountCreateBasic.vue
  auth-web/src/components/auth/create-account/GovmContactInfoForm.vue
  auth-web/src/components/auth/mixins/NextPageMixin.vue
  auth-web/src/locales/en.json
  auth-web/src/models/Organization.ts
  auth-web/src/routes/index.ts
  auth-web/src/routes/router.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/AcceptInviteView.vue
  auth-web/src/views/auth/create-account/GovmAccountCreationSuccessView.vue
  auth-web/src/views/auth/create-account/GovmAccountSetupView.vue
Labels: enhancement

#1458 invitation flow needs resync of token
  auth-api/src/auth_api/services/products.py
  auth-web/src/components/auth/create-account/GovmContactInfoForm.vue
  auth-web/src/components/auth/mixins/NextPageMixin.vue
  auth-web/src/routes/router.ts
  auth-web/src/views/auth/AcceptInviteLandingView.vue
  auth-web/src/views/auth/AcceptInviteView.vue
Labels: enhancement

#1463 Feature/6220 bug fix
  auth-web/src/views/auth/staff/StaffDashboardView.vue
Labels: skip-changelog

#1462 6703 staff reset passcode - API
  auth-api/src/auth_api/resources/entity.py
  auth-api/src/auth_api/schemas/schemas/entity.json
  auth-api/src/auth_api/services/entity.py
  auth-api/tests/unit/api/test_entity.py
  auth-api/tests/utilities/factory_scenarios.py
  status-api/requirements.txt
Labels: enhancement

#1464 Feature/6703 integration
  auth-web/src/locales/en.json
  auth-web/src/models/business.ts
  auth-web/src/services/business.services.ts
  auth-web/src/store/modules/business.ts
  auth-web/src/views/auth/staff/GeneratePasscodeView.vue
  auth-web/src/views/auth/staff/IncorporationSearchResultView.vue
Labels: enhancement

#1465 6703 - Merge DEV to Master for TEST push
  auth-api/src/auth_api/resources/entity.py
  auth-api/src/auth_api/schemas/schemas/entity.json
  auth-api/src/auth_api/services/entity.py
  auth-api/tests/unit/api/test_entity.py
  auth-api/tests/utilities/factory_scenarios.py
  auth-web/src/locales/en.json
  auth-web/src/models/business.ts
  auth-web/src/services/business.services.ts
  auth-web/src/store/modules/business.ts
  auth-web/src/views/auth/staff/GeneratePasscodeView.vue
  auth-web/src/views/auth/staff/IncorporationSearchResultView.vue
  auth-web/src/views/auth/staff/StaffDashboardView.vue
  status-api/requirements.txt
Labels: enhancement

#1466 Fix for duplicate accounts for staff
  auth-api/src/auth_api/services/invitation.py
  auth-api/src/auth_api/services/user.py
Labels: skip-changelog

#1468 6220-Update entity.py
  auth-api/src/auth_api/services/affiliation.py
  auth-api/src/auth_api/services/authorization.py
  auth-api/src/auth_api/services/entity.py
  auth-api/tests/unit/api/test_org.py
  auth-api/tests/unit/services/test_affiliation.py
Labels: enhancement

#1472 success page
  auth-web/src/views/auth/PendingApprovalView.vue
Labels: skip-changelog

#1471 Bug/6897
  auth-web/src/components/auth/account-settings/team-management/InviteUsersForm.vue
  auth-web/src/util/common-util.ts
Labels: bug, skip-changelog

#1473 email validation test
  auth-web/src/util/common-util.ts
Labels: skip-changelog

#1474 dev to test
  auth-web/src/components/auth/account-settings/team-management/InviteUsersForm.vue
  auth-web/src/util/common-util.ts
  auth-web/src/views/auth/PendingApprovalView.vue
Labels: skip-changelog

#1476 Broken links on landing page#6903
  auth-web/src/components/auth/home/BcscPanel.vue
  auth-web/src/views/auth/home/HomeView.vue
Labels: bug

#1477 dev to test
  auth-web/src/components/auth/home/BcscPanel.vue
  auth-web/src/views/auth/home/HomeView.vue
Labels: skip-changelog

#1470 Adding productSettings to user settings endpoint
  auth-api/requirements.txt
  auth-api/src/auth_api/models/user_settings.py
  auth-api/src/auth_api/schemas/schemas/user_settings_response.json
  auth-api/src/auth_api/schemas/user_settings.py
  auth-api/src/auth_api/services/user_settings.py
  auth-api/tests/unit/api/test_user_settings.py
  queue_services/account-mailer/src/account_mailer/enums.py
  queue_services/account-mailer/src/account_mailer/worker.py
Labels: enhancement

#1478 LD flag for Govm account invite
  auth-web/src/components/auth/staff/account-management/StaffAccountManagement.vue
  auth-web/src/util/constants.ts
Labels: skip-changelog

#1479 dev to test
  auth-api/requirements.txt
  auth-api/src/auth_api/models/user_settings.py
  auth-api/src/auth_api/schemas/schemas/user_settings_response.json
  auth-api/src/auth_api/schemas/user_settings.py
  auth-api/src/auth_api/services/user_settings.py
  auth-api/tests/unit/api/test_user_settings.py
  auth-web/src/components/auth/staff/account-management/StaffAccountManagement.vue
  auth-web/src/util/constants.ts
  queue_services/account-mailer/src/account_mailer/enums.py
  queue_services/account-mailer/src/account_mailer/worker.py
Labels: skip-changelog

#1481 made loginsource optional
  auth-web/src/routes/router.ts
Labels: bug

#1480 [entity6912] Business Registry Page Log In Updates
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/src/plugins/vuetify.ts
  auth-web/src/views/auth/home/HomeView.vue
Labels: enhancement

#1475 Adding int type for org_id in routes
  auth-api/src/auth_api/resources/__init__.py
  auth-api/src/auth_api/resources/account.py
  auth-api/src/auth_api/resources/org.py
  auth-api/src/auth_api/resources/user.py
  auth-api/tests/conftest.py
  auth-api/tests/unit/api/test_entity.py
Labels: skip-changelog
