Repository bcgov/sbc-auth, pull requests merged in 2021-05, with the labels that each got.

#1580 6895 - UI implementation
  auth-api/src/auth_api/resources/org.py
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/task.py
  auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
  auth-web/src/components/auth/common/GLPaymentForm.vue
  auth-web/src/components/auth/common/PaymentMethods.vue
  auth-web/src/components/auth/staff/account-management/StaffRejectedAccountsTable.vue
  auth-web/src/components/auth/staff/review-task/PaymentInformation.vue
  auth-web/src/components/auth/staff/review-task/ProductFee.vue
  auth-web/src/locales/en.json
  auth-web/src/models/Organization.ts
  auth-web/src/services/payment.services.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/store/modules/staff.ts
  auth-web/src/util/config-helper.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/staff/ReviewAccountView.vue
  auth-web/tests/unit/components/PaymentInformation.spec.ts
  auth-web/tests/unit/components/PaymentMethods.spec.ts
  auth-web/tests/unit/components/ProductFee.spec.ts
Labels: WIP, enhancement

#1585 list all product in product page
  auth-web/src/services/org.services.ts
Labels: skip-changelog

#1588 added encoding since idir usernames has backslashes
  auth-web/src/services/user.services.ts
Labels: skip-changelog

#1584 fixes for activity log (#1574)
  auth-api/migrations/versions/1a46fdc4d630_permissons_for_activity_log.py
  auth-api/migrations/versions/3c89ccb6bb32_actor_changed_to_actor_id.py
  auth-api/migrations/versions/a0f0a77dc77f_merge_heads.py
  auth-api/src/auth_api/models/activity_log.py
  auth-api/src/auth_api/resources/acitivity_log.py
  auth-api/src/auth_api/schemas/activity_log.py
  auth-api/src/auth_api/services/activity_log.py
  auth-api/src/auth_api/services/activity_log_publisher.py
  auth-api/src/auth_api/services/affiliation.py
  auth-api/src/auth_api/services/entity.py
  auth-api/tests/unit/api/test_activity_log.py
  auth-api/tests/utilities/factory_scenarios.py
  auth-api/tests/utilities/factory_utils.py
  auth-web/src/util/common-util.ts
  auth-web/src/util/constants.ts
  queue_services/activity-log-listener/Makefile
  queue_services/activity-log-listener/devops/vaults.json
  queue_services/activity-log-listener/src/activity_log_listener/config.py
  queue_services/activity-log-listener/src/activity_log_listener/worker.py
Labels: enhancement

#1576 Passcode Reset: Activity log#6702
  auth-web/src/assets/scss/overrides.scss
  auth-web/src/components/auth/account-settings/activity-log/ActivityLog.vue
  auth-web/src/locales/en.json
  auth-web/src/models/activityLog.ts
  auth-web/src/routes/router.ts
  auth-web/src/services/activityLog.services.ts
  auth-web/src/store/index.ts
  auth-web/src/store/modules/activityLog.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/AccountSettings.vue
  auth-web/tests/unit/components/ActivityLog.spec.ts
Labels: enhancement

#1583 Provide access to BCOL Vital Stats user If they had access before
  auth-api/migrations/versions/31ec16d4f1e9_product_migration_for_vs.py
  auth-api/migrations/versions/cdb2148334d3_.py
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/products.py
  auth-api/src/auth_api/utils/constants.py
  auth-api/tests/unit/api/test_activity_log.py
  auth-api/tests/unit/api/test_org.py
  docs/api-key-postman/API-GW-ACCOUNTS-DEV.json
  docs/api-key-postman/api-gw-account-keys.json
Labels: enhancement

#1590 GL info is not loading on user login first time
  auth-api/migrations/versions/e777dd2575e2_merge_heads.py
  auth-api/migrations/versions/f8f82c74f1fc_permissons_for_product_package.py
  auth-web/src/components/auth/account-settings/product/ProductPackage.vue
  auth-web/src/components/auth/common/GLPaymentForm.vue
  auth-web/src/util/common-util.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/AccountSettings.vue
Labels: bug

#1591 Fixed the repo links
  queue_services/activity-log-listener/requirements.txt
  queue_services/activity-log-listener/requirements/repo-libraries.txt
Labels: skip-changelog

#1586 Feature/6116 move to mailer account
  auth-api/src/auth_api/services/invitation.py
  auth-api/src/auth_api/services/membership.py
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/products.py
  auth-api/src/auth_api/services/task.py
  auth-api/src/auth_api/services/user.py
  auth-api/tests/unit/api/test_task.py
  auth-api/tests/unit/services/test_invitation.py
  auth-api/tests/unit/services/test_org.py
  queue_services/account-mailer/requirements.txt
  queue_services/account-mailer/src/account_mailer/email_templates/admin_notification_email.html
  queue_services/account-mailer/src/account_mailer/email_templates/business_invitation_email.html
  queue_services/account-mailer/src/account_mailer/email_templates/business_invitation_email_for_bceid.html
  queue_services/account-mailer/src/account_mailer/email_templates/dirsearch_business_invitation_email.html
  queue_services/account-mailer/src/account_mailer/email_templates/govm_approved_notification.html
  queue_services/account-mailer/src/account_mailer/email_templates/govm_business_invitation_email.html
  queue_services/account-mailer/src/account_mailer/email_templates/govm_member_invitation_email.html
  queue_services/account-mailer/src/account_mailer/email_templates/membership_approved_notification_email.html
  queue_services/account-mailer/src/account_mailer/email_templates/membership_approved_notification_email_for_bceid.html
  queue_services/account-mailer/src/account_mailer/email_templates/nonbcsc_org_approved_notification_email.html
  queue_services/account-mailer/src/account_mailer/email_templates/nonbcsc_org_rejected_notification_email.html
  queue_services/account-mailer/src/account_mailer/email_templates/otp_authenticator_reset_notification_email.html
  queue_services/account-mailer/src/account_mailer/email_templates/prod_package_approved_notification.html
  queue_services/account-mailer/src/account_mailer/email_templates/prod_package_rejected_notification.html
  queue_services/account-mailer/src/account_mailer/email_templates/role_changed_notification_email.html
  queue_services/account-mailer/src/account_mailer/email_templates/staff_review_account_email.html
  queue_services/account-mailer/src/account_mailer/enums.py
  queue_services/account-mailer/src/account_mailer/worker.py
Labels: WIP, enhancement

#1593 subject modifications
  auth-api/src/auth_api/services/membership.py
  queue_services/account-mailer/src/account_mailer/email_templates/prod_package_rejected_notification.html
  queue_services/account-mailer/src/account_mailer/enums.py
  queue_services/account-mailer/src/account_mailer/worker.py
Labels: WIP, enhancement

#1594 GOVM review page
  auth-web/src/components/auth/staff/review-task/AccountAdministrator.vue
  auth-web/src/components/auth/staff/review-task/ProductFee.vue
  auth-web/src/store/modules/org.ts
  auth-web/src/views/auth/staff/ReviewAccountView.vue
Labels: bug

#1595 updated wordings
  auth-web/src/components/auth/account-settings/product/ProductPackage.vue
  auth-web/src/views/auth/create-account/GovmAccountSetupView.vue
  auth-web/tests/unit/components/ProductPackage.spec.ts
Labels: skip-changelog

#1596 6116 - merge to master for TEST
  auth-api/src/auth_api/services/invitation.py
  auth-api/src/auth_api/services/membership.py
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/products.py
  auth-api/src/auth_api/services/task.py
  auth-api/src/auth_api/services/user.py
  auth-api/tests/unit/api/test_task.py
  auth-api/tests/unit/services/test_invitation.py
  auth-api/tests/unit/services/test_org.py
  auth-web/src/components/auth/account-settings/product/ProductPackage.vue
  auth-web/src/components/auth/staff/review-task/AccountAdministrator.vue
  auth-web/src/components/auth/staff/review-task/ProductFee.vue
  auth-web/src/store/modules/org.ts
  auth-web/src/views/auth/create-account/GovmAccountSetupView.vue
  auth-web/src/views/auth/staff/ReviewAccountView.vue
  auth-web/tests/unit/components/ProductPackage.spec.ts
  queue_services/account-mailer/requirements.txt
  queue_services/account-mailer/src/account_mailer/email_templates/admin_notification_email.html
  queue_services/account-mailer/src/account_mailer/email_templates/business_invitation_email.html
  queue_services/account-mailer/src/account_mailer/email_templates/business_invitation_email_for_bceid.html
  queue_services/account-mailer/src/account_mailer/email_templates/dirsearch_business_invitation_email.html
  queue_services/account-mailer/src/account_mailer/email_templates/govm_approved_notification.html
  queue_services/account-mailer/src/account_mailer/email_templates/govm_business_invitation_email.html
  queue_services/account-mailer/src/account_mailer/email_templates/govm_member_invitation_email.html
  queue_services/account-mailer/src/account_mailer/email_templates/membership_approved_notification_email.html
  queue_services/account-mailer/src/account_mailer/email_templates/membership_approved_notification_email_for_bceid.html
  queue_services/account-mailer/src/account_mailer/email_templates/nonbcsc_org_approved_notification_email.html
  queue_services/account-mailer/src/account_mailer/email_templates/nonbcsc_org_rejected_notification_email.html
  queue_services/account-mailer/src/account_mailer/email_templates/otp_authenticator_reset_notification_email.html
  queue_services/account-mailer/src/account_mailer/email_templates/prod_package_approved_notification.html
  queue_services/account-mailer/src/account_mailer/email_templates/prod_package_rejected_notification.html
  queue_services/account-mailer/src/account_mailer/email_templates/role_changed_notification_email.html
  queue_services/account-mailer/src/account_mailer/email_templates/staff_review_account_email.html
  queue_services/account-mailer/src/account_mailer/enums.py
  queue_services/account-mailer/src/account_mailer/worker.py
Labels: enhancement

#1597 GOVM TOS changes
  auth-api/migrations/versions/2eb11ab005d3_added_tos_for_idir.py
  auth-api/src/auth_api/config.py
  auth-api/src/auth_api/resources/documents.py
  auth-api/src/auth_api/services/invitation.py
  auth-api/src/auth_api/services/user.py
  auth-api/src/auth_api/utils/enums.py
  auth-web/src/components/auth/mixins/NextPageMixin.vue
  auth-web/src/views/auth/AcceptInviteView.vue
  auth-web/src/views/auth/TermsOfServiceView.vue
Labels: enhancement

#1598 BCOL Account - Payment Method not showing
  auth-web/src/components/auth/common/PaymentMethods.vue
  auth-web/src/util/config-helper.ts
  auth-web/src/views/auth/home/HomeView.vue
Labels: bug, enhancement

#1600 GovM approval mail fix
  auth-api/src/auth_api/services/org.py
Labels: bug, skip-changelog

#1601 GovM approval mail fix - merge to master
  auth-api/src/auth_api/services/org.py
Labels: bug, skip-changelog

#1602 Removed obsolete table - account_payment_settings
  auth-api/migrations/versions/959d8ff75e82_payment_change.py
  auth-api/migrations/versions/f5deb2ebf9a8_removed_deprecated_table.py
  auth-api/src/auth_api/models/__init__.py
  auth-api/src/auth_api/models/account_payment_settings.py
Labels: devops

#1604 7456 - Update BCOL refund template
  queue_services/account-mailer/src/account_mailer/email_templates/bcol_refund_request_email.html
Labels: enhancement, skip-changelog

#1606 Feature/6939
  auth-web/src/components/auth/account-settings/transaction/Transactions.vue
  auth-web/src/components/auth/account-settings/transaction/TransactionsDataTable.vue
  auth-web/src/store/modules/org.ts
  auth-web/tests/unit/components/Transactions.spec.ts
  auth-web/tests/unit/components/TransactionsDataTable.spec.ts
Labels: skip-changelog

#1608 Fixing product settings URL
  auth-api/src/auth_api/services/user_settings.py
  auth-api/tests/unit/api/test_user_settings.py
Labels: skip-changelog

#1607 Feature/7381
  auth-web/public/config/configuration.json
  auth-web/src/components/auth/create-account/AccountCreateBasic.vue
  auth-web/src/components/auth/create-account/AccountCreatePremium.vue
  auth-web/src/models/AutoComplete.ts
  auth-web/src/services/von.services.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/util/config-helper.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/OrgNameAutoComplete.vue
  auth-web/tests/unit/views/OrgNameAutoComplete.spec.ts
Labels: WIP, enhancement

#1616 changed wording
  auth-web/src/components/auth/account-settings/product/ProductPackage.vue
  auth-web/src/views/auth/AccountSettings.vue
  auth-web/src/views/auth/create-account/GovmAccountSetupView.vue
  auth-web/tests/unit/components/ProductPackage.spec.ts
Labels: skip-changelog

#1612 Adding partner on-boarding document
  docs/docs/api_contract/auth-api-1.0.0.yaml
Labels: skip-changelog

#1618 7443 name change
  auth-web/src/components/auth/common/AccountLoginOptionPicker.vue
  auth-web/src/locales/en.json
Labels: enhancement

#1615 Feature/6715
  auth-web/src/components/auth/account-settings/transaction/Transactions.vue
  auth-web/src/store/modules/org.ts
  auth-web/tests/unit/components/Statements.spec.ts
Labels: enhancement

#1621 Account Creation Process: VON API Integration style changes
  auth-web/src/assets/scss/overrides.scss
  auth-web/src/components/auth/create-account/AccountCreateBasic.vue
  auth-web/src/components/auth/create-account/AccountCreatePremium.vue
  auth-web/src/views/auth/OrgNameAutoComplete.vue
Labels: skip-changelog

#1619 GOVM account TOS
  auth-api/migrations/versions/c21389f4b51c_update_tos_for_idir.py
  auth-web/src/components/auth/common/TermsOfUse.vue
Labels: skip-changelog

#1622 Merge master with Dev for Test deploy
  auth-api/migrations/versions/c21389f4b51c_update_tos_for_idir.py
  auth-web/src/assets/scss/overrides.scss
  auth-web/src/components/auth/account-settings/product/ProductPackage.vue
  auth-web/src/components/auth/account-settings/transaction/Transactions.vue
  auth-web/src/components/auth/common/AccountLoginOptionPicker.vue
  auth-web/src/components/auth/common/TermsOfUse.vue
  auth-web/src/components/auth/create-account/AccountCreateBasic.vue
  auth-web/src/components/auth/create-account/AccountCreatePremium.vue
  auth-web/src/locales/en.json
  auth-web/src/store/modules/org.ts
  auth-web/src/views/auth/AccountSettings.vue
  auth-web/src/views/auth/OrgNameAutoComplete.vue
  auth-web/src/views/auth/create-account/GovmAccountSetupView.vue
  auth-web/tests/unit/components/ProductPackage.spec.ts
  auth-web/tests/unit/components/Statements.spec.ts
  docs/docs/api_contract/auth-api-1.0.0.yaml
Labels: skip-changelog

#1624 VON api show distinct org names
  auth-web/src/services/von.services.ts
  auth-web/src/views/auth/OrgNameAutoComplete.vue
Labels: enhancement

#1625 right align for total amount in transaction table
  auth-web/src/components/auth/account-settings/transaction/TransactionsDataTable.vue
Labels: skip-changelog

#1626 Login url fix for account mailer
  auth-web/tests/unit/views/OrgNameAutoComplete.spec.ts
  queue_services/account-mailer/src/account_mailer/auth_utils.py
  queue_services/account-mailer/src/account_mailer/config.py
Labels: bug, skip-changelog

#1628 6895 UI changes
  auth-web/src/components/auth/staff/review-task/AccountInformation.vue
  auth-web/src/components/auth/staff/review-task/ProductFee.vue
Labels: bug, skip-changelog

#1629 As a Ministry Account holder I want to review the Ministry Account Terms
  auth-api/migrations/versions/c21389f4b51c_update_tos_for_idir.py
  auth-web/src/locales/en.json
  auth-web/src/views/auth/TermsOfServiceView.vue
Labels: bug

#1623 Changes for refactoring Org creation and introduced user context
  auth-api/requirements/prod.txt
  auth-api/src/auth_api/resources/bcol_profiles.py
  auth-api/src/auth_api/resources/org.py
  auth-api/src/auth_api/services/__init__.py
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/validators/__init__.py
  auth-api/src/auth_api/services/validators/access_type.py
  auth-api/src/auth_api/services/validators/account_limit.py
  auth-api/src/auth_api/services/validators/bcol_credentials.py
  auth-api/src/auth_api/services/validators/duplicate_org_name.py
  auth-api/src/auth_api/services/validators/payment_type.py
  auth-api/src/auth_api/services/validators/validator_response.py
  auth-api/src/auth_api/utils/account_mailer.py
  auth-api/src/auth_api/utils/user_context.py
  auth-api/tests/conftest.py
  auth-api/tests/unit/api/test_bulk_user.py
  auth-api/tests/unit/api/test_org.py
  auth-api/tests/unit/api/test_task.py
  auth-api/tests/unit/api/test_user.py
  auth-api/tests/unit/services/test_affidavit.py
  auth-api/tests/unit/services/test_invitation.py
  auth-api/tests/unit/services/test_org.py
  auth-api/tests/unit/services/test_task.py
Labels: enhancement

#1632 Fixing the repo back to bcgov
  queue_services/account-mailer/requirements.txt
  queue_services/account-mailer/requirements/repo-libraries.txt
  queue_services/activity-log-listener/requirements.txt
  queue_services/activity-log-listener/requirements/repo-libraries.txt
  queue_services/events-listener/requirements.txt
  queue_services/events-listener/requirements/repo-libraries.txt
Labels: skip-changelog

#1634 added account number in account info screen
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/tests/unit/components/AccountInfo.spec.ts
Labels: enhancement, skip-changelog

#1633 7417 - pending tasks in asc order
  auth-api/src/auth_api/models/task.py
  auth-api/tests/unit/models/test_task.py
Labels: enhancement, skip-changelog

#1635 6734-refactor text for authentication screen
  auth-web/src/components/auth/account-settings/login-options/AccountSettingsLoginOption.vue
Labels: enhancement, skip-changelog

#1637 Changes for product model and related changes
  auth-api/migrations/versions/9b04140db7d3_product_code_flags.py
  auth-api/requirements/prod.txt
  auth-api/src/auth_api/config.py
  auth-api/src/auth_api/models/product_code.py
  auth-api/src/auth_api/resources/org_products.py
  auth-api/src/auth_api/schemas/__init__.py
  auth-api/src/auth_api/schemas/product_code.py
  auth-api/src/auth_api/schemas/schemas/org_product_subscriptions_response.json
  auth-api/src/auth_api/schemas/schemas/product.json
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/products.py
  auth-api/tests/unit/api/test_org_authorisations.py
  auth-api/tests/unit/api/test_org_products.py
  auth-api/tests/unit/api/test_product.py
  auth-api/tests/unit/api/test_task.py
  auth-api/tests/unit/services/test_org.py
  auth-api/tests/unit/services/test_product.py
  auth-api/tests/utilities/factory_scenarios.py
Labels: enhancement

#1640 7533 - Adding subscription as part org create payload
  auth-api/migrations/versions/9b04140db7d3_product_code_flags.py
  auth-api/src/auth_api/models/product_code.py
  auth-api/src/auth_api/services/org.py
  auth-api/tests/unit/api/test_org.py
  auth-api/tests/utilities/factory_scenarios.py
Labels: skip-changelog

#1642 7533
  auth-api/src/auth_api/utils/user_context.py
Labels: skip-changelog

#1644 Fixed wrong subject reference
  auth-api/src/auth_api/utils/account_mailer.py
Labels: bug

#1636 Action Based Account setup changes
  auth-web/src/components/auth/account-settings/product/ProductPackage.vue
  auth-web/src/components/auth/common/Product.vue
  auth-web/src/components/auth/common/ProductTOS.vue
  auth-web/src/components/auth/create-account/AccountTypeSelector.vue
  auth-web/src/components/auth/create-account/SelectProductService.vue
  auth-web/src/components/auth/staff/review-task/ProductFee.vue
  auth-web/src/locales/en.json
  auth-web/src/models/Organization.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/views/auth/create-account/AccountSetupView.vue
  auth-web/src/views/auth/create-account/GovmAccountSetupView.vue
  auth-web/tests/unit/components/AccountTypeSelector.spec.ts
  auth-web/tests/unit/components/Product.spec.ts
  auth-web/tests/unit/components/ProductFee.spec.ts
  auth-web/tests/unit/components/SelectProductService.spec.ts
Labels: WIP, enhancement

#1645 PAD confirmation mail/BCEID flow fix
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/task.py
  auth-api/src/auth_api/utils/user_context.py
Labels: bug

#1647 Feature/7533 2
  auth-web/src/locales/en.json
  auth-web/tests/unit/components/Product.spec.ts
Labels: skip-changelog
