Repository bcgov/sbc-auth, pull requests merged in 2021-09, with the labels that each got.

#1755 8610 - Dockerfile Node upgrade
  auth-web/Dockerfile
  auth-web/tests/unit/components/Transactions.spec.ts
Labels: enhancement

#1758 Updating API Spec to resolve the client library issue
  docs/docs/api_contract/auth-api-1.0.0.yaml
Labels: skip-changelog

#1759 Updating API Spec to resolve the client library issue
  docs/docs/api_contract/auth-api-1.0.0.yaml
Labels: skip-changelog

#1760 Updating API Spec to resolve the client library issue
  docs/docs/api_contract/auth-api-1.0.0.yaml
Labels: skip-changelog

#1761 Cleaning up API Spec to work for partners
  docs/docs/api_contract/auth-api-1.0.0.yaml
Labels: skip-changelog

#1762 Cleaning up API Spec to work for partners
  docs/docs/api_contract/auth-api-1.0.0.yaml
Labels: skip-changelog

#1764 Backend changes - 8664
  auth-api/migrations/versions/304705f06971_tasks_multiple_reasons.py
  auth-api/src/auth_api/models/task.py
  auth-api/src/auth_api/schemas/schemas/task_request.json
  auth-api/src/auth_api/services/affidavit.py
  auth-api/src/auth_api/services/task.py
  auth-api/tests/unit/api/test_task.py
  auth-api/tests/unit/services/test_task.py
  docker/docker-compose.yml
Labels: enhancement, WIP

#1766 8664 UI & Account mailer changes
  auth-api/src/auth_api/services/task.py
  auth-web/src/assets/scss/theme.scss
  auth-web/src/components/auth/staff/review-task/AccessRequestModal.vue
  auth-web/src/components/auth/staff/review-task/AccountStatus.vue
  auth-web/src/locales/en.json
  auth-web/src/services/task.services.ts
  auth-web/src/store/modules/codes.ts
  auth-web/src/store/modules/staff.ts
  auth-web/src/util/common-util.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/staff/ReviewAccountView.vue
  auth-web/tests/unit/components/AccessRequestModal.spec.ts
  auth-web/tests/unit/components/AccountStatus.spec.ts
  queue_services/account-mailer/src/account_mailer/email_processors/common_mailer.py
  queue_services/account-mailer/src/account_mailer/email_templates/resubmit_bceid_org.html
  queue_services/account-mailer/src/account_mailer/worker.py
Labels: enhancement

#1767 Changes for Rural Property Tax.
  auth-api/migrations/versions/385a6a9ae5a8_rpt.py
  auth-api/src/auth_api/utils/constants.py
Labels: enhancement

#1769 Fixing lint issues
  auth-api/src/auth_api/__init__.py
  auth-api/src/auth_api/config.py
  auth-api/src/auth_api/models/entity.py
  auth-api/src/auth_api/models/org.py
  auth-api/src/auth_api/models/user.py
  auth-api/src/auth_api/resources/entity.py
  auth-api/src/auth_api/resources/user.py
  auth-api/src/auth_api/schemas/base_schema.py
  auth-api/src/auth_api/services/affiliation.py
  auth-api/src/auth_api/services/authorization.py
  auth-api/src/auth_api/services/entity.py
  auth-api/src/auth_api/services/invitation.py
  auth-api/src/auth_api/services/keycloak.py
  auth-api/src/auth_api/services/membership.py
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/rest_service.py
  auth-api/src/auth_api/services/user.py
  auth-api/src/auth_api/utils/user_context.py
  auth-api/src/auth_api/utils/util_logging.py
Labels: skip-changelog

#1763 Allow multiple affiliation of same entity
  auth-api/src/auth_api/__init__.py
  auth-api/src/auth_api/models/affiliation.py
  auth-api/src/auth_api/models/views/authorization.py
  auth-api/src/auth_api/resources/org.py
  auth-api/src/auth_api/services/affiliation.py
  auth-api/src/auth_api/services/authorization.py
  auth-api/src/auth_api/services/org.py
  auth-api/tests/unit/api/test_account.py
  auth-api/tests/unit/api/test_user.py
  auth-api/tests/unit/services/test_affiliation.py
  auth-api/tests/unit/services/test_authorization.py
  auth-api/tests/unit/services/test_org.py
  auth-api/tests/unit/services/test_user.py
  auth-api/tests/utilities/factory_utils.py
Labels: enhancement

#1770 Adding affidavit approval days as config parameter
  auth-web/src/locales/en.json
  auth-web/src/util/config-helper.ts
  auth-web/src/views/auth/PendingApprovalView.vue
  auth-web/src/views/auth/create-account/non-bcsc/NonBcscAccountCreationSuccessView.vue
Labels: enhancement

#1779 9206 : CSO codes
  auth-api/migrations/versions/37dc988611c6_cso.py
  auth-api/src/auth_api/config.py
  auth-api/src/auth_api/services/invitation.py
Labels: enhancement

#1780 8412 : Fixing the account name in email body
  queue_services/account-mailer/src/account_mailer/email_templates/govm_member_invitation_email.html
Labels: bug

#1773 Feature/8605
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/src/main.ts
  auth-web/src/views/auth/staff/StaffDashboardView.vue
Labels: enhancement, WIP

#1782 Feature/8605-breadcrumb-changes
  auth-web/package-lock.json
  auth-web/public/config/configuration.json
  auth-web/src/shims-vue.d.ts
  auth-web/src/util/config-helper.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/staff/StaffDashboardView.vue
Labels: enhancement

#1783 8605 - feature flag implementation
  auth-web/src/components/auth/mixins/PaginationMixin.vue
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/staff/StaffDashboardView.vue
Labels: enhancement, skip-changelog
