Repository bcgov/sbc-auth, pull requests merged in 2021-06, with the labels that each got.

#1646 Feature/6921
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/src/locales/en.json
  auth-web/src/models/Organization.ts
  auth-web/src/models/user.ts
  auth-web/src/routes/router.ts
  auth-web/src/services/org.services.ts
  auth-web/src/services/user.services.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/store/modules/user.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/create-account/AccountSetupView.vue
  auth-web/src/views/auth/create-account/DuplicateAccountWarningView.vue
Labels: enhancement

#1648 Changes for showing pending invitations for create_accounts role, and gl for manage_gl_codes role.
  auth-web/src/components/auth/staff/account-management/StaffAccountManagement.vue
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/staff/StaffDashboardView.vue
Labels: enhancement

#1653 user settings sorting and updating header
  auth-web/src/store/modules/user.ts
  auth-web/src/views/auth/create-account/DuplicateAccountWarningView.vue
Labels: enhancement, skip-changelog

#1651 fix for link
  queue_services/account-mailer/src/account_mailer/email_templates/govm_approved_notification.html
  queue_services/account-mailer/src/account_mailer/email_templates/govm_rejected_notification.html
  queue_services/account-mailer/src/account_mailer/email_templates/nonbcsc_org_rejected_notification_email.html
Labels: bug, skip-changelog

#1649 Action Based Account setup changes#7533 product link
  auth-web/src/components/auth/common/Product.vue
  auth-web/src/components/auth/create-account/AccountTypeSelector.vue
  auth-web/src/components/auth/create-account/SelectProductService.vue
  auth-web/src/store/modules/org.ts
  auth-web/src/views/auth/create-account/non-bcsc/NonBcscAccountSetupView.vue
Labels: skip-changelog

#1655 Feature/6921-duplicate accounts view-page reload
  auth-web/src/views/auth/create-account/DuplicateAccountWarningView.vue
Labels: enhancement, skip-changelog

#1657 Action Based Account setup changes#7533 product link
  auth-web/src/views/auth/create-account/non-bcsc/NonBcscAccountSetupView.vue
Labels: skip-changelog

#1658 Feature/6921-handle-empty-org-contacts
  auth-web/src/views/auth/create-account/DuplicateAccountWarningView.vue
  auth-web/tests/unit/components/DuplicateAccountWarningView.spec.ts
Labels: enhancement, skip-changelog

#1660 Using the user_context to not pass around the token info.
  auth-api/src/auth_api/__init__.py
  auth-api/src/auth_api/models/base_model.py
  auth-api/src/auth_api/models/task.py
  auth-api/src/auth_api/models/user.py
  auth-api/src/auth_api/resources/account.py
  auth-api/src/auth_api/resources/acitivity_log.py
  auth-api/src/auth_api/resources/bulk_user.py
  auth-api/src/auth_api/resources/entity.py
  auth-api/src/auth_api/resources/invitation.py
  auth-api/src/auth_api/resources/notifications.py
  auth-api/src/auth_api/resources/org.py
  auth-api/src/auth_api/resources/org_authorizations.py
  auth-api/src/auth_api/resources/reset.py
  auth-api/src/auth_api/resources/task.py
  auth-api/src/auth_api/resources/user.py
  auth-api/src/auth_api/resources/user_settings.py
  auth-api/src/auth_api/services/activity_log.py
  auth-api/src/auth_api/services/activity_log_publisher.py
  auth-api/src/auth_api/services/affidavit.py
  auth-api/src/auth_api/services/affiliation.py
  auth-api/src/auth_api/services/authorization.py
  auth-api/src/auth_api/services/entity.py
  auth-api/src/auth_api/services/invitation.py
  auth-api/src/auth_api/services/keycloak.py
  auth-api/src/auth_api/services/membership.py
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/products.py
  auth-api/src/auth_api/services/reset.py
  auth-api/src/auth_api/services/task.py
  auth-api/src/auth_api/services/user.py
  auth-api/src/auth_api/services/validators/access_type.py
  auth-api/src/auth_api/services/validators/account_limit.py
  auth-api/src/auth_api/services/validators/bcol_credentials.py
  auth-api/src/auth_api/utils/account_mailer.py
  auth-api/src/auth_api/utils/user_context.py
  auth-api/tests/unit/api/test_invitation.py
  auth-api/tests/unit/api/test_org.py
  auth-api/tests/unit/api/test_task.py
  auth-api/tests/unit/api/test_user.py
  auth-api/tests/unit/api/test_user_settings.py
  auth-api/tests/unit/models/test_user.py
  auth-api/tests/unit/services/test_affidavit.py
  auth-api/tests/unit/services/test_affiliation.py
  auth-api/tests/unit/services/test_authorization.py
  auth-api/tests/unit/services/test_entity.py
  auth-api/tests/unit/services/test_invitation.py
  auth-api/tests/unit/services/test_keycloak.py
  auth-api/tests/unit/services/test_membership.py
  auth-api/tests/unit/services/test_org.py
  auth-api/tests/unit/services/test_reset.py
  auth-api/tests/unit/services/test_task.py
  auth-api/tests/unit/services/test_user.py
  auth-api/tests/unit/services/test_user_settings.py
  auth-api/tests/utilities/factory_scenarios.py
  auth-api/tests/utilities/factory_utils.py
Labels: enhancement

#1667 Feature/7782
  auth-web/src/components/auth/common/AccountBusinessType.vue
  auth-web/src/components/auth/create-account/AccountCreateBasic.vue
  auth-web/src/components/auth/create-account/AccountCreatePremium.vue
  auth-web/src/locales/en.json
  auth-web/src/models/Organization.ts
  auth-web/src/store/modules/codes.ts
  auth-web/src/store/modules/org.ts
  auth-web/tests/unit/components/AccountBusinessType.spec.ts
Labels: WIP, enhancement

#1672 Removing duplicate
  auth-api/migrations/versions/08e1d49dfa1a_business_type_and_size.py
Labels: skip-changelog

#1671 7587- Version 5 TOS content
  auth-api/migrations/versions/3818a89ddedf_add_tos_version_5.py
  auth-api/tests/unit/api/test_documents.py
  auth-api/tests/unit/models/test_documents.py
  auth-api/tests/unit/services/test_documents.py
  auth-api/tests/unit/services/test_user.py
  auth-api/tests/utilities/factory_utils.py
Labels: enhancement

#1673 Changing GL code validation to alphanumeric.
  auth-web/src/components/auth/common/GLPaymentForm.vue
Labels: bug

#1674 6852 - Changes for supporting ULC and CCC
  auth-api/migrations/versions/ca5c15ff55f0_.py
  auth-api/migrations/versions/d2cb317afb6e_new_corp_types.py
  auth-api/src/auth_api/utils/enums.py
Labels: enhancement

#1675 Changes to support CC and ULC in affiliation
  auth-api/src/auth_api/services/affiliation.py
Labels: skip-changelog

#1676 style for radio button
  auth-web/src/components/auth/common/AccountBusinessType.vue
Labels: skip-changelog

#1680 Feature/7782 validation fix
  auth-web/src/components/auth/common/AccountBusinessType.vue
Labels: skip-changelog

#1681 7782 - Reset org name on business type change
  auth-web/src/components/auth/common/AccountBusinessType.vue
  auth-web/tests/unit/components/AccountBusinessType.spec.ts
Labels: skip-changelog

#1683 Added a new decorator for role validation
  auth-api/src/auth_api/resources/org.py
  auth-api/src/auth_api/utils/role_validator.py
  auth-api/tests/unit/api/test_org.py
  auth-api/tests/utilities/factory_scenarios.py
Labels: bug

#1685 loading stepper css fix
  auth-web/src/assets/scss/base.scss
  auth-web/src/components/auth/common/AccountBusinessType.vue
Labels: skip-changelog

#1682 BCeID Affidavit: Staff Review Changes#7780
  auth-web/src/components/auth/staff/review-task/AccessRequestModal.vue
  auth-web/src/models/Code.ts
  auth-web/src/services/task.services.ts
  auth-web/src/store/modules/codes.ts
  auth-web/src/store/modules/staff.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/staff/ReviewAccountView.vue
  auth-web/tests/unit/components/AccessRequestModal.spec.ts
Labels: enhancement

#1684 Changes to include mailing address information for org
  auth-api/src/auth_api/schemas/contact.py
  auth-api/src/auth_api/schemas/org.py
  auth-api/src/auth_api/schemas/schemas/contact_response.json
  docs/docs/api_contract/auth-api-1.0.0.yaml
Labels: enhancement

#1688 7981 - Changing the supported NR types to config.
  auth-api/src/auth_api/config.py
  auth-api/src/auth_api/services/affiliation.py
Labels: enhancement

#1666 Client resubmit the Affidavit Info or update Account Info#7781
  auth-web/src/components/auth/common/AccountBusinessType.vue
  auth-web/src/components/auth/common/FileUploadPreview.vue
  auth-web/src/components/auth/create-account/AccountCreateBasic.vue
  auth-web/src/components/auth/create-account/AccountCreatePremium.vue
  auth-web/src/components/auth/create-account/AccountTypeSelector.vue
  auth-web/src/components/auth/create-account/PaymentMethodSelector.vue
  auth-web/src/components/auth/create-account/PremiumChooser.vue
  auth-web/src/components/auth/create-account/SelectProductService.vue
  auth-web/src/components/auth/create-account/UserProfileForm.vue
  auth-web/src/directives/displayMode.ts
  auth-web/src/main.ts
  auth-web/src/routes/router.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/store/modules/user.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/create-account/non-bcsc/NonBcscAccountSetupView.vue
  auth-web/tests/unit/components/AccountTypeSelector.spec.ts
  auth-web/tests/unit/components/PaymentMethodSelector.spec.ts
Labels: Do Not Merge, enhancement

#1690 Release to main merge
  auth-api/src/auth_api/config.py
  auth-api/src/auth_api/services/affiliation.py
Labels: skip-changelog

#1686 A few tests added
  auth-api/tests/unit/utils/test_role_validator.py
Labels: skip-changelog

#1693 few fixes on task related screens
  auth-api/src/auth_api/config.py
  auth-api/src/auth_api/models/task.py
  auth-api/src/auth_api/resources/task.py
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/task.py
  auth-api/tests/unit/api/test_task.py
  auth-api/tests/unit/models/test_task.py
  auth-api/tests/unit/services/test_task.py
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/src/components/auth/staff/account-management/StaffPendingAccountsTable.vue
  auth-web/src/components/auth/staff/account-management/StaffRejectedAccountsTable.vue
  auth-web/src/models/Task.ts
  auth-web/src/services/task.services.ts
  auth-web/src/store/modules/task.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/staff/ReviewAccountView.vue
Labels: skip-changelog

#1697 Remove symbol from AccoutBusinessType component
  auth-web/src/components/auth/common/AccountBusinessType.vue
Labels: skip-changelog

#1698 BCeID Affidavit: Staff Review Changes
  auth-web/src/components/auth/staff/account-management/StaffPendingAccountsTable.vue
  auth-web/src/components/auth/staff/review-task/AccessRequestModal.vue
  auth-web/src/views/auth/staff/ReviewAccountView.vue
Labels: skip-changelog

#1700 remove hide-details from select account type
  auth-web/src/components/auth/common/AccountBusinessType.vue
Labels: skip-changelog

#1699 Feature/7707 - Products And Services page implementation in Account Settings view
  auth-api/src/auth_api/utils/roles.py
  auth-web/src/components/auth/account-settings/product/ProductPackage.vue
  auth-web/src/components/auth/common/Product.vue
  auth-web/src/locales/en.json
  auth-web/src/store/modules/org.ts
  auth-web/tests/unit/components/Product.spec.ts
Labels: WIP, enhancement

#1701 Bug/7928
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/components/auth/common/ConfirmCancelButton.vue
  auth-web/src/store/modules/org.ts
Labels: bug

#1694 Changes for deactivate account
  auth-api/migrations/versions/3b485a23d057_deactivate_permissions.py
  auth-api/src/auth_api/exceptions/errors.py
  auth-api/src/auth_api/models/membership.py
  auth-api/src/auth_api/models/org.py
  auth-api/src/auth_api/resources/org.py
  auth-api/src/auth_api/services/affiliation.py
  auth-api/src/auth_api/services/membership.py
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/rest_service.py
  auth-api/src/auth_api/services/validators/duplicate_org_name.py
  auth-api/tests/unit/api/test_org.py
  auth-api/tests/unit/models/test_org.py
  auth-api/tests/unit/services/test_affiliation.py
  auth-api/tests/unit/services/test_org.py
  auth-api/tests/utilities/factory_scenarios.py
  auth-api/tests/utilities/factory_utils.py
Labels: enhancement

#1704 bug fix for delivery instructions
  auth-api/src/auth_api/schemas/schemas/mailing_address.json
  auth-web/src/store/modules/org.ts
Labels: bug, skip-changelog

#1705 7781 - pending staff review migration
  auth-api/migrations/versions/5397c5a5b0ca_staff_pending_status_permissions.py
Labels: bug, skip-changelog

#1706 account staff review fix
  auth-api/src/auth_api/models/task.py
  auth-api/src/auth_api/services/org.py
  auth-api/tests/unit/models/test_task.py
Labels: bug, skip-changelog

#1707 Deactivate Premium Account
  auth-web/src/assets/scss/overrides.scss
  auth-web/src/components/auth/account-deactivate/DeactivateCard.vue
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/locales/en.json
  auth-web/src/views/auth/AccountDeactivate.vue
Labels: skip-changelog

#1710 fix for on hold reason
  auth-api/src/auth_api/services/task.py
Labels: bug, skip-changelog

#1708 show login options in team members tab
  auth-api/migrations/versions/f55e4cc1aaaa_view_teammember_auth.py
  auth-web/src/components/auth/account-settings/team-management/MemberDataTable.vue
  auth-web/src/util/common-util.ts
  auth-web/src/util/constants.ts
Labels: enhancement

#1715 bceid_url
  auth-web/devops/vaults.json
Labels: bug, skip-changelog
