Repository bcgov/sbc-auth, pull requests merged in 2021-07, with the labels that each got.

#1709 Library upgrade and 1password keys integration.
  .github/workflows/notify-api-ci.yml
  .github/workflows/notify-queue-ci.yml
  notify-api/Makefile
  notify-api/devops/vaults.json
  notify-api/docs/dotenv_template
  notify-api/main.py
  notify-api/migrations/env.py
  notify-api/migrations/versions/0001_initial_tables.py
  notify-api/migrations/versions/0003_support_multiple_attachment.py
  notify-api/migrations/versions/0004_modify_file_bytes_column_type.py
  notify-api/requirements.txt
  notify-api/src/notify_api/core/jwt.py
  notify-api/src/notify_api/core/settings.py
  notify-api/src/notify_api/db/models/attachment.py
  notify-api/t1.txt
  notify-api/t2.txt
  notify-api/tests/conftest.py
  notify-api/tests/factories/attachment.py
  notify-api/tsecret.txt
  queue_services/notify-queue/Makefile
  queue_services/notify-queue/devops/vaults.json
  queue_services/notify-queue/requirements.txt
  queue_services/notify-queue/requirements/repo-libraries.txt
  queue_services/notify-queue/src/notify_service/config.py
Labels: devops

#1711 Remove unused code for account upgrade/downgrade/account name change…
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/src/components/auth/create-account/AccountCreateBasic.vue
  auth-web/src/components/auth/create-account/AccountCreatePremium.vue
  auth-web/src/components/auth/create-account/AccountTypeSelector.vue
  auth-web/src/components/auth/create-account/PremiumChooser.vue
  auth-web/src/components/auth/create-account/non-bcsc/UploadAffidavitStep.vue
  auth-web/src/routes/router.ts
  auth-web/src/services/org.services.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/create-account/AccountChangeSuccessView.vue
  auth-web/src/views/auth/create-account/AccountChangeView.vue
Labels: skip-changelog

#1712 Fixing issue type not set in user table
  auth-api/migrations/versions/9c58b78727c8_users_type.py
  auth-api/migrations/versions/9e4305679a5d_.py
  auth-api/src/auth_api/__init__.py
  auth-api/src/auth_api/models/user.py
  auth-api/src/auth_api/services/user.py
Labels: bug

#1717 fixed error with permissions
  auth-api/migrations/versions/3b485a23d057_deactivate_permissions.py
  auth-api/migrations/versions/f55e4cc1aaaa_view_teammember_auth.py
  auth-api/src/auth_api/models/product_code.py
  auth-api/tests/unit/api/test_permissions.py
Labels: bug

#1719 Fix issue with deactivate
  auth-api/src/auth_api/services/org.py
Labels: skip-changelog

#1713 Feature/7717 WIP
  auth-api/src/auth_api/resources/org.py
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/utils/enums.py
  auth-api/tests/unit/api/test_org.py
  auth-api/tests/unit/services/test_org.py
  auth-api/tests/utilities/factory_scenarios.py
Labels: WIP, enhancement

#1723 fix put org issue
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
Labels: bug, skip-changelog

#1724 Bug/8162
  auth-web/src/components/auth/staff/review-task/AccountInformation.vue
  auth-web/src/components/auth/staff/review-task/AccountStatus.vue
  auth-web/src/models/Task.ts
Labels: bug, skip-changelog

#1727 added branch name duplicate check
  auth-api/src/auth_api/services/org.py
  auth-api/tests/unit/api/test_bulk_user.py
  auth-api/tests/unit/api/test_org.py
Labels: skip-changelog

#1729 Fix for accessing getter
  auth-web/src/routes/index.ts
Labels: skip-changelog

#1731 Added redirect URI to TOS flow to support reupload affidavit flow
  auth-web/src/routes/index.ts
  auth-web/src/routes/router.ts
  auth-web/src/views/auth/TermsOfServiceView.vue
Labels: bug

#1733 8218: Deactivate account error messages
  auth-web/src/locales/en.json
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/AccountDeactivate.vue
Labels: enhancement

#1734 8226
  auth-api/src/auth_api/services/affidavit.py
  auth-api/src/auth_api/tracer.py
Labels: enhancement

#1735 Staff Dashboard: Pagination issue#8354
  auth-web/src/components/auth/staff/account-management/StaffActiveAccountsTable.vue
Labels: bug

#1737 bug fix for govm create
  auth-web/src/store/modules/org.ts
Labels: bug, skip-changelog
