Repository bcgov/sbc-auth, pull requests merged in 2021-08, with the labels that each got.

#1739 8266: Changes to match with schema changes (authAccountId -> accountId)
  auth-web/src/components/auth/account-settings/statement/StatementsSettings.vue
  auth-web/src/components/auth/account-settings/transaction/Transactions.vue
  auth-web/src/models/Organization.ts
  auth-web/src/models/statement.ts
Labels: enhancement

#1740 8266: Schema changes for new columns
  auth-api/migrations/versions/41ac4080a7ed_entity_changes.py
  auth-api/src/auth_api/models/entity.py
  auth-api/src/auth_api/schemas/schemas/business.json
Labels: enhancement

#1741 Business events listener queue service
  .github/workflows/business-events-listener-cd.yml
  .github/workflows/business-events-listener-ci.yml
  queue_services/business-events-listener/Dockerfile
  queue_services/business-events-listener/LICENSE
  queue_services/business-events-listener/MANIFEST.in
  queue_services/business-events-listener/Makefile
  queue_services/business-events-listener/README.md
  queue_services/business-events-listener/app.py
  queue_services/business-events-listener/devops/vaults.json
  queue_services/business-events-listener/logging.conf
  queue_services/business-events-listener/openshift/templates/bc.yaml
  queue_services/business-events-listener/openshift/templates/dc.yaml
  queue_services/business-events-listener/q_cli.py
  queue_services/business-events-listener/requirements.txt
  queue_services/business-events-listener/requirements/dev.txt
  queue_services/business-events-listener/requirements/prod.txt
  queue_services/business-events-listener/requirements/repo-libraries.txt
  queue_services/business-events-listener/scripts/verify_license_headers.sh
  queue_services/business-events-listener/setup.cfg
  queue_services/business-events-listener/setup.py
  queue_services/business-events-listener/src/business_events_listener/__init__.py
  queue_services/business-events-listener/src/business_events_listener/config.py
  queue_services/business-events-listener/src/business_events_listener/utils.py
  queue_services/business-events-listener/src/business_events_listener/version.py
  queue_services/business-events-listener/src/business_events_listener/worker.py
  queue_services/business-events-listener/tests/__init__.py
  queue_services/business-events-listener/tests/conftest.py
  queue_services/business-events-listener/tests/docker-compose.yml
  queue_services/business-events-listener/tests/integration/__init__.py
  queue_services/business-events-listener/tests/integration/test_worker_queue.py
  queue_services/business-events-listener/tests/integration/utils.py
Labels: enhancement, WIP

#1742 Changes to support NR purchased with no accounts
  queue_services/business-events-listener/src/business_events_listener/config.py
  queue_services/business-events-listener/src/business_events_listener/worker.py
  queue_services/business-events-listener/tests/integration/test_worker_queue.py
Labels: enhancement

#1745 improved the wordings
  queue_services/account-mailer/src/account_mailer/email_templates/resubmit_bceid_org.html
Labels: skip-changelog

#1751 Changes for consistent date format in UI and backend response.
  auth-api/src/auth_api/schemas/account_payment_settings.py
  auth-api/src/auth_api/schemas/activity_log.py
  auth-api/src/auth_api/schemas/affidavit.py
  auth-api/src/auth_api/schemas/affiliation.py
  auth-api/src/auth_api/schemas/base_schema.py
  auth-api/src/auth_api/schemas/contact.py
  auth-api/src/auth_api/schemas/contact_link.py
  auth-api/src/auth_api/schemas/documents.py
  auth-api/src/auth_api/schemas/entity.py
  auth-api/src/auth_api/schemas/invitation.py
  auth-api/src/auth_api/schemas/invitation_membership.py
  auth-api/src/auth_api/schemas/membership.py
  auth-api/src/auth_api/schemas/org.py
  auth-api/src/auth_api/schemas/product_subscription.py
  auth-api/src/auth_api/schemas/task.py
  auth-api/src/auth_api/schemas/user.py
  auth-api/src/auth_api/schemas/utils.py
  auth-api/src/auth_api/services/keycloak_user.py
  auth-api/tests/unit/api/test_user.py
  auth-web/src/components/auth/account-settings/team-management/InvitationsDataTable.vue
  auth-web/src/components/auth/account-settings/team-management/MemberDataTable.vue
  auth-web/src/components/auth/account-settings/transaction/TransactionsDataTable.vue
  auth-web/src/components/auth/common/DateRangeFilter.vue
  auth-web/src/util/common-util.ts
  auth-web/tests/unit/components/DateRangeFilter.spec.ts
  auth-web/tests/unit/util/common-util.spec.ts
Labels: enhancement
