Repository bcgov/sbc-auth, pull requests merged in 2022-12, with the labels that each got.

#2182 Update certifi.
  auth-api/requirements.txt
  jobs/notebook-report/requirements.txt
  jobs/notebook-report/requirements/prod.txt
  queue_services/account-mailer/requirements.txt
  queue_services/activity-log-listener/requirements.txt
  queue_services/business-events-listener/requirements.txt
  queue_services/events-listener/requirements.txt
  status-api/requirements.txt
Labels: dependencies, maintenance

#2184 ux update
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/src/components/auth/staff/review-task/AccountInformation.vue
Labels: enhancement

#2185 access type change ignore previous selected fees
  auth-web/src/views/auth/staff/ReviewAccountView.vue
Labels: bug

#2187 account create bceid govn bug fix
  auth-web/src/components/auth/create-account/AccountTypeSelector.vue
Labels: bug

#2191 14066/14562 - Minor tweaks for certified_by_name.
  auth-api/src/auth_api/services/affiliation.py
  auth-api/src/auth_api/version.py
Labels: bug
