Repository bcgov/sbc-auth, pull requests merged in 2022-01, with the labels that each got.

#1870 product approve call for gvn account
  auth-web/src/store/modules/staff.ts
  auth-web/src/views/auth/staff/ReviewAccountView.vue
Labels: bug

#1872 10255 - Bug fix for Account accessType change premium to GovN
  auth-web/src/components/auth/account-settings/account-info/AccountAccessType.vue
  auth-web/src/components/auth/account-settings/account-info/AccountInfo.vue
  auth-web/tests/unit/components/AccountAccessType.spec.ts
Labels: bug

#1871 Change the Prod Stat Fee and Service fee for Ministry and Non Ministr…
  auth-web/src/components/auth/account-settings/product/ProductPackage.vue
  auth-web/src/components/auth/common/ProductFeeSelector.vue
Labels: skip-changelog

#1873 access type pad error message UX alignment
  auth-web/src/components/auth/account-settings/account-info/AccountAccessType.vue
Labels: skip-changelog

#1877 10135 : Adding verified flag for BCeID affidavit approved users
  auth-api/migrations/versions/342ec8814181_update_verified_flag.py
  auth-api/src/auth_api/services/task.py
  auth-api/tests/unit/services/test_task.py
Labels: enhancement

#1879 Handle token expried exception and add devcontainer.
  notify-api/.devcontainer/Dockerfile
  notify-api/.devcontainer/db/docker_postgres_init.sql
  notify-api/.devcontainer/devcontainer.json
  notify-api/.devcontainer/docker-compose.yml
  notify-api/requirements.txt
  notify-api/src/notify_api/applications.py
  notify-api/src/notify_api/core/middleware.py
  notify-api/src/notify_api/db/crud/content.py
  notify-api/src/notify_api/db/models/content.py
  notify-api/src/notify_api/services/notify.py
  notify-api/tests/unit/crud/test_content.py
  notify-api/tests/unit/service/test_notify.py
Labels: devops

#1881 Added a page for bookmark.
  auth-web/src/assets/img/BCReg_Generic_Login_image.jpg
  auth-web/src/routes/index.ts
  auth-web/src/routes/router.ts
  auth-web/src/views/auth/BookmarkLoginView.vue
  auth-web/src/views/auth/SigninView.vue
Labels: devops

#1883 Change to send user for account admin approval for verified BCeID users
  auth-api/src/auth_api/services/invitation.py
  auth-api/src/auth_api/services/user.py
Labels: enhancement

#1882 Ability for Multiple Accounts for BCeID#10135
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/src/models/user.ts
  auth-web/src/routes/router.ts
  auth-web/src/views/auth/create-account/AccountSetupLanding.vue
  auth-web/src/views/auth/create-account/AccountSetupView.vue
  auth-web/src/views/auth/create-account/non-bcsc/NonBcscAccountSetupView.vue
Labels: enhancement, WIP

#1885 Ability for Multiple Accounts for BCeID#10135 | admin invite
  auth-web/src/views/auth/AcceptInviteView.vue
Labels: enhancement

#1884 10554 - handle multiple account for single idir
  auth-web/src/components/auth/create-account/AccountCreateBasic.vue
  auth-web/src/views/auth/AcceptInviteView.vue
Labels: enhancement

#1887 Switch bookmark page to common compoents login page.
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/src/App.vue
  auth-web/src/assets/img/BCReg_Generic_Login_image.jpg
  auth-web/src/routes/index.ts
  auth-web/src/routes/router.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/BookmarkLoginView.vue
  auth-web/src/views/auth/LoginView.vue
Labels: enhancement

#1891 Feature/10135 5
  auth-web/src/locales/en.json
  auth-web/src/views/auth/create-account/non-bcsc/NonBcscAccountSetupView.vue
Labels: skip-changelog

#1892 Adding get product for USER role as well
  auth-api/src/auth_api/services/products.py
Labels: skip-changelog

#1897 10851: Fixing key in refund email to transaction id
  queue_services/account-mailer/src/account_mailer/email_templates/bcol_refund_request_email.html
Labels: bug

#1900 6884 - Add get orgproducts permission for Staff View Account role
  auth-api/src/auth_api/resources/org_products.py
Labels: bug

#1901 added isLoading for the button to avoid double clicks
  auth-web/src/components/auth/account-settings/transaction/Transactions.vue
Labels: enhancement

#1898 Refactor to accomodate BCOL payment to GovN
  auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
  auth-web/src/components/auth/common/PaymentMethods.vue
Labels: bug

#1902 Account may change when navigating between UIs#6151
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/src/App.vue
  auth-web/src/components/auth/home/NameRequestButton.vue
  auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
  auth-web/src/components/auth/manage-business/EntityManagement.vue
  auth-web/src/views/auth/home/RequestNameView.vue
Labels: bug

#1903 Fixing find visible affiliations logic
  auth-api/src/auth_api/services/affiliation.py
  auth-api/src/auth_api/utils/enums.py
Labels: skip-changelog
