Repository bcgov/sbc-auth, pull requests merged in 2022-03, with the labels that each got.

#1921 added SP & GP
  auth-api/migrations/versions/cd89e8e61dec_sp_gp_corp_types.py
Labels: enhancement

#1923 updated auth api schema to include missing bcol and a few other attrs
  docs/docs/api_contract/auth-api-1.0.0.yaml
Labels: skip-changelog

#1922 Bcol Edit feature
  auth-api/src/auth_api/schemas/schemas/org.json
  auth-api/tests/docker/docker-compose.yml
  auth-api/tests/unit/api/test_org.py
  auth-web/package-lock.json
  auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
  auth-web/src/components/auth/common/LinkedBCOLBanner.vue
  auth-web/src/components/auth/common/PaymentMethods.vue
  auth-web/src/components/auth/create-account/BcolLogin.vue
Labels: enhancement

#1926 fix name getting updated on bcol updates
  auth-api/src/auth_api/services/org.py
Labels: skip-changelog

#1928 date format issue in statement
  auth-web/src/components/auth/common/SearchFilterInput.vue
Labels: bug

#1927 date format issue in statement
  auth-web/src/components/auth/common/SearchFilterInput.vue
Labels: bug

#1930 fix for UTC time being sent in invoice creation mail
  queue_services/account-mailer/src/account_mailer/config.py
  queue_services/account-mailer/src/account_mailer/email_processors/common_mailer.py
  queue_services/account-mailer/src/account_mailer/utils.py
  queue_services/account-mailer/tests/docker/docker-compose.yml
Labels: bug, enhancement

#1933 Added branch name and id to the search results
  auth-web/src/components/auth/staff/account-management/StaffActiveAccountsTable.vue
Labels: enhancement
