Repository bcgov/sbc-auth, pull requests merged in 2022-07, with the labels that each got.

#2011 12445 - Add in All for account-type. That way users can switch between Basic,…
  auth-web/src/components/auth/staff/account-management/StaffActiveAccountsTable.vue
  auth-web/src/models/Organization.ts
Labels: enhancement

#2010 12821 - Remove legacy service worker / PWA. (#2009)
  auth-web/Dockerfile
  auth-web/nginx.conf
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/src/registerServiceWorker.ts
  auth-web/src/service-worker.js
  auth-web/vue.config.js
Labels: devops

#2019 12755 - Unhandled SystemExit: 1 and various performance fixes
  auth-api/migrations/alembic.ini
  auth-api/migrations/versions/2229cbcaaa93_performance_indexes.py
  auth-api/src/auth_api/models/affiliation.py
  auth-api/src/auth_api/models/contact_link.py
  auth-api/src/auth_api/models/invitation_membership.py
  auth-api/src/auth_api/models/membership.py
  auth-api/src/auth_api/models/product_subscription.py
  auth-api/src/auth_api/resources/org.py
  auth-api/src/auth_api/schemas/base_schema.py
  auth-api/src/auth_api/services/affiliation.py
Labels: bug

#2018 10683 - Activity Log Changes
  auth-api/migrations/versions/1344cb533815_.py
  auth-api/requirements.txt
  auth-api/src/auth_api/config.py
  auth-api/src/auth_api/models/activity_log.py
  auth-api/src/auth_api/models/dataclass.py
  auth-api/src/auth_api/models/org.py
  auth-api/src/auth_api/schemas/base_schema.py
  auth-api/src/auth_api/schemas/schemas/org_response.json
  auth-api/src/auth_api/services/__init__.py
  auth-api/src/auth_api/services/activity_log.py
  auth-api/src/auth_api/services/activity_log_publisher.py
  auth-api/src/auth_api/services/affiliation.py
  auth-api/src/auth_api/services/entity.py
  auth-api/src/auth_api/services/invitation.py
  auth-api/src/auth_api/services/membership.py
  auth-api/src/auth_api/services/org.py
  auth-api/src/auth_api/services/products.py
  auth-api/src/auth_api/services/user.py
  auth-api/src/auth_api/utils/enums.py
  auth-api/tests/unit/api/test_activity_log.py
  auth-api/tests/unit/services/test_affidavit.py
  auth-api/tests/unit/services/test_affiliation.py
  auth-api/tests/unit/services/test_entity.py
  auth-api/tests/unit/services/test_invitation.py
  auth-api/tests/unit/services/test_membership.py
  auth-api/tests/unit/services/test_org.py
  auth-api/tests/unit/services/test_product.py
  auth-api/tests/utilities/factory_utils.py
  auth-web/src/components/auth/staff/account-management/StaffPendingAccountInvitationsTable.vue
  auth-web/src/components/auth/staff/account-management/StaffPendingAccountsTable.vue
  auth-web/src/components/auth/staff/account-management/StaffRejectedAccountsTable.vue
  auth-web/src/components/auth/staff/account-management/StaffSuspendedAccountsTable.vue
  queue_services/activity-log-listener/requirements.txt
  queue_services/activity-log-listener/src/activity_log_listener/version.py
  queue_services/activity-log-listener/src/activity_log_listener/worker.py
  queue_services/business-events-listener/README.md
  queue_services/business-events-listener/src/business_events_listener/worker.py
  queue_services/business-events-listener/tests/integration/test_worker_queue.py
Labels: enhancement

#2035 Turn Sentry Off by using SENTRY_ENABLE FLAG instead of SENTRY_DSN#12422
  auth-api/devops/vaults.json
  auth-api/docs/dotenv_template
  auth-api/src/auth_api/__init__.py
  auth-api/src/auth_api/config.py
  auth-web/src/main.ts
  queue_services/account-mailer/devops/vaults.json
  queue_services/account-mailer/src/account_mailer/config.py
  queue_services/activity-log-listener/devops/vaults.json
  queue_services/activity-log-listener/src/activity_log_listener/config.py
  queue_services/business-events-listener/devops/vaults.json
  queue_services/business-events-listener/src/business_events_listener/config.py
  queue_services/events-listener/devops/vaults.json
  queue_services/events-listener/src/events_listener/config.py
  status-api/config.py
  status-api/devops/vaults.json
  status-api/docs/dotenv_template
  status-api/requirements/prod.txt
  status-api/setup.cfg
  status-api/src/status_api/__init__.py
  status-api/src/status_api/resources/whatsnew.py
Labels: devops

#2045 Add in migration for site registry.
  auth-api/migrations/versions/3f79f6dcc58d_add_site_registry.py
Labels: enhancement

#2046 Version update.
  auth-api/src/auth_api/version.py
  auth-web/src/components/auth/staff/account-management/StaffActiveAccountsTable.vue
  auth-web/src/locales/en.json
  queue_services/account-mailer/requirements/dev.txt
  queue_services/account-mailer/src/account_mailer/version.py
  queue_services/activity-log-listener/requirements/dev.txt
  queue_services/activity-log-listener/src/activity_log_listener/version.py
  queue_services/business-events-listener/requirements/dev.txt
  queue_services/business-events-listener/src/business_events_listener/version.py
  queue_services/events-listener/requirements/dev.txt
  queue_services/events-listener/src/events_listener/version.py
Labels: dependencies
