Repository bcgov/sbc-auth, pull requests merged in 2022-11, with the labels that each got.

#2141 14128 - Fix to allow multiple affiliations for the same keycloak user (…
  auth-api/src/auth_api/models/views/authorization.py
Labels: bug

#2145 13333 - Allow multiple NR Affiliations
  auth-api/src/auth_api/services/affiliation.py
Labels: Do Not Merge

#2142 14113 Updates for BC/CC/ULC IAs
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/src/assets/scss/base.scss
  auth-web/src/components/auth/account-settings/product/ProductPackage.vue
  auth-web/src/components/auth/common/Product.vue
  auth-web/src/components/auth/common/ProductTOS.vue
  auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
  auth-web/src/components/auth/manage-business/EntityManagement.vue
  auth-web/src/components/auth/staff/review-task/ProductFee.vue
  auth-web/src/models/business.ts
  auth-web/src/store/modules/business.ts
  auth-web/src/store/modules/org.ts
  auth-web/src/util/constants.ts
  auth-web/src/views/auth/home/HomeView.vue
  auth-web/src/views/auth/home/IncorpOrRegisterView.vue
  auth-web/src/views/auth/staff/StaffDashboardView.vue
  auth-web/tests/unit/components/EntityManagement.spec.ts
  auth-web/tests/unit/components/Product.spec.ts
Labels: Do Not Merge

#2152 Minor tweak on the date/time calculation
  auth-api/src/auth_api/models/task.py
Labels: bug

#2162 Version update.
  auth-api/src/auth_api/version.py
Labels: devops

#2150 13205 - Fix for BC Online account creation, don't allow empty BCOL details. A…
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/src/components/auth/account-settings/payment/AccountPaymentMethods.vue
  auth-web/src/components/auth/common/LinkedBCOLBanner.vue
  auth-web/src/components/auth/common/PADInfoForm.vue
  auth-web/src/components/auth/common/PaymentMethods.vue
  auth-web/src/components/auth/create-account/AccountCreatePremium.vue
  auth-web/src/components/auth/create-account/AccountTypeSelector.vue
  auth-web/src/components/auth/create-account/BcolLogin.vue
  auth-web/src/components/auth/create-account/PaymentMethodSelector.vue
  auth-web/src/store/modules/org.ts
  auth-web/tsconfig.json
  auth-web/volar.config.js
Labels: bug
