Repository bcgov/sbc-auth, pull requests merged in 2022-05, with the labels that each got.

#1949 FAS library update to latest
  auth-web/package-lock.json
  auth-web/package.json
Labels: dependencies

#1948 9990 - Sentry error for Postal Code field exceeds length
  auth-api/Makefile
  auth-api/migrations/README
  auth-api/migrations/versions/da0ce563c18a_extend_postal_code.py
  auth-api/requirements.txt
  auth-api/requirements/prod.txt
  auth-api/src/auth_api/models/contact.py
  queue_services/account-mailer/requirements/prod.txt
  queue_services/activity-log-listener/requirements/prod.txt
  queue_services/business-events-listener/requirements/prod.txt
  queue_services/events-listener/requirements/prod.txt
Labels: bug

#1952 9990 - Dependency fixes
  auth-api/requirements.txt
  queue_services/account-mailer/requirements.txt
  queue_services/account-mailer/requirements/prod.txt
  queue_services/activity-log-listener/requirements.txt
  queue_services/activity-log-listener/requirements/prod.txt
  queue_services/business-events-listener/requirements.txt
  queue_services/business-events-listener/requirements/prod.txt
  queue_services/events-listener/requirements.txt
  queue_services/events-listener/requirements/prod.txt
Labels: bug

#1956 11883 - AUTH API: Ministry Invites - cannot resend expired invites
  auth-api/requirements.txt
  auth-api/src/auth_api/models/org.py
  auth-api/src/auth_api/services/org.py
  auth-api/tests/unit/api/test_org.py
  auth-api/tests/utilities/__init__.py
Labels: bug, enhancement

#1958 12222 - PAD Transactions UI Enhancement - Add Time to Transactions table.
  auth-web/src/components/auth/account-settings/transaction/TransactionsDataTable.vue
Labels: enhancement

#1957 12228 - Minor string tweaks for adding new products to the platform.
  auth-web/src/locales/en.json
Labels: enhancement

#1961 11900 - Minor check for govm Account for radio group.
  auth-web/src/components/auth/common/AccountBusinessType.vue
Labels: bug

#1962 10296 - AUTH API: Handle new state property
  auth-api/src/auth_api/utils/enums.py
  auth-web/src/components/auth/manage-business/AffiliatedEntityTable.vue
  auth-web/src/models/business.ts
  auth-web/src/util/common-util.ts
  auth-web/src/util/constants.ts
  queue_services/business-events-listener/app.py
  queue_services/business-events-listener/requirements.txt
  queue_services/business-events-listener/src/business_events_listener/worker.py
  queue_services/business-events-listener/tests/integration/test_worker_queue.py
  queue_services/business-events-listener/tests/integration/utils.py
Labels: enhancement

#1973 Revert "Updated Assets Staff Tile and Configurations"
  auth-web/babel.config.js
  auth-web/package-lock.json
  auth-web/package.json
  auth-web/src/assets/img/AssetsRegistries_dashboard.jpg
  auth-web/src/assets/img/ManufacturedHomeRegistry_dashboard.jpg
  auth-web/src/components/auth/staff/PPRLauncher.vue
  auth-web/src/locales/en.json
  auth-web/tests/unit/components/PPRLauncher.spec.ts
Labels: enhancement
