Repository bcgov/sbc-auth, pull requests merged in 2022-02, with the labels that each got.

#1907 branch name added to user settings
  auth-api/src/auth_api/models/user_settings.py
  auth-api/src/auth_api/schemas/schemas/user_settings_response.json
  auth-api/src/auth_api/schemas/user_settings.py
  auth-api/src/auth_api/services/user_settings.py
  auth-api/tests/unit/api/test_user_settings.py
  auth-api/tests/unit/services/test_user_settings.py
  docs/docs/api_contract/auth-api-1.0.0.yaml
Labels: enhancement

#1908 Expand account info drop down to include branch name#10476
  auth-web/package-lock.json
  auth-web/package.json
Labels: enhancement, skip-changelog

#1911 [FAS] - Logout not redirecting to Login Screen#11120 | common compon…
  auth-web/package-lock.json
  auth-web/package.json
Labels: bug

#1913 11098 - UI changes for allowing reject/approve onhold tasks
  auth-web/src/store/modules/staff.ts
  auth-web/src/views/auth/staff/ReviewAccountView.vue
Labels: enhancement

#1915 10651 - Add Govn confirmation dialog feature
  auth-web/src/locales/en.json
  auth-web/src/views/auth/ChooseAuthMethodView.vue
Labels: enhancement

#1917 fixed CI issue - keycloak sticky version
  auth-api/tests/docker/docker-compose.yml
  queue_services/account-mailer/requirements.txt
  queue_services/account-mailer/requirements/prod.txt
  queue_services/account-mailer/tests/docker/docker-compose.yml
Labels: devops
